// Batch: market-countries5 — add 6 high-commercial-value countries + data layer + Vehicle×Market relations.
// Countries: Australia (RHD), Russia (LHD, sanctions risk recorded), Georgia (LHD), Tunisia (LHD), Oman (LHD GCC), Bahrain (LHD GCC).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";
const GBTSRC = "https://en.wikipedia.org/wiki/GB/T_charging_standard";
const MODELS = "https://data.chinausedautohub.com/models/";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "australia", name: "Australia", name_zh: "澳大利亚", region: "oceania", drive_side: "rhd", currency: "AUD", status: "active", source: "Department of Infrastructure, Transport, Regional Development (ROVER) / Australian Border Force", source_url: "https://www.infrastructure.gov.au/infrastructure-transport-vehicles/vehicles/importing-road-vehicle-australia", source_date: D, confidence: "high" },
  { country_id: "russia", name: "Russia", name_zh: "俄罗斯", region: "europe", drive_side: "lhd", currency: "RUB", status: "active", source: "Federal Customs Service (FCS) / EAEU framework", source_url: "https://carawon.com/en/import-to-russia", source_date: D, confidence: "high" },
  { country_id: "georgia", name: "Georgia", name_zh: "格鲁吉亚", region: "europe", drive_side: "lhd", currency: "GEL", status: "active", source: "Revenue Service of Georgia (Customs)", source_url: "https://carawon.com/en/import-to-georgia", source_date: D, confidence: "high" },
  { country_id: "tunisia", name: "Tunisia", name_zh: "突尼斯", region: "africa", drive_side: "lhd", currency: "TND", status: "active", source: "Tunisian Customs (Direction Générale des Douanes)", source_url: "https://www.trade.gov/country-commercial-guides/tunisia-automotive-parts-services-equipment", source_date: D, confidence: "high" },
  { country_id: "oman", name: "Oman", name_zh: "阿曼", region: "middle-east", drive_side: "lhd", currency: "OMR", status: "active", source: "Royal Oman Police — Directorate General of Customs", source_url: "https://www.customs.gov.om/en/import-of-used-vehicles-motorcycles-and-classic-vehicles/", source_date: D, confidence: "high" },
  { country_id: "bahrain", name: "Bahrain", name_zh: "巴林", region: "middle-east", drive_side: "lhd", currency: "BHD", status: "active", source: "Bahrain Customs Affairs", source_url: "https://www.customs.gov.bh/en/faq", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Australia (RHD) =====
  { rule_id: "au-drive-side", country_id: "australia", category: "drive_side", title: "Right-hand drive (RHD) required", rule_text: "Australia drives on the left and registers right-hand-drive (RHD) vehicles. China-market LHD units cannot be registered as-is; source RHD export units (BYD, MG, GWM, Chery and others produce RHD for Australia).", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "au-rover-approval", country_id: "australia", category: "import_eligibility", title: "ROVER import approval mandatory (RVSA 2018)", rule_text: "Before importing a road vehicle, a Vehicle Import Approval must be obtained through ROVER under the Road Vehicle Standards Act 2018. Importing without approval is an offence. Used-vehicle pathways are narrow: the Specialist and Enthusiast Vehicle Scheme (SEVS), the 25-Year Rule, and the Personal Import Scheme (12+ months prior overseas ownership/use).", effective_date: null, last_checked: D, source: "Department of Infrastructure (ROVER / RVSA 2018)", source_url: "https://www.infrastructure.gov.au/infrastructure-transport-vehicles/vehicles/importing-road-vehicle-australia", confidence: "high", needs_review: true, notes: "Approval pathways are restrictive — verify current SEVS/PIS eligibility with the Department of Infrastructure before sourcing." },
  { rule_id: "au-age-limit", country_id: "australia", category: "vehicle_age", title: "No blanket age limit (standards-based)", rule_text: "Australia has no blanket used-vehicle age limit; eligibility is instead set by Australian Design Rules (ADR) conformity, emissions and frontal-impact standards, and the import-approval pathway. Non-compliant or non-approved used vehicles cannot be registered.", effective_date: null, last_checked: D, source: "Australian Border Force (importing a motor vehicle)", source_url: "https://www.abf.gov.au/importing-exporting-and-manufacturing/importing/how-to-import/types-of-imports/importing-a-motor-vehicle", confidence: "medium", needs_review: true, notes: "Standards-based, not age-based — confirm ADR and approval pathway with ROVER." },
  { rule_id: "au-ev-policy", country_id: "australia", category: "ev_policy", title: "No EV-specific import-duty relief (LCT fuel-efficient threshold)", rule_text: "Australia grants no EV-specific import-duty relief; 5% customs duty and 10% GST apply to all passenger vehicles. Electric and other fuel-efficient vehicles (≤7L/100km) benefit from a higher Luxury Car Tax (LCT) threshold before the 33% LCT applies on the excess.", effective_date: null, last_checked: D, source: "Australian Taxation Office (Luxury Car Tax) / Australian Border Force", source_url: "https://www.ato.gov.au/tax-rates-and-codes/luxury-car-tax-rate-and-thresholds", confidence: "medium", needs_review: true, notes: "LCT thresholds are indexed annually — verify current figures with the ATO." },

  // ===== Russia (LHD) =====
  { rule_id: "ru-drive-side", country_id: "russia", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Russia drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "ru-utilization-fee", country_id: "russia", category: "import_eligibility", title: "Utilization (recycling) fee + EPTS activation", rule_text: "Imported vehicles face a utilization (recycling) fee that escalated from 2024 and was further increased from 2025 (scrappage fees effectively doubled). Registration requires EPTS (electronic passport) activation. From 1 April 2024, Resolution 1291 closed the EAEU arbitrage loophole — cars cleared in Kyrgyzstan/Kazakhstan then imported into Russia pay the full domestic duty.", effective_date: "2025-01-01", last_checked: D, source: "Reuters / Interfax / Carawon (Russia import guide)", source_url: "https://www.reuters.com/business/autos-transportation/imported-cars-face-higher-fees-russia-plans-domestic-production-boost-2024-09-30/", confidence: "medium", needs_review: true, notes: "Utilization-fee amounts change frequently — verify current figures with the Federal Customs Service." },
  { rule_id: "ru-tax-stack", country_id: "russia", category: "import_eligibility", title: "Personal-import duty by engine cc + excise + 20% VAT", rule_text: "Personal import of a car into Russia is taxed by a combined customs-duty schedule keyed to engine displacement, plus an engine-power (horsepower) excise, plus 20% VAT, plus the utilization fee. Older and larger-engine vehicles attract higher charges.", effective_date: null, last_checked: D, source: "Carawon (Russia import guide)", source_url: "https://carawon.com/en/import-to-russia", confidence: "medium", needs_review: true, notes: "Duty is engine-cc based, not a single rate — verify with the Federal Customs Service." },
  { rule_id: "ru-age-limit", country_id: "russia", category: "vehicle_age", title: "No strict age limit identified (EAEU certification applies)", rule_text: "No single universal used-vehicle age limit was identified in the sources reviewed; eligibility is governed by EAEU technical certification and the utilization-fee + duty schedule, which rises for older vehicles. Confirm current used-vehicle eligibility with Russian customs.", effective_date: null, last_checked: D, source: "Needs verification (no explicit age rule located)", source_url: null, confidence: "unknown", needs_review: true, notes: "Used-vehicle eligibility not clearly documented — verify with the Federal Customs Service." },
  { rule_id: "ru-ev-policy", country_id: "russia", category: "ev_policy", title: "No EV duty relief + EV/hybrid sanctions sensitivity", rule_text: "Russia grants no EV-specific import-duty relief; EVs still pay the utilization fee, VAT and applicable charges. Separately, EU sanctions ban the export of all new and second-hand electric and hybrid vehicles (and cars over 1,900cc) to Russia from the EU — a constraint that does not directly bind China-origin vehicles but signals the sanctions environment around EV/hybrid trade.", effective_date: null, last_checked: D, source: "European Commission (import/export bans) / Reuters", source_url: "https://commission.europa.eu/topics/eu-solidarity-ukraine/eu-sanctions-against-russia-following-invasion-ukraine/import-and-export-bans_en", confidence: "medium", needs_review: true, notes: "EV/hybrid treatment and sanctions scope change — verify before trading." },
  { rule_id: "ru-sanctions", country_id: "russia", category: "other", title: "Sanctions risk (recorded truthfully)", rule_text: "Russia is subject to EU/US sanctions. Western automakers (Volkswagen, BMW, etc.) prohibit exports to Russia and have contractual safeguards; luxury-car (>1,900cc) and EV/hybrid exports are banned from the EU. Chinese-origin vehicles are not directly sanctioned, but transactions face banking/payment/logistics friction and enhanced compliance scrutiny; gray-market routing of Western brands into Russia carries enforcement risk (account freezes, searches, prosecution).", effective_date: null, last_checked: D, source: "Reuters (gray-market flow) / European Commission", source_url: "https://www.reuters.com/business/autos-transportation/foreign-cars-flow-russia-through-china-skirting-ukraine-war-sanctions-2026-02-12/", confidence: "medium", needs_review: true, notes: "Sanctions and compliance landscape changes frequently — obtain legal/compliance advice before trading." },

  // ===== Georgia (LHD) =====
  { rule_id: "ge-drive-side", country_id: "georgia", category: "drive_side", title: "Left-hand drive (LHD) standard; RHD penalised", rule_text: "Georgia drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive (RHD) vehicles are not banned outright but face a tripled excise rate in every age bracket (a strong disincentive).", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / CarSelect (RHD rate)", source_url: "https://carselect.ge/en/blog/rastamozhka-avto-iz-ssha-v-gruzii", confidence: "high", needs_review: true, notes: "RHD excise triples in every age bracket — verify current rates with the Revenue Service." },
  { rule_id: "ge-tax-stack", country_id: "georgia", category: "import_eligibility", title: "Nominal duty + per-cc excise + 18% VAT", rule_text: "Georgia runs one of the region's lightest customs regimes: import duty is nominal (about GEL 0.05 per cc plus 5% per year of age), plus a per-cc excise with a sharp age cliff at 6 years (1.5 GEL/cc under 6 years vs 4.5 GEL/cc over, as of April 2026), plus 18% VAT. RHD vehicles triple the excise.", effective_date: "2026-04-01", last_checked: D, source: "Carawon (Georgia import guide)", source_url: "https://carawon.com/en/import-to-georgia", confidence: "medium", needs_review: true, notes: "Excise is per-cc with an age cliff — verify current brackets with the Revenue Service." },
  { rule_id: "ge-age-cliff", country_id: "georgia", category: "vehicle_age", title: "6-year excise cliff (not a ban)", rule_text: "Georgia walked back a planned ban on passenger vehicles older than 6 years and instead applies a tax: the per-cc excise steps up sharply at 6 years of age (about 1.5 GEL/cc to 4.5 GEL/cc). Older vehicles remain importable but carry a materially higher excise.", effective_date: "2026-04-01", last_checked: D, source: "WC Shipping (Georgia 6-year rule update)", source_url: "https://www.wcshipping.com/blog/georgias-6-year-car-import-rule-what-changed-in-poti-2026-update", confidence: "medium", needs_review: true, notes: "The 6-year threshold is a tax cliff, not a prohibition — verify current rates." },
  { rule_id: "ge-ev-policy", country_id: "georgia", category: "ev_policy", title: "EV exemption (0% duty + no excise, 18% VAT only)", rule_text: "Electric vehicles are exempt from Georgia's import duty and per-cc excise, leaving 18% VAT as the main charge — a strong relief delta versus combustion vehicles. Euro 5 emission conformity applies to ICE imports.", effective_date: null, last_checked: D, source: "Guazi (Georgia 2026 import rules) / Carawon", source_url: "https://en.guazi.com/blog/insight/georgia-used-car-import-guide.html", confidence: "medium", needs_review: true, notes: "EV exemption is source-backed — verify current status with the Revenue Service." },
  { rule_id: "ge-euro5", country_id: "georgia", category: "emission", title: "Euro 5 emission conformity", rule_text: "Imported combustion vehicles must meet Euro 5 emission standards. Re-export through Poti/Batumi to Armenia, Azerbaijan and Central Asia may skip the tax if re-exported.", effective_date: null, last_checked: D, source: "Guazi (Georgia 2026 import rules)", source_url: "https://en.guazi.com/blog/insight/georgia-used-car-import-guide.html", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with the Revenue Service." },

  // ===== Tunisia (LHD) =====
  { rule_id: "tn-drive-side", country_id: "tunisia", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Tunisia drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "tn-age-limit", country_id: "tunisia", category: "vehicle_age", title: "Used cars under 5 years old", rule_text: "Since 2012 Tunisia has prohibited the entry of vehicles older than five years (an individual used-vehicle import must be no more than 5 years old). The imported vehicle requires an FCR (Fiche de Contrôle de Conformité) conformity certificate.", effective_date: null, last_checked: D, source: "US ITA Country Commercial Guide (trade.gov) / ElJaziraTransit", source_url: "https://www.trade.gov/country-commercial-guides/tunisia-automotive-parts-services-equipment", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Tunisian Customs." },
  { rule_id: "tn-fcr", country_id: "tunisia", category: "import_eligibility", title: "FCR conformity certificate required", rule_text: "Individual used-vehicle import requires a FCR (Fiche de Contrôle de Conformité) conformity certificate and the importer must be a Tunisian citizen aged 18+. High ICE tariffs plus 19% VAT and a consumption tax make combustion imports expensive.", effective_date: null, last_checked: D, source: "ElJaziraTransit (Tunisia import guide)", source_url: "https://eljaziratransit.com/en/blog/guide-importation-voiture-tunisie-fcr-electrique", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Tunisian Customs." },
  { rule_id: "tn-ev-policy", country_id: "tunisia", category: "ev_policy", title: "EV full exemption (0% duty + 0% VAT + 0% consumption)", rule_text: "Fully electric vehicles under 5 years old may pay 0% customs duty, 0% VAT and 0% consumption tax in Tunisia (2026) — one of the strongest EV relief packages in North Africa. This makes recent Chinese EVs the standout import category.", effective_date: null, last_checked: D, source: "EV24.africa (Tunisia EV import)", source_url: "https://www.ev24.africa/import-electric-car-tunisia-taxes-customs-registration/", confidence: "medium", needs_review: true, notes: "EV exemption is source-backed — verify current scope with Tunisian Customs." },

  // ===== Oman (LHD GCC) =====
  { rule_id: "om-drive-side", country_id: "oman", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Oman drives on the right and registers left-hand-drive (LHD) vehicles under GCC standard specifications.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "om-age-limit", country_id: "oman", category: "vehicle_age", title: "Private vehicles under 7 years old", rule_text: "Oman Customs permits import of private vehicles less than 7 years old (trucks/buses under 10 years, equipment under 15 years). The importer must be at least 18 years old for personal import, and vehicles must comply with the standard specifications in force in the Sultanate.", effective_date: null, last_checked: D, source: "Royal Oman Police — Directorate General of Customs", source_url: "https://www.customs.gov.om/en/import-of-used-vehicles-motorcycles-and-classic-vehicles/", confidence: "high", needs_review: true, notes: "Official source — verify current age limits with Oman Customs." },
  { rule_id: "om-gcc-spec", country_id: "oman", category: "import_eligibility", title: "GCC standard specification required", rule_text: "Imported vehicles must comply with the standard specifications in force in the Sultanate (GCC specification). A flat 5% customs duty plus 5% VAT applies.", effective_date: null, last_checked: D, source: "Royal Oman Police — Directorate General of Customs", source_url: "https://www.customs.gov.om/en/import-of-used-vehicles-motorcycles-and-classic-vehicles/", confidence: "high", needs_review: true, notes: "GCC specification is mandatory — verify with Oman Customs." },
  { rule_id: "om-ev-policy", country_id: "oman", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was identified for Oman in the sources reviewed; the flat 5% customs duty plus 5% VAT applies to all vehicles.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented in reviewed sources — verify with Oman Customs." },

  // ===== Bahrain (LHD GCC) =====
  { rule_id: "bh-drive-side", country_id: "bahrain", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Bahrain drives on the right and registers left-hand-drive (LHD) vehicles under GCC specification.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "bh-age-limit", country_id: "bahrain", category: "vehicle_age", title: "Age limit ~5 years (5–10 years pay BHD 1,000 fee)", rule_text: "Bahrain restricts imported vehicles to about 5 years of age; vehicles aged 5 to 10 years are subject to an additional flat import fee of BHD 1,000 (with heightened border scrutiny). Bahrain's parliament has considered extending the age limit from 5 to 10 years.", effective_date: null, last_checked: D, source: "JP Sheet (Bahrain import guide) / Expat Focus", source_url: "https://jpsheet.com/import-guide/bahrain/", confidence: "medium", needs_review: true, notes: "Age-limit policy is in flux (5 vs 10 years) — verify with Bahrain Customs." },
  { rule_id: "bh-gcc-spec", country_id: "bahrain", category: "import_eligibility", title: "GCC specification + 5% duty + 10% VAT", rule_text: "Imported vehicles must conform to GCC specification. Bahrain applies 5% customs duty plus 10% VAT (total ~15% on CIF + duty), the highest VAT in the GCC. Vehicles imported from other GCC countries with proof of prior duty payment may be exempt.", effective_date: null, last_checked: D, source: "Bahrain Customs Affairs (FAQ)", source_url: "https://www.customs.gov.bh/en/faq", confidence: "high", needs_review: true, notes: "Verify current duty/VAT with Bahrain Customs." },
  { rule_id: "bh-ev-policy", country_id: "bahrain", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was identified for Bahrain in the sources reviewed; the 5% customs duty plus 10% VAT applies. Bahrain has EV-adoption incentives, but their application to used imports is not confirmed in reviewed sources.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with Bahrain Customs." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  // Australia
  { taxrule_id: "au-duty", country_id: "australia", tax_type: "import_duty", label: "Import duty (passenger vehicles)", rate_pct: 5, basis: "CIF value", effective_date: null, last_checked: D, source: "Australian Border Force (importing a motor vehicle)", source_url: "https://www.abf.gov.au/importing-exporting-and-manufacturing/importing/how-to-import/types-of-imports/importing-a-motor-vehicle", confidence: "medium", needs_review: true, notes: "5% on most passenger vehicles; some origins are duty-free under FTAs. Verify with ABF." },
  { taxrule_id: "au-gst", country_id: "australia", tax_type: "vat", label: "GST", rate_pct: 10, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Australian Border Force", source_url: "https://www.abf.gov.au/importing-exporting-and-manufacturing/importing/how-to-import/types-of-imports/importing-a-motor-vehicle", confidence: "medium", needs_review: false },
  { taxrule_id: "au-lct", country_id: "australia", tax_type: "excise", label: "Luxury Car Tax (LCT, above threshold)", rate_pct: 33, basis: "GST-inclusive value above threshold", effective_date: "2026-07-01", last_checked: D, source: "Australian Taxation Office (LCT rate and thresholds)", source_url: "https://www.ato.gov.au/tax-rates-and-codes/luxury-car-tax-rate-and-thresholds", confidence: "medium", needs_review: true, notes: "33% on the value above the threshold (indexed annually; fuel-efficient ≤7L/100km vehicles have a higher threshold). Verify current thresholds with the ATO." },

  // Russia
  { taxrule_id: "ru-vat", country_id: "russia", tax_type: "vat", label: "VAT", rate_pct: 20, basis: "CIF + duty + excise", effective_date: null, last_checked: D, source: "Carawon (Russia import guide)", source_url: "https://carawon.com/en/import-to-russia", confidence: "medium", needs_review: false, notes: "20% VAT applies on the cumulative base; utilization fee and engine-cc duty are separate (see import rules)." },

  // Georgia
  { taxrule_id: "ge-vat", country_id: "georgia", tax_type: "vat", label: "VAT", rate_pct: 18, basis: "Vehicle value", effective_date: null, last_checked: D, source: "Carawon (Georgia import guide)", source_url: "https://carawon.com/en/import-to-georgia", confidence: "medium", needs_review: false },
  { taxrule_id: "ge-ev-duty", country_id: "georgia", tax_type: "import_duty", label: "Import duty + excise (electric vehicles, exempt)", rate_pct: 0, basis: "Vehicle value", effective_date: null, last_checked: D, source: "Guazi (Georgia 2026 import rules) / Carawon", source_url: "https://en.guazi.com/blog/insight/georgia-used-car-import-guide.html", confidence: "medium", needs_review: true, notes: "EVs are exempt from import duty and per-cc excise (18% VAT only). Verify with the Revenue Service." },

  // Tunisia
  { taxrule_id: "tn-vat", country_id: "tunisia", tax_type: "vat", label: "VAT", rate_pct: 19, basis: "Vehicle value", effective_date: null, last_checked: D, source: "Tutor2u / ElJaziraTransit (Tunisia)", source_url: "https://eljaziratransit.com/en/blog/guide-importation-voiture-tunisie-fcr-electrique", confidence: "medium", needs_review: false },
  { taxrule_id: "tn-ev-duty", country_id: "tunisia", tax_type: "import_duty", label: "Import duty (electric vehicles, exempt)", rate_pct: 0, basis: "Vehicle value", effective_date: null, last_checked: D, source: "EV24.africa (Tunisia EV import)", source_url: "https://www.ev24.africa/import-electric-car-tunisia-taxes-customs-registration/", confidence: "medium", needs_review: true, notes: "Fully electric vehicles under 5 years: 0% customs duty + 0% VAT + 0% consumption tax (2026). Verify with Tunisian Customs." },

  // Oman
  { taxrule_id: "om-duty", country_id: "oman", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: 5, basis: "CIF value", effective_date: null, last_checked: D, source: "Royal Oman Police — Directorate General of Customs / YouhuAuto", source_url: "https://www.customs.gov.om/en/import-of-used-vehicles-motorcycles-and-classic-vehicles/", confidence: "medium", needs_review: true, notes: "5% standard GCC customs duty. Verify with Oman Customs." },
  { taxrule_id: "om-vat", country_id: "oman", tax_type: "vat", label: "VAT", rate_pct: 5, basis: "CIF + duty", effective_date: null, last_checked: D, source: "YouhuAuto (Middle East import guide) / Oman Tax Authority", source_url: "https://youhuauto.com/blogs/car-export/middle-east-vehicle-import-guide", confidence: "medium", needs_review: true, notes: "5% VAT (introduced 2021). Verify with the Oman Tax Authority." },

  // Bahrain
  { taxrule_id: "bh-duty", country_id: "bahrain", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: 5, basis: "CIF value", effective_date: null, last_checked: D, source: "Bahrain Customs Affairs (FAQ)", source_url: "https://www.customs.gov.bh/en/faq", confidence: "high", needs_review: true, notes: "5% customs duty. Verify with Bahrain Customs." },
  { taxrule_id: "bh-vat", country_id: "bahrain", tax_type: "vat", label: "VAT", rate_pct: 10, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Bahrain Customs Affairs (FAQ)", source_url: "https://www.customs.gov.bh/en/faq", confidence: "high", needs_review: true, notes: "10% VAT (highest in the GCC). Total taxes ~15% (5% customs + 10% VAT). Verify with Bahrain Customs." },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "cn-manzhouli", name: "Manzhouli (满洲里) land border", country_id: "cn", type: "origin", note: "Land/rail border crossing for Russia overland" },
  { port_id: "au-melbourne", name: "Melbourne", country_id: "australia", type: "destination", note: null },
  { port_id: "au-sydney", name: "Sydney (Port Botany)", country_id: "australia", type: "destination", note: null },
  { port_id: "au-brisbane", name: "Brisbane", country_id: "australia", type: "destination", note: null },
  { port_id: "ru-vladivostok", name: "Vladivostok", country_id: "russia", type: "destination", note: "Far East — primary entry for China-origin RoRo" },
  { port_id: "ru-zabaykalsk", name: "Zabaykalsk (land border)", country_id: "russia", type: "destination", note: "Overland via Manzhouli rail/road crossing" },
  { port_id: "ge-poti", name: "Poti", country_id: "georgia", type: "destination", note: "Black Sea — re-export hub" },
  { port_id: "ge-batumi", name: "Batumi", country_id: "georgia", type: "destination", note: "Black Sea" },
  { port_id: "tn-rades", name: "Rades (Tunis)", country_id: "tunisia", type: "destination", note: null },
  { port_id: "tn-sfax", name: "Sfax", country_id: "tunisia", type: "destination", note: null },
  { port_id: "om-sohar", name: "Sohar", country_id: "oman", type: "destination", note: null },
  { port_id: "om-salalah", name: "Salalah", country_id: "oman", type: "destination", note: null },
  { port_id: "bh-khalifa", name: "Khalifa Bin Salman Port (Hidd)", country_id: "bahrain", type: "destination", note: null },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-au-melbourne", origin_port_id: "cn-shanghai", destination_port_id: "au-melbourne", est_days_min: 16, est_days_max: 24, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-au-sydney", origin_port_id: "cn-shanghai", destination_port_id: "au-sydney", est_days_min: 16, est_days_max: 26, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-tianjin-to-ru-vladivostok", origin_port_id: "cn-tianjin", destination_port_id: "ru-vladivostok", est_days_min: 4, est_days_max: 8, shipping_method: "roro", source: "Industry route estimates (short Far East sea leg)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-manzhouli-to-ru-zabaykalsk", origin_port_id: "cn-manzhouli", destination_port_id: "ru-zabaykalsk", est_days_min: 2, est_days_max: 5, shipping_method: "container", source: "Industry route estimates (overland rail/road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-ge-poti", origin_port_id: "cn-shanghai", destination_port_id: "ge-poti", est_days_min: 24, est_days_max: 34, shipping_method: "roro", source: "Industry route estimates (Suez / Black Sea)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-tn-rades", origin_port_id: "cn-shanghai", destination_port_id: "tn-rades", est_days_min: 20, est_days_max: 30, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-om-sohar", origin_port_id: "cn-guangzhou", destination_port_id: "om-sohar", est_days_min: 12, est_days_max: 18, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-bh-khalifa", origin_port_id: "cn-shanghai", destination_port_id: "bh-khalifa", est_days_min: 14, est_days_max: 20, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

// ---------- vehicle-market.json relations ----------
const vm = read("vehicle-market.json");
vm.meta.batch = "batch 16 — market-countries5";
vm.meta.updated = D;

const dsMatch = (summary) => ({ status: "match", summary, source: "Data sub-site models.json (export intelligence) + Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, source_type: "database", confidence: "high", checked_date: D });
const dsRhd = (model, market, extra) => ({ status: "needs_conversion", summary: `China domestic-market production is left-hand drive (LHD), but ${market} registers right-hand drive (RHD) only — ${model} is produced in RHD for export markets (${extra}). Confirm RHD availability with the exporter and source an RHD unit.`, source: "Data sub-site models.json (export intelligence) + Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, source_type: "database", confidence: "medium", checked_date: D, needs_review: true });
const charging = (dest) => ({ standard: "GB/T", destination_standard: dest, connector: "GB/T AC / GB/T DC (vehicle inlet)", voltage: null, frequency: null, needs_adapter: true, notes: `China-market GB/T inlet vs ${dest} network — adapter required; confirm the sourced unit's inlet (some export units carry a CCS2 inlet).`, source: "Vehicle: GB/T charging standard (Wikipedia); Destination: Combined Charging System / Type 2 (Wikipedia)", source_url: GBTSRC, source_type: "reputable_media", confidence: "medium", checked_date: D, needs_review: true });

const relations = [
  // ===== Australia (RHD, duty 5% + GST 10% + LCT, ROVER approval) =====
  {
    vehicle_id: "byd-atto-3", country_id: "australia",
    drive_side_fit: dsRhd("BYD Atto 3", "Australia", "official Australian RHD launch"),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Australia grants no EV-specific duty relief (5% duty + 10% GST), but EVs qualify for the higher fuel-efficient Luxury Car Tax threshold (33% LCT only above it). EV adoption is among the fastest in the region.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)"),
    import_eligibility: { status: "conformity_required", requirements: ["ROVER import approval (RVSA 2018)", "RHD export unit"], notes: "Australia's used-import pathways are narrow (SEVS, 25-Year Rule, Personal Import Scheme); a new RHD Atto 3 enters under standard ROVER approval while a used unit must fit an approval pathway. Confirm the pathway before sourcing.", source: "market sub-site importrules.json (ROVER approval)", source_url: "https://www.infrastructure.gov.au/infrastructure-transport-vehicles/vehicles/importing-road-vehicle-australia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "au-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "au-gst", ev_duty_relief: false, notes: "No EV relief — 5% duty + 10% GST (+ 33% LCT above the fuel-efficient threshold). Referenced from taxrules.json — verify with ABF/ATO.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.ato.gov.au/tax-rates-and-codes/luxury-car-tax-rate-and-thresholds", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-au-melbourne", "cn-shanghai-to-au-sydney"], notes: "Sea freight to Melbourne or Sydney (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV with strong RHD availability for Australia; RHD sourcing, ROVER approval and the LCT threshold are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "byd-sealion-6", country_id: "australia",
    drive_side_fit: dsRhd("BYD Sealion 6 (宋PLUS export)", "Australia", "official Australian RHD launch"),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "PHEV (plug-in hybrid, DM-i) — PHEV classification is the key open question for Australia: whether the DM-i trim qualifies for the fuel-efficient LCT threshold (≤7L/100km) and the FBT/novated-lease treatment, versus a BEV. No EV-specific duty relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)"),
    import_eligibility: { status: "conformity_required", requirements: ["ROVER import approval (RVSA 2018)", "RHD export unit"], notes: "PHEV classification under Australia's LCT fuel-efficient threshold and the narrow used-import pathways are the open questions. RHD required.", source: "market sub-site importrules.json (ROVER approval)", source_url: "https://www.infrastructure.gov.au/infrastructure-transport-vehicles/vehicles/importing-road-vehicle-australia", source_type: "regulatory", confidence: "low", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "au-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "au-gst", ev_duty_relief: false, notes: "No PHEV duty relief — 5% duty + 10% GST; PHEV may qualify for the fuel-efficient LCT threshold (verify with ATO). Referenced from taxrules.json.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.ato.gov.au/tax-rates-and-codes/luxury-car-tax-rate-and-thresholds", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-au-melbourne"], notes: "Sea freight to Melbourne (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Sealion 6 is a compact PHEV SUV sold RHD in Australia; PHEV-vs-BEV LCT classification and ROVER approval are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/seal-u", source_type: "manufacturer", confidence: "low", checked_date: D,
  },

  // ===== Russia (LHD, utilization fee + EAEU, sanctions risk) =====
  {
    vehicle_id: "li-auto-l7", country_id: "russia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Russia registers LHD only — no conversion required."),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "EREV (extended-range electric vehicle) — a class whose EAEU utilization-fee and engine-cc duty bracket is under-explained and must be confirmed; EREVs are a fast-growing import segment in Russia. No EV-specific duty relief applies, and EV/hybrid trade faces sanctions sensitivity.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("GB/T / CCS2 (mixed)"),
    import_eligibility: { status: "conformity_required", requirements: ["EAEU technical certification", "EPTS activation", "Utilization (recycling) fee"], notes: "EREV classification under the utilization-fee and engine-cc schedule is the open question; EAEU certification and EPTS activation apply. Sanctions add banking/payment friction.", source: "market sub-site importrules.json (utilization fee + EAEU)", source_url: "https://carawon.com/en/import-to-russia", source_type: "regulatory", confidence: "low", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: null, ev_duty_taxrule_id: null, vat_taxrule_id: "ru-vat", ev_duty_relief: false, notes: "No EV/EREV duty relief — utilization fee + engine-cc duty + excise + 20% VAT. Referenced from taxrules.json (VAT only; duty is engine-cc based) — verify with the Federal Customs Service.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-russia", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-tianjin-to-ru-vladivostok", "cn-manzhouli-to-ru-zabaykalsk"], notes: "Sea to Vladivostok (RoRo) or overland via Manzhouli/Zabaykalsk (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Li Auto L7 (理想L7) is an EREV SUV; EREV classification under Russia's utilization-fee/duty schedule and the sanctions environment (EU EV/hybrid export ban; banking friction) are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Li_L7", source_type: "reputable_media", confidence: "low", checked_date: D,
  },
  {
    vehicle_id: "byd-han", country_id: "russia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Russia registers LHD only — no conversion required."),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "EV and PHEV (DM-i) trims — PHEV-vs-EV classification under Russia's utilization-fee and EAEU duty schedule is the key open question; neither class receives EV-specific duty relief, and EV/hybrid trade is sanctions-sensitive (EU bans EV/hybrid exports to Russia).", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("GB/T / CCS2 (mixed)"),
    import_eligibility: { status: "conformity_required", requirements: ["EAEU technical certification", "EPTS activation", "Utilization (recycling) fee"], notes: "PHEV-vs-EV utilization-fee classification and EAEU certification are the open questions; sanctions add banking friction.", source: "market sub-site importrules.json (utilization fee + EAEU)", source_url: "https://carawon.com/en/import-to-russia", source_type: "regulatory", confidence: "low", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: null, ev_duty_taxrule_id: null, vat_taxrule_id: "ru-vat", ev_duty_relief: false, notes: "No EV/PHEV duty relief — utilization fee + engine-cc duty + excise + 20% VAT. Referenced from taxrules.json — verify with the Federal Customs Service.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-russia", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-tianjin-to-ru-vladivostok", "cn-manzhouli-to-ru-zabaykalsk"], notes: "Sea to Vladivostok (RoRo) or overland via Manzhouli/Zabaykalsk (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Han (汉) is an EV/PHEV sedan; PHEV-vs-EV utilization-fee classification and the sanctions environment are the key fit questions for Russia.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/han", source_type: "manufacturer", confidence: "low", checked_date: D,
  },

  // ===== Georgia (LHD, EV exemption + 6-year excise cliff + re-export) =====
  {
    vehicle_id: "byd-atto-3", country_id: "georgia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Georgia registers LHD — no conversion required."),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Georgia exempts EVs from import duty and the per-cc excise (18% VAT only), versus a nominal duty plus age-cliff excise for combustion vehicles. A strong EV relief delta, reinforced by Georgia's Poti/Batumi re-export corridor.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)"),
    import_eligibility: { status: "conformity_required", requirements: ["Euro 5 (ICE only, not EV)", "Customs declaration"], notes: "EVs are exempt from duty and excise (18% VAT only); re-export through Poti/Batumi may skip the tax if re-exported. Confirm EV-exemption scope with the Revenue Service.", source: "market sub-site importrules.json (EV exemption)", source_url: "https://en.guazi.com/blog/insight/georgia-used-car-import-guide.html", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: null, ev_duty_taxrule_id: "ge-ev-duty", vat_taxrule_id: "ge-vat", ev_duty_relief: true, notes: "EV: 0% duty + no excise + 18% VAT (vs nominal duty + per-cc age-cliff excise for ICE). Referenced from taxrules.json — verify with the Revenue Service.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-georgia", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-ge-poti"], notes: "Sea freight to Poti (RoRo); Batumi as alternative — re-export to Armenia/Azerbaijan/Central Asia.", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Georgia's EV duty/excise exemption and re-export corridor are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "geely-monjaro", country_id: "georgia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Georgia registers LHD — no conversion required."),
    age_rule_fit: { status: "borderline", summary: "Monjaro production began 2021; Georgia's 6-year excise cliff means 2021 units are now ~5 years old (under the cliff for now, but approaching it) — source 2022+ units to stay in the lower excise bracket. Verify the exact manufacture date.", source: "market sub-site importrules.json (6-year excise cliff)", source_url: "https://www.wcshipping.com/blog/georgias-6-year-car-import-rule-what-changed-in-poti-2026-update", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to nominal duty (GEL 0.05/cc + 5%/year of age) plus a per-cc excise (1.5 GEL/cc under 6 years) and 18% VAT; no EV relief applies. Euro 5 conformity required.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["Euro 5 emission conformity", "Customs declaration"], notes: "Euro 5 conformity and the per-cc age-cliff excise are the key filters; the 6-year cliff drives a material excise step-up.", source: "market sub-site importrules.json (tax stack + Euro 5)", source_url: "https://carawon.com/en/import-to-georgia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: null, ev_duty_taxrule_id: null, vat_taxrule_id: "ge-vat", ev_duty_relief: false, notes: "ICE: nominal duty + per-cc excise (age cliff) + 18% VAT — no flat % duty recorded. Referenced from taxrules.json (VAT) — verify with the Revenue Service.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-georgia", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-ge-poti"], notes: "Sea freight to Poti (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; Georgia's 6-year excise cliff (2021 units approaching it) and Euro 5 conformity are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "chery-tiggo-8", country_id: "georgia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Georgia registers LHD — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 8 production began 2018; Georgia's 6-year excise cliff means 2018 units are now ~8 years old — past the cliff, so they pay the higher excise (4.5 GEL/cc vs 1.5 GEL/cc) rather than being banned. Source 2021+ units to stay in the lower bracket.", source: "market sub-site importrules.json (6-year excise cliff)", source_url: "https://www.wcshipping.com/blog/georgias-6-year-car-import-rule-what-changed-in-poti-2026-update", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — older units (past 6 years) face the higher per-cc excise bracket; no EV relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["Euro 5 emission conformity", "Customs declaration"], notes: "Euro 5 conformity and the age-cliff excise are the key filters; units past 6 years pay the higher excise bracket.", source: "market sub-site importrules.json (tax stack + Euro 5)", source_url: "https://carawon.com/en/import-to-georgia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: null, ev_duty_taxrule_id: null, vat_taxrule_id: "ge-vat", ev_duty_relief: false, notes: "ICE: nominal duty + per-cc excise (higher bracket past 6 years) + 18% VAT. Referenced from taxrules.json (VAT) — verify with the Revenue Service.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-georgia", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-ge-poti"], notes: "Sea freight to Poti (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 8 is an ICE SUV; Georgia's 6-year excise cliff puts 2018 units in the higher excise bracket — the age cliff is the key fit point.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_8", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Tunisia (LHD, EV full exemption + 5-year age limit) =====
  {
    vehicle_id: "byd-atto-3", country_id: "tunisia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Tunisia registers LHD only — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Atto 3 production began 2022; Tunisia's under-5-years rule means 2022 units are now ~4 years old (eligible). Verify the exact manufacture date.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://www.trade.gov/country-commercial-guides/tunisia-automotive-parts-services-equipment", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Tunisia grants fully electric vehicles under 5 years 0% customs duty, 0% VAT and 0% consumption tax (2026) — the strongest EV relief in North Africa versus high ICE tariffs + 19% VAT.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes) — early-stage"),
    import_eligibility: { status: "conformity_required", requirements: ["FCR conformity certificate", "<5 years old"], notes: "Under-5-years age rule and FCR conformity are the hard filters; the EV full-exemption applies to eligible units.", source: "market sub-site importrules.json (FCR + age + EV exemption)", source_url: "https://www.ev24.africa/import-electric-car-tunisia-taxes-customs-registration/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: null, ev_duty_taxrule_id: "tn-ev-duty", vat_taxrule_id: "tn-vat", ev_duty_relief: true, notes: "EV <5yr: 0% duty + 0% VAT + 0% consumption (vs high ICE tariffs + 19% VAT). Referenced from taxrules.json — verify with Tunisian Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.ev24.africa/import-electric-car-tunisia-taxes-customs-registration/", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-tn-rades"], notes: "Sea freight to Rades/Tunis (RoRo); Sfax as alternative.", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Tunisia's EV full-exemption (0% duty/VAT/consumption) and the under-5-years rule are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "geely-monjaro", country_id: "tunisia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Tunisia registers LHD only — no conversion required."),
    age_rule_fit: { status: "borderline", summary: "Monjaro production began 2021; Tunisia's under-5-years rule makes 2021 units ~5 years old (borderline) — source 2022+ units and verify the exact cut-off with Tunisian Customs.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://www.trade.gov/country-commercial-guides/tunisia-automotive-parts-services-equipment", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to high ICE tariffs plus 19% VAT and a consumption tax; no EV relief applies. This makes ICE imports expensive versus the EV full-exemption.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["FCR conformity certificate", "<5 years old"], notes: "Under-5-years rule and FCR conformity are the hard filters; the ICE tariff stack is materially higher than the EV exemption.", source: "market sub-site importrules.json (FCR + age)", source_url: "https://eljaziratransit.com/en/blog/guide-importation-voiture-tunisie-fcr-electrique", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: null, ev_duty_taxrule_id: null, vat_taxrule_id: "tn-vat", ev_duty_relief: false, notes: "ICE: high import tariffs + 19% VAT + consumption tax (no clean single % recorded). Referenced from taxrules.json (VAT) — verify with Tunisian Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://eljaziratransit.com/en/blog/guide-importation-voiture-tunisie-fcr-electrique", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-tn-rades"], notes: "Sea freight to Rades/Tunis (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; Tunisia's under-5-years rule (2021 units borderline) and the high ICE tariff stack are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Oman (LHD GCC, 7-year age limit) =====
  {
    vehicle_id: "chery-tiggo-8", country_id: "oman",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Oman registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 8 production began 2018; Oman's 7-year age limit for private vehicles means 2018 units are now ~8 years old (ineligible) — source 2019+ units and verify the cut-off with Oman Customs.", source: "market sub-site importrules.json (7-year age limit)", source_url: "https://www.customs.gov.om/en/import-of-used-vehicles-motorcycles-and-classic-vehicles/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to Oman's flat 5% customs duty plus 5% VAT; no EV-specific relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["GCC specification", "<7 years old"], notes: "The 7-year age limit for private vehicles is the hard blocker for 2018 units; GCC specification applies.", source: "market sub-site importrules.json (age limit + GCC spec)", source_url: "https://www.customs.gov.om/en/import-of-used-vehicles-motorcycles-and-classic-vehicles/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "om-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "om-vat", ev_duty_relief: false, notes: "ICE: 5% duty + 5% VAT. Referenced from taxrules.json — verify with Oman Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.customs.gov.om/en/import-of-used-vehicles-motorcycles-and-classic-vehicles/", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-guangzhou-to-om-sohar"], notes: "Sea freight to Sohar (RoRo); Salalah as alternative.", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 8 is an ICE SUV; Oman's 7-year age limit renders 2018 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_8", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Bahrain (LHD GCC, ~5-year age limit, 10% VAT) =====
  {
    vehicle_id: "geely-monjaro", country_id: "bahrain",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Bahrain registers LHD only — no conversion required."),
    age_rule_fit: { status: "borderline", summary: "Monjaro production began 2021; Bahrain's ~5-year age limit makes 2021 units ~5 years old (borderline; 5–10-year units pay a BHD 1,000 fee) — source 2022+ units and verify the cut-off with Bahrain Customs.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://jpsheet.com/import-guide/bahrain/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to Bahrain's 5% customs duty plus 10% VAT (highest in the GCC); no EV-specific relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["GCC specification", "~5 years old"], notes: "The ~5-year age limit (5–10-year units pay BHD 1,000) and GCC specification are the key filters.", source: "market sub-site importrules.json (age limit + GCC spec)", source_url: "https://jpsheet.com/import-guide/bahrain/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "bh-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "bh-vat", ev_duty_relief: false, notes: "ICE: 5% duty + 10% VAT (~15% total). Referenced from taxrules.json — verify with Bahrain Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.customs.gov.bh/en/faq", source_type: "government", confidence: "high", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-bh-khalifa"], notes: "Sea freight to Khalifa Bin Salman Port (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; Bahrain's ~5-year age limit (2021 units borderline) and 10% VAT are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "chery-tiggo-8", country_id: "bahrain",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Bahrain registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 8 production began 2018; Bahrain's ~5-year age limit makes 2018 units ~8 years old (ineligible; 5–10-year units pay a BHD 1,000 fee) — source 2021+ units and verify the cut-off with Bahrain Customs.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://jpsheet.com/import-guide/bahrain/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to 5% customs duty plus 10% VAT; no EV-specific relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["GCC specification", "~5 years old"], notes: "The ~5-year age limit (2018 units ineligible) and GCC specification are the key filters.", source: "market sub-site importrules.json (age limit + GCC spec)", source_url: "https://jpsheet.com/import-guide/bahrain/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "bh-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "bh-vat", ev_duty_relief: false, notes: "ICE: 5% duty + 10% VAT (~15% total). Referenced from taxrules.json — verify with Bahrain Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.customs.gov.bh/en/faq", source_type: "government", confidence: "high", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-bh-khalifa"], notes: "Sea freight to Khalifa Bin Salman Port (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 8 is an ICE SUV; Bahrain's ~5-year age limit renders 2018 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_8", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
];

const skips = [
  { vehicle_id: "byd-seal", country_id: "australia", reason: "EV × RHD — RHD + charging + no-EV-relief delta already represented by byd-atto-3 × australia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "mg-4", country_id: "australia", reason: "EV × RHD — RHD + charging delta already represented by byd-atto-3 × australia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "chery-tiggo-8", country_id: "australia", reason: "ICE × RHD — used-import restriction (ROVER/SEVS/PIS) is a market-level fact (stated on the Australia page); RHD ICE delta already represented by chery-tiggo-8 × kenya/nigeria (mechanical ICE×RHD cross-product, avoid)." },
  { vehicle_id: "geely-monjaro", country_id: "russia", reason: "ICE × LHD — utilization fee + engine-cc duty are market-level facts, not a vehicle×market increment; no age conflict and no distinct increment (fails the generation gate)." },
  { vehicle_id: "byd-atto-3", country_id: "russia", reason: "EV × LHD — Russia grants no EV duty relief and Chinese EVs use GB/T charging (no adapter increment); utilization fee is a market-level fact (fails the generation gate)." },
  { vehicle_id: "yangwang-u8", country_id: "russia", reason: "EREV × LHD — EREV classification + sanctions delta already represented by li-auto-l7 × russia (mechanical EREV cross-product, avoid)." },
  { vehicle_id: "byd-seal", country_id: "georgia", reason: "EV × LHD — EV duty/excise-exemption delta already represented by byd-atto-3 × georgia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "byd-dolphin", country_id: "georgia", reason: "EV × LHD — EV exemption delta already represented by byd-atto-3 × georgia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "chery-tiggo-8", country_id: "tunisia", reason: "ICE × LHD — 5-year age-rule delta already represented by geely-monjaro × tunisia (mechanical ICE cross-product, avoid)." },
  { vehicle_id: "byd-seal", country_id: "tunisia", reason: "EV × LHD — EV full-exemption delta already represented by byd-atto-3 × tunisia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "great-wall-haval-h6", country_id: "oman", reason: "ICE × LHD — 2020 units are ~6 years old (under the 7-year limit, no age conflict); 5% duty + 5% VAT is a market-level fact (no distinct increment, avoid)." },
  { vehicle_id: "byd-atto-3", country_id: "oman", reason: "EV × LHD — Oman has no EV-specific duty relief (flat 5% + 5% VAT) and no distinct EV increment; charging-only delta already represented (defer, like UAE/Qatar)." },
  { vehicle_id: "byd-atto-3", country_id: "bahrain", reason: "EV × LHD — Bahrain has no EV-specific import-duty relief recorded (flat 5% + 10% VAT) and no distinct EV increment (defer)." },
];

let added = 0;
for (const rel of relations) {
  if (vm.relations.find((x) => x.vehicle_id === rel.vehicle_id && x.country_id === rel.country_id)) continue;
  vm.relations.push(rel);
  added++;
}
let skipped = 0;
for (const s of skips) {
  if (vm.skipped.find((x) => x.vehicle_id === s.vehicle_id && x.country_id === s.country_id)) continue;
  if (vm.relations.find((x) => x.vehicle_id === s.vehicle_id && x.country_id === s.country_id)) continue;
  vm.skipped.push(s);
  skipped++;
}
write("vehicle-market.json", vm);

console.log(`countries: ${countries.countries.length}, rules: ${importrules.rules.length}, taxes: ${taxrules.taxrules.length}, ports: ${ports.ports.length}, routes: ${routes.routes.length}, relations: ${vm.relations.length} (+${added}), skips: ${vm.skipped.length} (+${skipped})`);
