// Batch: market-countries7 — add 6 high-commercial-value countries + data layer + Vehicle×Market relations.
// Countries: Mongolia (North Asia land-border/rail), Kyrgyzstan (Central Asia EAEU re-export),
//            Serbia (Europe EU-adjacent), Senegal (West Africa), Côte d'Ivoire (West Africa),
//            Cameroon (Central Africa gateway).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";
const GBTSRC = "https://en.wikipedia.org/wiki/GB/T_charging_standard";
const MODELS = "https://data.chinausedautohub.com/models/";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "mongolia", name: "Mongolia", name_zh: "蒙古", region: "central-asia", drive_side: "lhd", currency: "MNT", status: "active", source: "Mongolian Customs General Administration / JP Sheet import guide", source_url: "https://jpsheet.com/import-guide/mongolia/", source_date: D, confidence: "high" },
  { country_id: "kyrgyzstan", name: "Kyrgyzstan", name_zh: "吉尔吉斯斯坦", region: "central-asia", drive_side: "lhd", currency: "KGS", status: "active", source: "State Customs Service of Kyrgyzstan / EAEU Common Customs Tariff / Washin Auto guide", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", source_date: D, confidence: "high" },
  { country_id: "serbia", name: "Serbia", name_zh: "塞尔维亚", region: "europe", drive_side: "lhd", currency: "RSD", status: "active", source: "Serbian Customs Administration / Qualitex Trading import regulations", source_url: "https://www.qualitextrading.com/import-regulations/serbia", source_date: D, confidence: "high" },
  { country_id: "senegal", name: "Senegal", name_zh: "塞内加尔", region: "africa", drive_side: "lhd", currency: "XOF", status: "active", source: "Direction Générale des Douanes (Senegal) / Washin Auto guide", source_url: "https://washinauto.com/import-guide?country=Senegal", source_date: D, confidence: "high" },
  { country_id: "cote-divoire", name: "Côte d'Ivoire", name_zh: "科特迪瓦", region: "africa", drive_side: "lhd", currency: "XOF", status: "active", source: "Direction Générale des Douanes (Côte d'Ivoire) / Qualitex Trading import regulations", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", source_date: D, confidence: "high" },
  { country_id: "cameroon", name: "Cameroon", name_zh: "喀麦隆", region: "africa", drive_side: "lhd", currency: "XAF", status: "active", source: "Direction Générale des Douanes (Cameroon) / Qualitex Trading import regulations", source_url: "https://www.qualitextrading.com/import-regulations/cameroon", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Mongolia (LHD, no fixed age limit, 5% + 10% VAT + excise, EV/hybrid/gas excise discount) =====
  { rule_id: "mn-drive-side", country_id: "mongolia", category: "drive_side", title: "Left-hand drive (LHD) market; RHD JDM permitted until 2030", rule_text: "Mongolia is a left-hand-drive market, but right-hand-drive Japanese domestic-market vehicles are currently permitted with a valid import licence. A complete ban on importing right-hand-drive vehicles is scheduled to take effect on 1 June 2030. China-market LHD units are directly registrable.", effective_date: "2030-06-01", last_checked: D, source: "JP Sheet (Mongolia import guide)", source_url: "https://jpsheet.com/import-guide/mongolia/", confidence: "medium", needs_review: true, notes: "RHD ban scheduled 1 June 2030 — confirm current status with Mongolian Customs." },
  { rule_id: "mn-age-limit", country_id: "mongolia", category: "vehicle_age", title: "No fixed age limit (tax rises with age)", rule_text: "Mongolia has no fixed vehicle-age cut-off for used imports, but excise and duty generally climb with vehicle age — so the newest unit the budget allows is usually the cheaper option once taxes are counted. Confirm the current age-based schedule with Mongolian Customs before committing.", effective_date: null, last_checked: D, source: "SUVHUB (Mongolia import rules)", source_url: "https://suvhub.com/import-rules/mongolia", confidence: "medium", needs_review: true, notes: "No hard cut-off; tax climbs with age — verify the current schedule with Mongolian Customs." },
  { rule_id: "mn-duty-stack", country_id: "mongolia", category: "other", title: "5% customs duty + 10% VAT + excise", rule_text: "Mongolia applies roughly a 5% customs duty plus 10% VAT, plus an excise tax that runs from MNT 750,000 to MNT 65,975,000 depending on engine size and age. An additional 33% excise applies to the portion of a vehicle's customs value exceeding MNT 360 million. Duty is assessed on the CIF value.", effective_date: null, last_checked: D, source: "JP Sheet (Mongolia import guide)", source_url: "https://jpsheet.com/import-guide/mongolia/", confidence: "medium", needs_review: true, notes: "Excise is engine-size and age based — verify with Mongolian Customs before purchase." },
  { rule_id: "mn-ev-policy", country_id: "mongolia", category: "ev_policy", title: "EV / hybrid / gas vehicles get up to 50% excise discount", rule_text: "Hybrid, electric and gas-fuelled vehicles receive up to a 50% discount on excise tax in Mongolia, a meaningful relief delta versus combustion vehicles. This makes recent Chinese EVs and hybrids particularly attractive on the tax side.", effective_date: null, last_checked: D, source: "JP Sheet (Mongolia import guide)", source_url: "https://jpsheet.com/import-guide/mongolia/", confidence: "medium", needs_review: true, notes: "Up to 50% excise discount for EV/hybrid/gas — confirm current scope with Mongolian Customs." },
  { rule_id: "mn-entry", country_id: "mongolia", category: "import_eligibility", title: "Landlocked — transit via Tianjin then rail", rule_text: "Mongolia is landlocked. Vehicles transit by sea to Tianjin (China), then continue by rail to Ulaanbaatar via the Erlian/Zamyn-Üüd border crossing. Customs clearance is completed at the Ulaanbaatar rail terminal.", effective_date: null, last_checked: D, source: "JP Sheet / SUVHUB (Mongolia import guides)", source_url: "https://jpsheet.com/import-guide/mongolia/", confidence: "medium", needs_review: true, notes: "Transit routing is operational guidance — confirm with a forwarder." },

  // ===== Kyrgyzstan (LHD, EAEU, 10-year age limit) =====
  { rule_id: "kg-drive-side", country_id: "kyrgyzstan", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Kyrgyzstan drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "kg-age-limit", country_id: "kyrgyzstan", category: "vehicle_age", title: "10-year age limit", rule_text: "Used vehicles older than 10 years are not allowed to be imported into Kyrgyzstan. In 2026 this means roughly model-year 2016 and newer. Confirm the current threshold with the State Customs Service before sourcing older stock.", effective_date: null, last_checked: D, source: "Washin Auto (Kyrgyzstan import guide)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with the State Customs Service." },
  { rule_id: "kg-eaeu", country_id: "kyrgyzstan", category: "import_eligibility", title: "EAEU member — Common Customs Tariff applies", rule_text: "Kyrgyzstan is an EAEU member and applies the bloc's Common Customs Tariff to non-EAEU vehicles. Permanent importation is subject to customs duty and VAT; temporary (employment-status) import has a distinct lower-charge treatment. No pre-shipment inspection is required.", effective_date: null, last_checked: D, source: "Washin Auto (Kyrgyzstan import guide)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", confidence: "medium", needs_review: true, notes: "EAEU framework; no inspection required — verify duty rates with the State Customs Service." },
  { rule_id: "kg-ev-policy", country_id: "kyrgyzstan", category: "ev_policy", title: "EV import-duty treatment needs verification", rule_text: "No EV-specific import-duty exemption was confirmed for Kyrgyzstan in the sources reviewed. Kyrgyzstan is an EAEU member, so EV treatment may follow the EAEU framework; confirm current EV duty with the State Customs Service before trading.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with the State Customs Service." },

  // ===== Serbia (LHD, Euro 3, 12.5% + 20% VAT, no age limit) =====
  { rule_id: "rs-drive-side", country_id: "serbia", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Serbia drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive imports are generally not registrable.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "rs-emission", country_id: "serbia", category: "emission", title: "Euro 3 emission standard minimum", rule_text: "All imported vehicles must meet the Euro 3 emission standard or higher. Petrol, diesel, hybrid and electric (EV) fuel types are all accepted by Serbian Customs.", effective_date: null, last_checked: D, source: "Qualitex Trading (Serbia import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", confidence: "medium", needs_review: true, notes: "Euro 3 minimum — confirm current emission threshold with Serbian Customs." },
  { rule_id: "rs-age-limit", country_id: "serbia", category: "vehicle_age", title: "No fixed age limit", rule_text: "Serbia has no fixed vehicle-age cut-off for used imports; the binding gate is the Euro 3 emission standard and technical condition. Damaged vehicles may be imported if repairable with minimal work.", effective_date: null, last_checked: D, source: "Qualitex Trading (Serbia import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", confidence: "medium", needs_review: true, notes: "No age limit — eligibility is standards-based. Verify with Serbian Customs." },
  { rule_id: "rs-duty-stack", country_id: "serbia", category: "other", title: "12.5% duty + 20% VAT (AMSS catalog basis)", rule_text: "Serbia charges 12.5% customs duty on non-EU origin vehicles (0% only for EU origin with EUR1/origin declaration) plus 20% VAT on the customs value plus duty. Customs uses the AMSS catalog value to calculate taxes regardless of the actual purchase price.", effective_date: null, last_checked: D, source: "Qualitex Trading (Serbia import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", confidence: "medium", needs_review: true, notes: "AMSS catalog value is the tax base — verify current rates with Serbian Customs." },
  { rule_id: "rs-ev-policy", country_id: "serbia", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was identified for Serbia in the sources reviewed; EVs are accepted but face the same 12.5% duty plus 20% VAT as other vehicles. Serbia imports around 130,000 used cars annually, with growing hybrid interest.", effective_date: null, last_checked: D, source: "Qualitex Trading (Serbia import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", confidence: "medium", needs_review: true, notes: "No EV-specific relief — verify current EV treatment with Serbian Customs." },

  // ===== Senegal (LHD, strict 3-year private age rule, pre-shipment inspection) =====
  { rule_id: "sn-drive-side", country_id: "senegal", category: "drive_side", title: "Left-hand drive (LHD) market", rule_text: "Senegal drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive vehicles are generally not suitable for permanent registration.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "sn-age-limit", country_id: "senegal", category: "vehicle_age", title: "3-year age rule (private); 6-year (commercial)", rule_text: "Imported used vehicles for private use must not be more than 3 years old from original registration and not more than 4 years from the year of manufacture. Commercial vehicles must not be more than 60 months from original registration and not more than 6 years from manufacture. In 2026 this makes roughly model-year 2023 and newer eligible for private use.", effective_date: null, last_checked: D, source: "Washin Auto (Senegal import guide)", source_url: "https://washinauto.com/import-guide?country=Senegal", confidence: "medium", needs_review: true, notes: "Strict age rule (3yr private / 6yr commercial) — verify with Senegal Customs before purchase." },
  { rule_id: "sn-inspection", country_id: "senegal", category: "import_eligibility", title: "Pre-shipment inspection in country of origin", rule_text: "All used vehicles imported into Senegal must undergo pre-delivery inspection in the country of origin before shipment. Required documents include bill of lading, certificate of origin, import licence/approval permit (obtained before departure), original title and purchase invoice.", effective_date: null, last_checked: D, source: "Washin Auto (Senegal import guide)", source_url: "https://washinauto.com/import-guide?country=Senegal", confidence: "medium", needs_review: true, notes: "Pre-shipment inspection and prior import approval are mandatory — verify with Senegal Customs." },
  { rule_id: "sn-ev-policy", country_id: "senegal", category: "ev_policy", title: "EV import-duty treatment needs verification", rule_text: "No EV-specific import-duty exemption was confirmed for Senegal in the sources reviewed. EV policy is developing; confirm current EV duty with Senegal Customs before trading.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with Senegal Customs." },

  // ===== Côte d'Ivoire (LHD, 5-year age limit, ~53% duty) =====
  { rule_id: "ci-drive-side", country_id: "cote-divoire", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Côte d'Ivoire drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "ci-age-limit", country_id: "cote-divoire", category: "vehicle_age", title: "5-year age limit (cars)", rule_text: "Côte d'Ivoire restricts imported cars (tourism vehicles) to a maximum of 5 years of age. Taxis are also 5 years, minibuses (9–34 seats) 7 years, buses (34+ seats) 10 years, and trucks up to 10 years depending on weight. In 2026 this means roughly model-year 2021 and newer for passenger cars.", effective_date: null, last_checked: D, source: "Qualitex Trading (Côte d'Ivoire import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", confidence: "medium", needs_review: true, notes: "5-year car limit — verify current threshold with Côte d'Ivoire Customs before purchase." },
  { rule_id: "ci-duty", country_id: "cote-divoire", category: "other", title: "~53% customs duty + registration fee", rule_text: "Côte d'Ivoire charges approximately 53% customs duty on the vehicle CIF value, plus a vehicle registration fee of about EUR 690 per vehicle. Vehicles cannot be shipped in the same container as household goods or personal effects.", effective_date: null, last_checked: D, source: "Qualitex Trading (Côte d'Ivoire import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", confidence: "medium", needs_review: true, notes: "~53% duty is an approximation — verify with Côte d'Ivoire Customs." },
  { rule_id: "ci-ev-policy", country_id: "cote-divoire", category: "ev_policy", title: "EV import-duty treatment needs verification", rule_text: "No EV-specific import-duty exemption was confirmed for Côte d'Ivoire in the sources reviewed; EVs are expected to follow the standard ~53% schedule. Confirm current EV treatment with Côte d'Ivoire Customs.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with Côte d'Ivoire Customs." },

  // ===== Cameroon (LHD, no age limit, 58%/77% duty) =====
  { rule_id: "cm-drive-side", country_id: "cameroon", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Cameroon drives on the right and registers left-hand-drive (LHD) vehicles; left-hand-drive imports are common and no fixed age limit applies.", effective_date: null, last_checked: D, source: "Japan Carrier (Cameroon import regulations)", source_url: "https://www.japan-carrier.com/regulations/cameroon?lang=en", confidence: "high", needs_review: false },
  { rule_id: "cm-age-limit", country_id: "cameroon", category: "vehicle_age", title: "No fixed age limit", rule_text: "Cameroon has no fixed vehicle-age limit for used imports; new and used vehicles are both accepted. Taxes may vary depending on the vehicle's age, engine power and other factors.", effective_date: null, last_checked: D, source: "Japan Carrier / Qualitex Trading (Cameroon import regulations)", source_url: "https://www.japan-carrier.com/regulations/cameroon?lang=en", confidence: "medium", needs_review: true, notes: "No fixed age limit — but taxes vary by age/engine. Verify with Cameroon Customs." },
  { rule_id: "cm-duty", country_id: "cameroon", category: "other", title: "58% (≤2000cc) / 77% (>2000cc) duty", rule_text: "Cameroon charges import duty of 58% of CIF for vehicles with engine capacity below 2000cc and 77% of CIF for engines above 2000cc, plus a non-sale certificate is required. Documents must be submitted at least one month before shipment arrival.", effective_date: null, last_checked: D, source: "Qualitex Trading (Cameroon import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/cameroon", confidence: "medium", needs_review: true, notes: "Engine-capacity-based duty (58% / 77%) — verify with Cameroon Customs." },
  { rule_id: "cm-ev-policy", country_id: "cameroon", category: "ev_policy", title: "EV import-duty treatment needs verification", rule_text: "No EV-specific import-duty exemption was confirmed for Cameroon in the sources reviewed. Cameroon's duty is engine-capacity based, so EV classification is unclear; confirm with Cameroon Customs before trading.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with Cameroon Customs." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  // Mongolia
  { taxrule_id: "mn-duty", country_id: "mongolia", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: 5, basis: "CIF value", effective_date: null, last_checked: D, source: "JP Sheet (Mongolia import guide)", source_url: "https://jpsheet.com/import-guide/mongolia/", confidence: "medium", needs_review: true, notes: "~5% customs duty. Verify with Mongolian Customs." },
  { taxrule_id: "mn-vat", country_id: "mongolia", tax_type: "vat", label: "VAT", rate_pct: 10, basis: "CIF + duty", effective_date: null, last_checked: D, source: "JP Sheet (Mongolia import guide)", source_url: "https://jpsheet.com/import-guide/mongolia/", confidence: "medium", needs_review: false },
  // Kyrgyzstan
  { taxrule_id: "kg-duty", country_id: "kyrgyzstan", tax_type: "import_duty", label: "Import duty (EAEU Common Customs Tariff)", rate_pct: 15, basis: "CIF value", effective_date: null, last_checked: D, source: "EAEU Common Customs Tariff (Kyrgyzstan member)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", confidence: "low", needs_review: true, notes: "~15% EAEU CCT (estimate). Verify with the State Customs Service of Kyrgyzstan." },
  { taxrule_id: "kg-vat", country_id: "kyrgyzstan", tax_type: "vat", label: "VAT", rate_pct: 12, basis: "CIF + duty", effective_date: null, last_checked: D, source: "State Tax Service of Kyrgyzstan (VAT)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", confidence: "low", needs_review: true, notes: "12% VAT (estimate). Verify with the State Customs Service." },
  // Serbia
  { taxrule_id: "rs-duty", country_id: "serbia", tax_type: "import_duty", label: "Import duty (non-EU origin)", rate_pct: 12.5, basis: "CIF value (AMSS catalog)", effective_date: null, last_checked: D, source: "Qualitex Trading (Serbia import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", confidence: "medium", needs_review: true, notes: "12.5% for non-EU origin; 0% only for EU origin with EUR1. Verify with Serbian Customs." },
  { taxrule_id: "rs-vat", country_id: "serbia", tax_type: "vat", label: "VAT", rate_pct: 20, basis: "CIF + duty (AMSS catalog)", effective_date: null, last_checked: D, source: "Qualitex Trading (Serbia import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", confidence: "medium", needs_review: false },
  // Senegal
  { taxrule_id: "sn-duty", country_id: "senegal", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: 20, basis: "CIF value", effective_date: null, last_checked: D, source: "Senegal Customs (commonly cited)", source_url: "https://washinauto.com/import-guide?country=Senegal", confidence: "low", needs_review: true, notes: "~20% commonly cited (estimate); rate varies by age/engine. Verify with Senegal Customs." },
  { taxrule_id: "sn-vat", country_id: "senegal", tax_type: "vat", label: "VAT", rate_pct: 18, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Senegal Customs (VAT)", source_url: "https://washinauto.com/import-guide?country=Senegal", confidence: "low", needs_review: true, notes: "18% VAT (estimate). Verify with Senegal Customs." },
  // Côte d'Ivoire
  { taxrule_id: "ci-duty", country_id: "cote-divoire", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: 53, basis: "CIF value", effective_date: null, last_checked: D, source: "Qualitex Trading (Côte d'Ivoire import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", confidence: "medium", needs_review: true, notes: "~53% customs duty (approximation). Verify with Côte d'Ivoire Customs." },
  // Cameroon
  { taxrule_id: "cm-duty-le2000", country_id: "cameroon", tax_type: "import_duty", label: "Import duty (engine ≤2000cc)", rate_pct: 58, basis: "CIF value", effective_date: null, last_checked: D, source: "Qualitex Trading (Cameroon import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/cameroon", confidence: "medium", needs_review: true, notes: "58% of CIF for engines ≤2000cc. Verify with Cameroon Customs." },
  { taxrule_id: "cm-duty-gt2000", country_id: "cameroon", tax_type: "import_duty", label: "Import duty (engine >2000cc)", rate_pct: 77, basis: "CIF value", effective_date: null, last_checked: D, source: "Qualitex Trading (Cameroon import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/cameroon", confidence: "medium", needs_review: true, notes: "77% of CIF for engines >2000cc. Verify with Cameroon Customs." },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "mn-ulaanbaatar", name: "Ulaanbaatar (via Tianjin + rail transit)", country_id: "mongolia", type: "destination", note: "Landlocked — transit via Tianjin then rail through Erlian/Zamyn-Üüd" },
  { port_id: "kg-bishkek", name: "Bishkek (via rail transit)", country_id: "kyrgyzstan", type: "destination", note: "Landlocked — transit via rail from China/Kazakhstan" },
  { port_id: "rs-belgrade", name: "Belgrade (via Bar / Thessaloniki transit)", country_id: "serbia", type: "destination", note: "Landlocked — transit via Bar (Montenegro) or Thessaloniki (Greece)" },
  { port_id: "sn-dakar", name: "Dakar", country_id: "senegal", type: "destination", note: null },
  { port_id: "ci-abidjan", name: "Abidjan", country_id: "cote-divoire", type: "destination", note: null },
  { port_id: "cm-douala", name: "Douala", country_id: "cameroon", type: "destination", note: null },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-tianjin-to-mn-ulaanbaatar", origin_port_id: "cn-tianjin", destination_port_id: "mn-ulaanbaatar", est_days_min: 8, est_days_max: 14, shipping_method: "container", source: "Industry route estimates (rail transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-tianjin-to-kg-bishkek", origin_port_id: "cn-tianjin", destination_port_id: "kg-bishkek", est_days_min: 15, est_days_max: 24, shipping_method: "container", source: "Industry route estimates (rail transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-rs-belgrade", origin_port_id: "cn-shanghai", destination_port_id: "rs-belgrade", est_days_min: 30, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates (via Bar/Thessaloniki)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-sn-dakar", origin_port_id: "cn-guangzhou", destination_port_id: "sn-dakar", est_days_min: 30, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-ci-abidjan", origin_port_id: "cn-shanghai", destination_port_id: "ci-abidjan", est_days_min: 30, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-cm-douala", origin_port_id: "cn-guangzhou", destination_port_id: "cm-douala", est_days_min: 28, est_days_max: 38, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

// ---------- vehicle-market.json relations ----------
const vm = read("vehicle-market.json");
vm.meta.batch = "batch 18 — market-countries7";
vm.meta.updated = D;

const dsMatch = (summary) => ({ status: "match", summary, source: "Data sub-site models.json (export intelligence) + Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, source_type: "database", confidence: "high", checked_date: D });
const charging = (dest, notes) => ({ standard: "GB/T", destination_standard: dest, connector: "GB/T AC / GB/T DC (vehicle inlet)", voltage: null, frequency: null, needs_adapter: true, notes: notes ?? `China-market GB/T inlet vs ${dest} network — adapter required; confirm the sourced unit's inlet (some export units carry a CCS2 inlet).`, source: "Vehicle: GB/T charging standard (Wikipedia); Destination: Combined Charging System / Type 2 (Wikipedia)", source_url: GBTSRC, source_type: "reputable_media", confidence: "medium", checked_date: D, needs_review: true });

const relations = [
  // ===== Mongolia (LHD, no age limit, EV/hybrid/gas up to 50% excise discount) =====
  {
    vehicle_id: "byd-atto-3", country_id: "mongolia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Mongolia registers LHD (RHD JDM permitted only until 1 June 2030) — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Mongolia has no fixed age limit (tax rises with age), so current-generation Atto 3 units (2022+) are eligible. The tax climbs with age, so source the newest unit available.", source: "market sub-site importrules.json (no fixed age limit)", source_url: "https://suvhub.com/import-rules/mongolia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Mongolia grants up to a 50% excise discount to electric vehicles versus combustion vehicles, a strong tax-side incentive for Chinese EV imports.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: { standard: "GB/T", destination_standard: "GB/T / CCS2 (mixed, China-influenced)", connector: "GB/T AC / GB/T DC (vehicle inlet)", voltage: null, frequency: null, needs_adapter: false, notes: "Mongolia's charging network is heavily China-influenced with GB/T connectors common; confirm the specific charger standard for the intended route. China-market GB/T units are broadly compatible but verify DC fast-charging availability.", source: "Vehicle: GB/T charging standard (Wikipedia)", source_url: GBTSRC, source_type: "reputable_media", confidence: "low", checked_date: D, needs_review: true },
    import_eligibility: { status: "conformity_required", requirements: ["Rail transit via Tianjin + Erlian/Zamyn-Üüd", "No fixed age limit"], notes: "Mongolia is landlocked; vehicles transit Tianjin then rail to Ulaanbaatar. The RHD ban (1 June 2030) does not affect LHD China units.", source: "market sub-site importrules.json (landlocked + age)", source_url: "https://jpsheet.com/import-guide/mongolia/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "mn-duty", ev_duty_taxrule_id: "mn-duty", vat_taxrule_id: "mn-vat", ev_duty_relief: true, notes: "EV: up to 50% excise discount (not a lower duty rate — the 5% duty and 10% VAT still apply). Referenced from taxrules.json — verify with Mongolian Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://jpsheet.com/import-guide/mongolia/", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-tianjin-to-mn-ulaanbaatar"], notes: "Sea to Tianjin, then rail to Ulaanbaatar via Erlian/Zamyn-Üüd (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Mongolia's EV excise discount and GB/T-compatible charging network are the key fit points for recent low-mileage Chinese EV stock.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "byd-seal", country_id: "mongolia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Mongolia registers LHD (RHD JDM permitted only until 1 June 2030) — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Mongolia has no fixed age limit; Seal units (2022+) are eligible and the age-based tax rise favors recent stock.", source: "market sub-site importrules.json (no fixed age limit)", source_url: "https://suvhub.com/import-rules/mongolia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — qualifies for Mongolia's up-to-50% EV excise discount versus combustion vehicles.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: { standard: "GB/T", destination_standard: "GB/T / CCS2 (mixed, China-influenced)", connector: "GB/T AC / GB/T DC (vehicle inlet)", voltage: null, frequency: null, needs_adapter: false, notes: "Mongolia's China-influenced network broadly accepts GB/T; confirm DC fast-charging availability for the intended route.", source: "Vehicle: GB/T charging standard (Wikipedia)", source_url: GBTSRC, source_type: "reputable_media", confidence: "low", checked_date: D, needs_review: true },
    import_eligibility: { status: "conformity_required", requirements: ["Rail transit via Tianjin + Erlian/Zamyn-Üüd"], notes: "Landlocked transit via Tianjin then rail to Ulaanbaatar; the RHD ban does not affect LHD units.", source: "market sub-site importrules.json (landlocked)", source_url: "https://jpsheet.com/import-guide/mongolia/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "mn-duty", ev_duty_taxrule_id: "mn-duty", vat_taxrule_id: "mn-vat", ev_duty_relief: true, notes: "EV: up to 50% excise discount. Referenced from taxrules.json — verify with Mongolian Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://jpsheet.com/import-guide/mongolia/", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-tianjin-to-mn-ulaanbaatar"], notes: "Sea to Tianjin, then rail to Ulaanbaatar (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Seal is a mid-size EV sedan; Mongolia's EV excise discount and GB/T charging make it a strong recent-EV import.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/seal", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "byd-sealion-6", country_id: "mongolia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Mongolia registers LHD — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Sealion 6 (2025) is a current-generation model; Mongolia's no-fixed-age-limit regime makes it clearly eligible.", source: "market sub-site importrules.json (no fixed age limit)", source_url: "https://suvhub.com/import-rules/mongolia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Plug-in hybrid (PHEV / DM-i) — Mongolia's up-to-50% excise discount applies to hybrids as well as EVs, a tax-side incentive versus pure combustion.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: { standard: "GB/T", destination_standard: "GB/T / CCS2 (mixed, China-influenced)", connector: "GB/T AC / GB/T DC (vehicle inlet)", voltage: null, frequency: null, needs_adapter: false, notes: "PHEV charges on AC GB/T; Mongolia's China-influenced network broadly accepts GB/T. Confirm AC charging point availability.", source: "Vehicle: GB/T charging standard (Wikipedia)", source_url: GBTSRC, source_type: "reputable_media", confidence: "low", checked_date: D, needs_review: true },
    import_eligibility: { status: "conformity_required", requirements: ["Rail transit via Tianjin + Erlian/Zamyn-Üüd"], notes: "Landlocked transit via Tianjin then rail; LHD China units registrable.", source: "market sub-site importrules.json (landlocked)", source_url: "https://jpsheet.com/import-guide/mongolia/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "mn-duty", ev_duty_taxrule_id: "mn-duty", vat_taxrule_id: "mn-vat", ev_duty_relief: true, notes: "PHEV/hybrid: up to 50% excise discount. Referenced from taxrules.json — verify with Mongolian Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://jpsheet.com/import-guide/mongolia/", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-tianjin-to-mn-ulaanbaatar"], notes: "Sea to Tianjin, then rail to Ulaanbaatar (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Sealion 6 is a PHEV SUV; Mongolia's hybrid excise discount and GB/T charging are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/sealion-6", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },

  // ===== Kyrgyzstan (LHD, EAEU, 10-year age limit) =====
  {
    vehicle_id: "chery-tiggo-7", country_id: "kyrgyzstan",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Kyrgyzstan registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 7 production began 2016; Kyrgyzstan's 10-year age limit makes 2016 units ~10 years old (borderline-to-ineligible) in 2026. Source 2017+ units and verify the exact cut-off with the State Customs Service.", source: "market sub-site importrules.json (10-year age limit)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to EAEU Common Customs Tariff (~15%) plus VAT. No EV relief applies to the ICE trim.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["≤10 years old", "EAEU customs clearance"], notes: "The 10-year age rule renders 2016 units borderline — the age rule is the primary blocker for this model. No pre-shipment inspection is required.", source: "market sub-site importrules.json (age + EAEU)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "kg-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "kg-vat", ev_duty_relief: false, notes: "ICE: ~15% EAEU duty + 12% VAT (estimates). Referenced from taxrules.json — verify with the State Customs Service.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-tianjin-to-kg-bishkek"], notes: "Rail transit via China/Kazakhstan to Bishkek (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 7 is an ICE SUV; Kyrgyzstan's 10-year age limit renders 2016 units borderline — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_7", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "haval-h9", country_id: "kyrgyzstan",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Kyrgyzstan registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Haval H9 production began 2015; Kyrgyzstan's 10-year age limit makes 2015 units ~11 years old (ineligible) in 2026. Source 2017+ units and verify the cut-off.", source: "market sub-site importrules.json (10-year age limit)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE, ≥2000cc) — subject to EAEU duty plus VAT; the large engine raises the cost base. No EV relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["≤10 years old", "EAEU customs clearance"], notes: "The 10-year age rule renders 2015 units ineligible — the age rule is the primary blocker.", source: "market sub-site importrules.json (age + EAEU)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "kg-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "kg-vat", ev_duty_relief: false, notes: "ICE: ~15% EAEU duty + 12% VAT (estimates). Referenced from taxrules.json — verify with the State Customs Service.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://washinauto.com/import-guide?country=Kyrgyzstan", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-tianjin-to-kg-bishkek"], notes: "Rail transit via China/Kazakhstan to Bishkek (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Haval H9 is a large ICE SUV; Kyrgyzstan's 10-year age limit renders 2015 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Haval_H9", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Serbia (LHD, Euro 3, no age limit, 12.5% + 20% VAT) =====
  {
    vehicle_id: "byd-atto-3", country_id: "serbia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Serbia registers LHD only — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Serbia has no fixed age limit (Euro 3 emission is the binding gate); current-generation Atto 3 units are eligible.", source: "market sub-site importrules.json (no age limit)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Serbia accepts EVs but records no EV-specific import-duty relief (12.5% duty + 20% VAT, AMSS catalog basis). The EV classification avoids Euro 3 combustion concerns.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)", "China-market GB/T inlet vs Serbia's European CCS2/Type 2 network — adapter required."),
    import_eligibility: { status: "conformity_required", requirements: ["Euro 3 emission standard", "AMSS catalog value assessment"], notes: "Serbia's Euro 3 minimum and AMSS-catalog tax base are the key process points; EVs avoid the Euro 3 combustion threshold. Verify with Serbian Customs.", source: "market sub-site importrules.json (emission + duty)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "rs-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "rs-vat", ev_duty_relief: false, notes: "EV: 12.5% duty + 20% VAT (no EV relief); taxes use AMSS catalog value. Referenced from taxrules.json — verify with Serbian Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-rs-belgrade"], notes: "Sea to Bar (Montenegro) or Thessaloniki (Greece), then rail/road to Belgrade (RoRo/container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Serbia's no-age-limit regime, Euro 3 acceptance and CCS2/Type 2 charging (adapter needed) are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "mg-4", country_id: "serbia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Serbia registers LHD only — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Serbia has no fixed age limit; MG4 EV (2022+) is eligible with Euro 3 compliance.", source: "market sub-site importrules.json (no age limit)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — no EV-specific duty relief in Serbia (12.5% + 20% VAT), but EVs avoid Euro 3 combustion concerns.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)", "China-market GB/T inlet vs Serbia's European CCS2/Type 2 network — adapter required."),
    import_eligibility: { status: "conformity_required", requirements: ["Euro 3 emission standard", "AMSS catalog value assessment"], notes: "Serbia's Euro 3 minimum and AMSS-catalog tax base apply; EVs avoid the Euro 3 combustion threshold. Verify with Serbian Customs.", source: "market sub-site importrules.json (emission + duty)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "rs-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "rs-vat", ev_duty_relief: false, notes: "EV: 12.5% duty + 20% VAT (no EV relief). Referenced from taxrules.json — verify with Serbian Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.qualitextrading.com/import-regulations/serbia", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-rs-belgrade"], notes: "Sea to Bar (Montenegro) or Thessaloniki (Greece), then rail/road to Belgrade.", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "MG4 EV is a compact hatchback; Serbia's no-age-limit regime and CCS2/Type 2 charging (adapter needed) are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/MG4_EV", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Senegal (LHD, 3-year private age rule, pre-shipment inspection) =====
  {
    vehicle_id: "geely-monjaro", country_id: "senegal",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Senegal registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Monjaro production began 2021; Senegal's 3-year (private) / 4-year (manufacture) age rule makes 2021 units ~5 years old (ineligible) in 2026. Only 2023+ units qualify for private import.", source: "market sub-site importrules.json (3-year age rule)", source_url: "https://washinauto.com/import-guide?country=Senegal", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to Senegal's duty plus VAT; the strict age rule (not duty) is the primary blocker for this model.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["≤3 years old (private)", "Pre-shipment inspection in country of origin", "Prior import approval permit"], notes: "Senegal's strict 3-year private age rule and pre-shipment inspection are the hard filters; the age rule renders 2021 units ineligible.", source: "market sub-site importrules.json (age + inspection)", source_url: "https://washinauto.com/import-guide?country=Senegal", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "sn-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "sn-vat", ev_duty_relief: false, notes: "ICE: ~20% duty + 18% VAT (estimates). Referenced from taxrules.json — verify with Senegal Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://washinauto.com/import-guide?country=Senegal", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-guangzhou-to-sn-dakar"], notes: "Sea freight to Dakar (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; Senegal's strict 3-year private age rule renders 2021 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "chery-tiggo-8", country_id: "senegal",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Senegal registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 8 production began 2018; Senegal's 3-year (private) / 4-year (manufacture) age rule makes 2018 units ~8 years old (ineligible). Only 2023+ units qualify.", source: "market sub-site importrules.json (3-year age rule)", source_url: "https://washinauto.com/import-guide?country=Senegal", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to Senegal's duty plus VAT; the strict age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["≤3 years old (private)", "Pre-shipment inspection in country of origin"], notes: "Senegal's strict age rule and pre-shipment inspection render 2018 units ineligible — the age rule is the primary blocker.", source: "market sub-site importrules.json (age + inspection)", source_url: "https://washinauto.com/import-guide?country=Senegal", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "sn-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "sn-vat", ev_duty_relief: false, notes: "ICE: ~20% duty + 18% VAT (estimates). Referenced from taxrules.json — verify with Senegal Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://washinauto.com/import-guide?country=Senegal", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-guangzhou-to-sn-dakar"], notes: "Sea freight to Dakar (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 8 is an ICE SUV; Senegal's strict age rule renders 2018 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_8", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Côte d'Ivoire (LHD, 5-year age limit, ~53% duty) =====
  {
    vehicle_id: "chery-tiggo-8", country_id: "cote-divoire",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Côte d'Ivoire registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 8 production began 2018; Côte d'Ivoire's 5-year car age limit makes 2018 units ~8 years old (ineligible). Source 2021+ units and verify the cut-off.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to ~53% duty plus registration fee; the 5-year age rule is the primary blocker for this model.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["≤5 years old (cars)", "No household-goods co-shipment"], notes: "The 5-year age rule renders 2018 units ineligible — the age rule is the primary blocker. ~53% duty plus EUR 690 registration fee applies.", source: "market sub-site importrules.json (age + duty)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "ci-duty", ev_duty_taxrule_id: null, vat_taxrule_id: null, ev_duty_relief: false, notes: "ICE: ~53% duty (no separate VAT recorded) + EUR 690 registration fee. Referenced from taxrules.json — verify with Côte d'Ivoire Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-ci-abidjan"], notes: "Sea freight to Abidjan (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 8 is an ICE SUV; Côte d'Ivoire's 5-year age rule renders 2018 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_8", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "geely-monjaro", country_id: "cote-divoire",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Côte d'Ivoire registers LHD only — no conversion required."),
    age_rule_fit: { status: "borderline", summary: "Monjaro production began 2021; Côte d'Ivoire's 5-year age limit makes 2021 units ~5 years old (borderline) in 2026. Source 2022+ units and verify the exact cut-off.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to ~53% duty plus registration fee; the 5-year age rule makes 2021 units borderline.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["≤5 years old (cars)", "No household-goods co-shipment"], notes: "The 5-year age rule makes 2021 units borderline — source 2022+ units. ~53% duty plus EUR 690 registration fee applies.", source: "market sub-site importrules.json (age + duty)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "ci-duty", ev_duty_taxrule_id: null, vat_taxrule_id: null, ev_duty_relief: false, notes: "ICE: ~53% duty + EUR 690 registration fee. Referenced from taxrules.json — verify with Côte d'Ivoire Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.qualitextrading.com/import-regulations/ivory-coast", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-ci-abidjan"], notes: "Sea freight to Abidjan (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; Côte d'Ivoire's 5-year age rule makes 2021 units borderline — source 2022+ units.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Cameroon (LHD, no age limit, 58%/77% duty) =====
  {
    vehicle_id: "byd-atto-3", country_id: "cameroon",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Cameroon registers LHD only — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Cameroon has no fixed age limit, so current-generation Atto 3 units (2022+) are eligible.", source: "market sub-site importrules.json (no age limit)", source_url: "https://www.japan-carrier.com/regulations/cameroon?lang=en", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Cameroon's engine-capacity-based duty (58% ≤2000cc / 77% >2000cc) does not cleanly map to EVs, so EV classification and rate are uncertain; confirm with Cameroon Customs.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)", "China-market GB/T inlet vs Cameroon's CCS2/Type 2 network — adapter required; EV charging network is early-stage."),
    import_eligibility: { status: "conformity_required", requirements: ["No age limit", "Non-sale certificate", "Documents 1 month before arrival"], notes: "Cameroon has no age limit but the engine-capacity duty basis makes EV classification uncertain; a non-sale certificate is required. Verify with Cameroon Customs.", source: "market sub-site importrules.json (age + duty)", source_url: "https://www.qualitextrading.com/import-regulations/cameroon", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "cm-duty-le2000", ev_duty_taxrule_id: null, vat_taxrule_id: null, ev_duty_relief: false, notes: "Duty is engine-capacity based (58% ≤2000cc / 77% >2000cc); EV rate uncertain. Referenced from taxrules.json — verify with Cameroon Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.qualitextrading.com/import-regulations/cameroon", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-guangzhou-to-cm-douala"], notes: "Sea freight to Douala (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Cameroon's no-age-limit regime and engine-capacity duty (EV rate uncertain) plus early-stage charging are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "low", checked_date: D,
  },
];

const skips = [
  { vehicle_id: "byd-dolphin", country_id: "mongolia", reason: "EV × LHD — Mongolia's EV excise-discount delta already represented by byd-atto-3 / byd-seal / byd-sealion-6 × mongolia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "mg-4", country_id: "mongolia", reason: "EV × LHD — Mongolia EV excise-discount delta already represented (mechanical EV cross-product, avoid)." },
  { vehicle_id: "geely-monjaro", country_id: "mongolia", reason: "ICE × LHD — no age conflict (Mongolia has no fixed age limit); 5%+10%+excise is a market-level fact (fails the generation gate)." },
  { vehicle_id: "chery-tiggo-8", country_id: "mongolia", reason: "ICE × LHD — no age conflict (no fixed age limit); duty stack is market-level (fails the generation gate)." },
  { vehicle_id: "byd-atto-3", country_id: "kyrgyzstan", reason: "EV × LHD — no confirmed EV duty relief in Kyrgyzstan (EAEU member); 10-year age limit satisfied by 2022 start. No independent increment." },
  { vehicle_id: "geely-monjaro", country_id: "kyrgyzstan", reason: "ICE × LHD — 2021 start is under the 10-year limit (no age conflict); EAEU duty/VAT is market-level (fails the generation gate)." },
  { vehicle_id: "chery-tiggo-8", country_id: "kyrgyzstan", reason: "ICE × LHD — 2018 start is ~8 years old (under the 10-year limit, no age conflict); EAEU duty is market-level (fails the generation gate)." },
  { vehicle_id: "byd-seal", country_id: "serbia", reason: "EV × LHD — charging-compat + no-EV-relief delta already represented by byd-atto-3 and mg-4 × serbia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "geely-monjaro", country_id: "serbia", reason: "ICE × LHD — no age conflict (Serbia has no age limit); 12.5%+20% VAT is market-level (fails the generation gate)." },
  { vehicle_id: "byd-atto-3", country_id: "senegal", reason: "EV × LHD — 2022 start is ~4 years from manufacture, borderline under the 3yr private rule, but the age-rule delta is already represented by geely-monjaro and chery-tiggo-8 × senegal (mechanical cross-product, avoid)." },
  { vehicle_id: "byd-dolphin", country_id: "cote-divoire", reason: "EV × LHD — 2021 start is borderline under the 5-year rule, but no EV relief and the age delta is already represented by ICE exemplars (avoid mechanical cross-product)." },
  { vehicle_id: "chery-tiggo-8", country_id: "cameroon", reason: "ICE × LHD — no age conflict (Cameroon has no age limit) and engine-capacity duty (58%/77%) is a market-level fact, not a vehicle×market increment (fails the generation gate)." },
  { vehicle_id: "geely-monjaro", country_id: "cameroon", reason: "ICE × LHD — engine-capacity duty (58%/77%) is a market-level fact; no age conflict and no EV relief (fails the generation gate)." },
  { vehicle_id: "byd-seal", country_id: "cameroon", reason: "EV × LHD — EV-rate-uncertain delta already represented by byd-atto-3 × cameroon (mechanical EV cross-product, avoid)." },
];

let added = 0;
for (const rel of relations) {
  if (vm.relations.find((x) => x.vehicle_id === rel.vehicle_id && x.country_id === rel.country_id)) continue;
  vm.relations.push(rel);
  added++;
}
let skipped = 0;
for (const s of skips) {
  if (vm.skipped.find((x) => x.vehicle_id === s.vehicle_id && x.country_id === s.country_id)) continue;
  if (vm.relations.find((x) => x.vehicle_id === s.vehicle_id && x.country_id === s.country_id)) continue;
  vm.skipped.push(s);
  skipped++;
}
write("vehicle-market.json", vm);

console.log(`countries: ${countries.countries.length}, rules: ${importrules.rules.length}, taxes: ${taxrules.taxrules.length}, ports: ${ports.ports.length}, routes: ${routes.routes.length}, relations: ${vm.relations.length} (+${added}), skips: ${vm.skipped.length} (+${skipped})`);
