// Batch: market-countries9 — add 6 high-commercial-value countries + data layer.
// Countries: Paraguay (Latin America re-export hub), Angola (Africa high-duty), Mozambique (Africa RHD),
//            Uganda (East Africa RHD), Tajikistan (Central Asia EV-relief), Zimbabwe (Southern Africa RHD).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "paraguay", name: "Paraguay", name_zh: "巴拉圭", region: "latin-america", drive_side: "lhd", currency: "PYG", status: "active", source: "Dirección Nacional de Aduanas (Paraguay) / JP Sheet import guide", source_url: "https://jpsheet.com/import-guide/paraguay/", source_date: D, confidence: "high" },
  { country_id: "angola", name: "Angola", name_zh: "安哥拉", region: "africa", drive_side: "lhd", currency: "AOA", status: "active", source: "Angola Customs (AGT) / US trade.gov (Angola import tariffs)", source_url: "https://www.trade.gov/country-commercial-guides/angola-import-tariffs", source_date: D, confidence: "high" },
  { country_id: "mozambique", name: "Mozambique", name_zh: "莫桑比克", region: "africa", drive_side: "rhd", currency: "MZN", status: "active", source: "Autoridade Tributária de Moçambique (AT) / carimports.co.mz import guide", source_url: "https://www.carimports.co.mz/insights/the-complete-2026-guide-to-car-import-age-limits-and-restrictions-in-mozambique/", source_date: D, confidence: "high" },
  { country_id: "uganda", name: "Uganda", name_zh: "乌干达", region: "africa", drive_side: "rhd", currency: "UGX", status: "active", source: "Uganda Revenue Authority (URA)", source_url: "https://ura.go.ug/en/import-export-faqs/", source_date: D, confidence: "high" },
  { country_id: "tajikistan", name: "Tajikistan", name_zh: "塔吉克斯坦", region: "central-asia", drive_side: "lhd", currency: "TJS", status: "active", source: "Government Decree No. 355 (2023) / Product Compliance Institute", source_url: "https://www.productcomplianceinstitute.com/2023/09/05/tajikistan-new-regulation-for-the-import-of-vehicles/", source_date: D, confidence: "high" },
  { country_id: "zimbabwe", name: "Zimbabwe", name_zh: "津巴布韦", region: "africa", drive_side: "rhd", currency: "USD", status: "active", source: "Zimbabwe Revenue Authority (ZIMRA)", source_url: "https://www.zimra.co.zw/customs/importation-of-motor-vehicles-by-private-individuals", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Paraguay (LHD, 10-year age limit, Arancel + 10% IVA, Asunción river port) =====
  { rule_id: "py-drive-side", country_id: "paraguay", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Paraguay drives on the right and registers left-hand-drive (LHD) vehicles. A China-market LHD unit imports directly without conversion.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "py-age-limit", country_id: "paraguay", category: "vehicle_age", title: "10-year age limit (Ley 2018/2002)", rule_text: "Paraguay caps used passenger-car imports at 10 model-years old from the year of manufacture (motorcycles 5–7 years), under Ley 2018/2002. In 2026 this means roughly model-year 2016 and newer; registered classic cars over 10 years are a limited exception.", effective_date: null, last_checked: D, source: "JP Sheet / Washin Auto (Paraguay import guides)", source_url: "https://jpsheet.com/import-guide/paraguay/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Dirección Nacional de Aduanas before purchase." },
  { rule_id: "py-duty-stack", country_id: "paraguay", category: "import_eligibility", title: "Arancel duty + 10% IVA + fees", rule_text: "Vehicle import cost is a stack of the Arancel import duty (0–20% depending on origin and category), 10% IVA on the customs value plus duty, and administrative fees — roughly 28–32% of CIF all-in for a used car. Vehicles never qualify for the duty-free menaje (household-goods) exemption.", effective_date: null, last_checked: D, source: "Seaway Export / Move Paraguay (Paraguay guides)", source_url: "https://moveparaguay.com/en/importing/", confidence: "medium", needs_review: true, notes: "Layered Arancel + IVA + fees; exact rate varies by origin. Verify with Dirección Nacional de Aduanas." },
  { rule_id: "py-ev-policy", country_id: "paraguay", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty exemption was confirmed for Paraguay in the sources reviewed; EVs are expected to follow the standard Arancel + IVA + fees stack. Confirm EV treatment with Dirección Nacional de Aduanas.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with Dirección Nacional de Aduanas." },

  // ===== Angola (LHD, uncertain age rule, ~30% duty + 14% VAT, Luanda) =====
  { rule_id: "ao-drive-side", country_id: "angola", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Angola drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / airportcarhub", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "ao-age-limit", country_id: "angola", category: "vehicle_age", title: "Age limit cited inconsistently (5–6 years)", rule_text: "Sources conflict on Angola's used-vehicle age rule: some cite a 5-year prohibition (except diplomats), others a 6-year limit, and others report no strict age limit but high duty. Confirm the current cut-off with Angola Customs (AGT) before sourcing stock.", effective_date: null, last_checked: D, source: "AutoLanded / IAM / chinausedcar.net (Angola guides)", source_url: "https://autolanded.com/angola/", confidence: "low", needs_review: true, notes: "Sources conflict (5 vs 6 years vs no strict limit) — verify with Angola Customs before purchase." },
  { rule_id: "ao-import-process", country_id: "angola", category: "import_eligibility", title: "Restricted regime — high duty, Luanda clearance", rule_text: "Angola operates a restricted import regime with high duty applied at the port of Luanda; treatment depends on vehicle category and assessed value, and the regime has changed in recent years. Clearance needs standard export documents plus import licence/CNCA where applicable.", effective_date: null, last_checked: D, source: "chinausedcar.net (Angola used-car import guide)", source_url: "https://chinausedcar.net/blog/angola-used-car-import-guide", confidence: "medium", needs_review: true, notes: "High-duty restricted regime — verify current requirements with Angola Customs." },
  { rule_id: "ao-ev-policy", country_id: "angola", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty exemption was confirmed for Angola in the sources reviewed; EVs follow the standard 30% duty plus 14% VAT (combined ~42–55%). Confirm EV treatment with Angola Customs.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with Angola Customs." },

  // ===== Mozambique (RHD, no age limit, duty by engine + 17% VAT, Maputo/Beira) =====
  { rule_id: "mz-drive-side", country_id: "mozambique", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Mozambique drives on the left and registers right-hand-drive (RHD) vehicles — unlike its former colonial power Portugal. A China-market LHD unit cannot be registered as-is; source an RHD export unit.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / Enjoy Mozambique", source_url: "https://enjoymoz.com/driving-in-mozambique/", confidence: "high", needs_review: false },
  { rule_id: "mz-age-limit", country_id: "mozambique", category: "vehicle_age", title: "No fixed age limit", rule_text: "Mozambique currently has no import age limit for used vehicles, making it one of the more accessible markets in Southern Africa — though duty may rise with age and the regime can change. Verify current rules with the Autoridade Tributária (AT).", effective_date: null, last_checked: D, source: "carimports.co.mz / chinausedcar.net (Mozambique guides)", source_url: "https://www.carimports.co.mz/insights/the-complete-2026-guide-to-car-import-age-limits-and-restrictions-in-mozambique/", confidence: "medium", needs_review: true, notes: "No age limit today — but confirm with the Autoridade Tributária before sourcing older stock." },
  { rule_id: "mz-import-process", country_id: "mozambique", category: "import_eligibility", title: "JUE digital clearance + NUIT + Intertek inspection", rule_text: "All vehicle clearance runs through the JUE digital customs portal. A valid NUIT (tax identification number) is required, and the Intertek pre-shipment inspection (MOZ number) is mandatory to avoid heavy fines at Maputo/Beira.", effective_date: null, last_checked: D, source: "carimports.co.mz (Maputo port clearance guide)", source_url: "https://carimports.co.mz/insights/a-step-by-step-guide-to-port-clearance-and-freight-forwarding-at-maputo-port/", confidence: "medium", needs_review: true, notes: "JUE + NUIT + Intertek MOZ — verify the document set with the Autoridade Tributária." },
  { rule_id: "mz-ev-policy", country_id: "mozambique", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty exemption was confirmed for Mozambique in the sources reviewed; EVs follow the engine-size-based duty plus 17% VAT. Confirm EV treatment with the Autoridade Tributária.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with the Autoridade Tributária." },

  // ===== Uganda (RHD, 15-year age limit (13 proposed), Euro 4, UNBS, 25% + 18% + env levy) =====
  { rule_id: "ug-drive-side", country_id: "uganda", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Uganda drives on the left and registers right-hand-drive (RHD) vehicles. A China-market LHD unit cannot be registered as-is; source an RHD export unit.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "ug-age-limit", country_id: "uganda", category: "vehicle_age", title: "15-year age limit (13 years proposed for 2026/27)", rule_text: "Uganda prohibits the import of passenger vehicles 15 years old or more from manufacture. The government has proposed reducing the limit to 13 years under the 2026/27 Revenue Enhancement and Compliance Measures. In 2026 this means roughly model-year 2011 and newer (trending toward 2013).", effective_date: null, last_checked: D, source: "carimports.co.ug / Daily Express (Uganda age-rule reporting)", source_url: "https://www.carimports.co.ug/insights/environmental-levy-and-vehicle-age-rules-in-uganda-2026/", confidence: "medium", needs_review: true, notes: "15 years today, 13 proposed — verify the current cut-off with URA before purchase." },
  { rule_id: "ug-import-process", country_id: "uganda", category: "import_eligibility", title: "UNBS inspection + Euro 4/IV emission standard", rule_text: "All used cars must pass inspection by the Uganda National Bureau of Standards (UNBS) on arrival and meet the Euro 4/IV emission standard. Uganda is landlocked — vehicles transit via the Port of Mombasa (Kenya).", effective_date: null, last_checked: D, source: "Automag.ug / URA (Uganda import guides)", source_url: "https://automag.ug/2025/07/07/importing-a-car-to-uganda-in-2025-heres-what-you-need-to-know/", confidence: "medium", needs_review: true, notes: "UNBS inspection + Euro 4; Mombasa transit. Verify with URA before purchase." },
  { rule_id: "ug-ev-policy", country_id: "uganda", category: "ev_policy", title: "Environmental levy relief for newer/EV units", rule_text: "Uganda's environmental levy on imported vehicles is 0% for vehicles under 9 years old and 50% above 9 years — so newer and EV units avoid the heaviest levy. Confirm current EV treatment with URA.", effective_date: null, last_checked: D, source: "Uganda Revenue Authority (URA) / Carawon", source_url: "https://ura.go.ug/en/import-export-faqs/", confidence: "medium", needs_review: true, notes: "Environmental levy 0% (<9yr) vs 50% (≥9yr) — verify EV scope with URA." },

  // ===== Tajikistan (LHD, pre-2013 ban, Euro 4, ~20-30% + 18% VAT, EV exemption) =====
  { rule_id: "tj-drive-side", country_id: "tajikistan", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Tajikistan drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "tj-age-limit", country_id: "tajikistan", category: "vehicle_age", title: "Pre-2013 vehicles banned (Decree No. 355)", rule_text: "Under Government Decree No. 355 of 2 August 2023, Tajikistan prohibits the import of any vehicle produced before 2013 — a fixed cutoff, not a rolling window. For 2026 imports only model-year 2013 and newer are permitted.", effective_date: "2023-08-02", last_checked: D, source: "Product Compliance Institute / eAutoExport (Tajikistan)", source_url: "https://www.productcomplianceinstitute.com/2023/09/05/tajikistan-new-regulation-for-the-import-of-vehicles/", confidence: "medium", needs_review: true, notes: "Fixed 2013 cutoff — verify current enforcement with Tajik Customs." },
  { rule_id: "tj-emission", country_id: "tajikistan", category: "emission", title: "Euro 4 emission standard minimum", rule_text: "Imported passenger vehicles must meet the Euro 4 (or higher) emission standard.", effective_date: null, last_checked: D, source: "EncarExport (Tajikistan import guide)", source_url: "https://encarexport.com/en/blog/import-used-car-korea-to-tajikistan", confidence: "medium", needs_review: true, notes: "Euro 4 minimum — verify with Tajik Customs." },
  { rule_id: "tj-ev-policy", country_id: "tajikistan", category: "ev_policy", title: "EV import-duty exemption (10 years from Oct 2022)", rule_text: "To promote EV adoption, Tajikistan has implemented a tax exemption for electric cars, buses and trolleys — including import-duty exemption for a 10-year period starting October 2022. Confirm current EV treatment with Tajik Customs.", effective_date: "2022-10-01", last_checked: D, source: "AutoCango (Tajikistan import regulations)", source_url: "https://www.autocango.com/blog-detail/tajikistan-regulation-import-used-cars-from-china", confidence: "medium", needs_review: true, notes: "EV import-duty exemption (10 years) — verify with Tajik Customs before trading." },

  // ===== Zimbabwe (RHD, 10-year age limit SI 54/2024, duty by engine + surtax + 15% VAT, EV 25%) =====
  { rule_id: "zw-drive-side", country_id: "zimbabwe", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Zimbabwe drives on the left and registers right-hand-drive (RHD) vehicles. A China-market LHD unit cannot be registered as-is; source an RHD export unit.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "zw-age-limit", country_id: "zimbabwe", category: "vehicle_age", title: "10-year age limit (S.I. 54 of 2024)", rule_text: "Under S.I. 54 of 2024, motor vehicles aged 10 years and above (from date of manufacture) are prohibited from import into Zimbabwe; S.I. 172 of 2024 permits certain categories to import vehicles 10+ years old. In 2026 this means roughly model-year 2016 and newer for the general channel.", effective_date: null, last_checked: D, source: "Zimbabwe Revenue Authority (ZIMRA)", source_url: "https://www.zimra.co.zw/public-notices", confidence: "medium", needs_review: true, notes: "10-year limit with S.I. 172 exceptions — verify with ZIMRA before purchase." },
  { rule_id: "zw-import-process", country_id: "zimbabwe", category: "import_eligibility", title: "ZIMRA valuation + Durban transit + border clearance", rule_text: "Zimbabwe is landlocked; vehicles typically transit via Durban (South Africa) or Beira (Mozambique) and clear at the Beitbridge or Forbes border posts. ZIMRA values the vehicle independently for duty assessment, and pre-export inspection documentation is required.", effective_date: null, last_checked: D, source: "ZIMRA / carimports.co.zw (Zimbabwe import guide)", source_url: "https://www.carimports.co.zw/insights/the-complete-2026-guide-to-car-import-age-limits-and-restrictions-in-zimbabwe/", confidence: "medium", needs_review: true, notes: "Durban/Beira transit + ZIMRA valuation. Verify with ZIMRA before purchase." },
  { rule_id: "zw-ev-policy", country_id: "zimbabwe", category: "ev_policy", title: "EV duty 25% (hybrid 40%)", rule_text: "Zimbabwe's ZIMRA import rules tax electric vehicles at 25% customs duty (hybrids at 40%), with electric tractors duty-free and surtax on older vehicles — a reduced EV rate versus the engine-size ICE schedule. Confirm current rates with ZIMRA.", effective_date: null, last_checked: D, source: "EV24.africa (Zimbabwe EV duty rules)", source_url: "https://www.ev24.africa/zimbabwe-hybrid-ev-duty-rules-zimra-explained/", confidence: "medium", needs_review: true, notes: "EV 25% / hybrid 40% — verify current rates with ZIMRA." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  // Paraguay
  { taxrule_id: "py-duty", country_id: "paraguay", tax_type: "import_duty", label: "Import duty (Arancel)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Seaway Export (Paraguay import guide)", source_url: "https://www.seawayexport.com/destinations/shipping-to-paraguay", confidence: "medium", needs_review: true, notes: "0–20% by origin/category; combined Arancel + IVA + fees ≈ 28–32% all-in. Verify with Dirección Nacional de Aduanas.", value_min: 0, value_max: 20 },
  { taxrule_id: "py-vat", country_id: "paraguay", tax_type: "vat", label: "IVA (VAT)", rate_pct: 10, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Seaway Export (Paraguay import guide)", source_url: "https://www.seawayexport.com/destinations/shipping-to-paraguay", confidence: "medium", needs_review: false },
  // Angola
  { taxrule_id: "ao-duty", country_id: "angola", tax_type: "import_duty", label: "Import duty (passenger vehicles)", rate_pct: 30, basis: "CIF value", effective_date: null, last_checked: D, source: "Rugged Rides Export / AutoLanded (Angola duty)", source_url: "https://autolanded.com/angola/", confidence: "medium", needs_review: true, notes: "30% import duty on CIF; combined duty + excise + VAT ≈ 42–55%. Verify with Angola Customs." },
  { taxrule_id: "ao-vat", country_id: "angola", tax_type: "vat", label: "VAT", rate_pct: 14, basis: "CIF + duty", effective_date: null, last_checked: D, source: "US trade.gov / PwC (Angola VAT)", source_url: "https://www.trade.gov/country-commercial-guides/angola-import-tariffs", confidence: "high", needs_review: false },
  // Mozambique
  { taxrule_id: "mz-duty", country_id: "mozambique", tax_type: "import_duty", label: "Import duty (by engine size)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "japanesecarsdurban.co.za / chinausedcar.net (Mozambique duty)", source_url: "https://japanesecarsdurban.co.za/blog/mozambique-vehicle-import-duty-at-rates-2025", confidence: "medium", needs_review: true, notes: "Varies by engine size; commonly ~20%+ for passenger cars. Verify with the Autoridade Tributária." },
  { taxrule_id: "mz-vat", country_id: "mozambique", tax_type: "vat", label: "VAT", rate_pct: 17, basis: "CIF + duty", effective_date: null, last_checked: D, source: "ShipMZ (Mozambique import tax)", source_url: "https://shipmz.com/artigo/import-tax-in-mozambique-duties-vat-customs-fees-explained", confidence: "medium", needs_review: false },
  // Uganda
  { taxrule_id: "ug-duty", country_id: "uganda", tax_type: "import_duty", label: "Import duty", rate_pct: 25, basis: "CIF value", effective_date: null, last_checked: D, source: "Uganda Revenue Authority (URA)", source_url: "https://ura.go.ug/en/import-export-faqs/", confidence: "high", needs_review: true, notes: "25% import duty (EAC CET). Verify with URA." },
  { taxrule_id: "ug-vat", country_id: "uganda", tax_type: "vat", label: "VAT", rate_pct: 18, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Uganda Revenue Authority (URA)", source_url: "https://ura.go.ug/en/import-export-faqs/", confidence: "high", needs_review: false },
  { taxrule_id: "ug-env-levy", country_id: "uganda", tax_type: "other", label: "Environmental levy (age-based)", rate_pct: 50, basis: "CIF value", effective_date: null, last_checked: D, source: "Uganda Revenue Authority (URA)", source_url: "https://ura.go.ug/en/import-export-faqs/", confidence: "high", needs_review: true, notes: "50% for vehicles ≥9 years old; 0% under 9 years. Plus 6% withholding tax and 1.5% infrastructure levy. Verify with URA." },
  // Tajikistan
  { taxrule_id: "tj-duty", country_id: "tajikistan", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "EncarExport (Tajikistan import guide)", source_url: "https://encarexport.com/en/blog/import-used-car-korea-to-tajikistan", confidence: "medium", needs_review: true, notes: "Approximately 20–30% of value (some sources cite a flat USD schedule by specification). Verify with Tajik Customs.", value_min: 20, value_max: 30 },
  { taxrule_id: "tj-vat", country_id: "tajikistan", tax_type: "vat", label: "VAT", rate_pct: 18, basis: "CIF + duty", effective_date: null, last_checked: D, source: "EncarExport (Tajikistan import guide)", source_url: "https://encarexport.com/en/blog/import-used-car-korea-to-tajikistan", confidence: "medium", needs_review: false },
  { taxrule_id: "tj-ev-duty", country_id: "tajikistan", tax_type: "import_duty", label: "Import duty (electric vehicles, exempt)", rate_pct: 0, basis: "CIF value", effective_date: "2022-10-01", last_checked: D, source: "AutoCango (Tajikistan EV exemption)", source_url: "https://www.autocango.com/blog-detail/tajikistan-regulation-import-used-cars-from-china", confidence: "medium", needs_review: true, notes: "0% import duty on EVs for 10 years from Oct 2022. Verify with Tajik Customs." },
  // Zimbabwe
  { taxrule_id: "zw-duty", country_id: "zimbabwe", tax_type: "import_duty", label: "Import duty (by engine size)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "japanesecarsdurban.co.za (ZIMRA duty rates)", source_url: "https://japanesecarsdurban.co.za/blog/zimbabwe-vehicle-import-duty-zimra-rates-2025", confidence: "medium", needs_review: true, notes: "Customs duty by engine size, plus surtax and VAT. Verify with ZIMRA." },
  { taxrule_id: "zw-vat", country_id: "zimbabwe", tax_type: "vat", label: "VAT", rate_pct: 15, basis: "CIF + duty", effective_date: null, last_checked: D, source: "japanesecarsdurban.co.za / ZimTax (Zimbabwe VAT)", source_url: "https://zimtax.co.zw/import-duty", confidence: "medium", needs_review: true, notes: "15% VAT (standard Zimbabwe rate). Verify with ZIMRA." },
  { taxrule_id: "zw-ev-duty", country_id: "zimbabwe", tax_type: "import_duty", label: "Import duty (electric vehicles)", rate_pct: 25, basis: "CIF value", effective_date: null, last_checked: D, source: "EV24.africa (Zimbabwe EV duty rules)", source_url: "https://www.ev24.africa/zimbabwe-hybrid-ev-duty-rules-zimra-explained/", confidence: "medium", needs_review: true, notes: "EVs 25%, hybrids 40%, electric tractors duty-free. Verify with ZIMRA." },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "py-asuncion", name: "Asunción (river port, via Montevideo/Brazil transit)", country_id: "paraguay", type: "destination", note: "Landlocked — river/road transit via Montevideo (Uruguay) or Brazilian ports" },
  { port_id: "ao-luanda", name: "Luanda", country_id: "angola", type: "destination", note: null },
  { port_id: "mz-maputo", name: "Maputo", country_id: "mozambique", type: "destination", note: null },
  { port_id: "mz-beira", name: "Beira", country_id: "mozambique", type: "destination", note: null },
  { port_id: "ug-kampala", name: "Kampala (via Mombasa transit)", country_id: "uganda", type: "destination", note: "Landlocked — transit via Port of Mombasa (Kenya) then road" },
  { port_id: "tj-dushanbe", name: "Dushanbe (via rail/road transit)", country_id: "tajikistan", type: "destination", note: "Landlocked — rail/road from China or via Poti/Batumi (Georgia) / Bandar Abbas (Iran)" },
  { port_id: "zw-harare", name: "Harare (via Durban/Beira transit)", country_id: "zimbabwe", type: "destination", note: "Landlocked — transit via Durban (South Africa) or Beira (Mozambique); Beitbridge/Forbes border" },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-py-asuncion", origin_port_id: "cn-shanghai", destination_port_id: "py-asuncion", est_days_min: 30, est_days_max: 42, shipping_method: "container", source: "Industry route estimates (via Montevideo transshipment)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-ao-luanda", origin_port_id: "cn-guangzhou", destination_port_id: "ao-luanda", est_days_min: 28, est_days_max: 38, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-mz-maputo", origin_port_id: "cn-shanghai", destination_port_id: "mz-maputo", est_days_min: 22, est_days_max: 32, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-mz-beira", origin_port_id: "cn-guangzhou", destination_port_id: "mz-beira", est_days_min: 24, est_days_max: 34, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-ug-kampala", origin_port_id: "cn-shanghai", destination_port_id: "ug-kampala", est_days_min: 20, est_days_max: 30, shipping_method: "roro", source: "Industry route estimates (sea to Mombasa + road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-lianyungang-to-tj-dushanbe", origin_port_id: "cn-lianyungang", destination_port_id: "tj-dushanbe", est_days_min: 18, est_days_max: 30, shipping_method: "container", source: "Industry route estimates (rail transit via Khorgos)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-zw-harare", origin_port_id: "cn-shanghai", destination_port_id: "zw-harare", est_days_min: 24, est_days_max: 36, shipping_method: "roro", source: "Industry route estimates (sea to Durban + road transit)", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

console.log("countries:", countries.countries.length, "| rules:", importrules.rules.length, "| taxes:", taxrules.taxrules.length, "| ports:", ports.ports.length, "| routes:", routes.routes.length);
