// Batch: market-countries13 (sweep wave) — add 4 countries + data layer.
// Countries: Rwanda (Africa LHD, Euro 4 no age limit, 25% duty + 18% VAT, EV full
//            exemption until mid-2028, RRA, Kigali via Mombasa/Dar transit),
//            Malawi (Africa RHD, no age limit, 25% duty + excise 0–110% + VAT 16.5%,
//            MRA, via Dar es Salaam transit),
//            Albania (Europe LHD, ~10yr age limit + Euro 4/5, 10% MFN duty + 20% VAT,
//            EV VAT exemption new-only, DPD, Durrës),
//            Moldova (Europe LHD, no age limit since 2021, engine+age excise, 20% VAT
//            from 2027, Customs Service, Giurgiulesti).
// All regulatory data cited to official/reliable sources; every statement carries
// source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "rwanda", name: "Rwanda", name_zh: "卢旺达", region: "africa", drive_side: "lhd", currency: "RWF", status: "active", source: "Rwanda Revenue Authority (RRA)", source_url: "https://www.rra.gov.rw", source_date: D, confidence: "high" },
  { country_id: "malawi", name: "Malawi", name_zh: "马拉维", region: "africa", drive_side: "rhd", currency: "MWK", status: "active", source: "Malawi Revenue Authority (MRA)", source_url: "https://www.mra.mw", source_date: D, confidence: "high" },
  { country_id: "albania", name: "Albania", name_zh: "阿尔巴尼亚", region: "europe", drive_side: "lhd", currency: "ALL", status: "active", source: "General Directorate of Customs (DPD)", source_url: "https://dogana.gov.al", source_date: D, confidence: "high" },
  { country_id: "moldova", name: "Moldova", name_zh: "摩尔多瓦", region: "europe", drive_side: "lhd", currency: "MDL", status: "active", source: "Customs Service of the Republic of Moldova", source_url: "https://customs.gov.md", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Rwanda (LHD, Euro 4 no age limit, EV full exemption until mid-2028) =====
  { rule_id: "rw-drive-side", country_id: "rwanda", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Rwanda registers left-hand-drive (LHD) vehicles only. Right-hand-drive (RHD) units are permitted only for a temporary period (about two weeks) before they must be converted to LHD or re-exported. A China-market LHD unit is registrable as-is.", effective_date: null, last_checked: D, source: "Rwanda Revenue Authority / Automag.rw (2026 import rules)", source_url: "https://automag.rw/2026/03/21/car-import-rules-rwanda-2026-taxes-age-limits/", confidence: "medium", needs_review: true, notes: "LHD only; RHD restricted to temporary use. Verify with RRA." },
  { rule_id: "rw-age-limit", country_id: "rwanda", category: "vehicle_age", title: "No fixed age limit — Euro 4 emissions compliance", rule_text: "Rwanda has no fixed vehicle age limit; eligibility is driven by Euro 4/IV emissions compliance (EAC standard EAS 1047:2022). Vehicles manufactured after about January 2006 generally comply, but any unit failing emissions is rejected regardless of age. A certificate of conformity or logbook stating Euro 4 compliance is submitted via the Rwanda Electronic Single Window (ReSW).", effective_date: null, last_checked: D, source: "Automag.rw (Rwanda 2026 import rules) / EAC EAS 1047:2022", source_url: "https://automag.rw/2026/03/21/car-import-rules-rwanda-2026-taxes-age-limits/", confidence: "medium", needs_review: true, notes: "No age limit; Euro 4 emissions is the filter. Verify with RRA/RSB." },
  { rule_id: "rw-import-process", country_id: "rwanda", category: "import_eligibility", title: "ReSW single window + RSB inspection", rule_text: "Rwanda digitised vehicle import clearance through the Rwanda Electronic Single Window (ReSW), which centralises pre-verification of conformity (PVoC), duty calculation and compliance checks. The Rwanda Standards Board (RSB) performs a physical inspection, and importers submit the Euro 4 certificate and proof of CIF value on the platform before shipping.", effective_date: null, last_checked: D, source: "Automag.rw (Rwanda 2026 import rules) / Rwanda Revenue Authority", source_url: "https://automag.rw/2026/03/21/car-import-rules-rwanda-2026-taxes-age-limits/", confidence: "medium", needs_review: true, notes: "ReSW + RSB physical inspection; PVoC. Verify with RRA." },
  { rule_id: "rw-ev-policy", country_id: "rwanda", category: "ev_policy", title: "EV full tax exemption until June 30 2028", rule_text: "Fully electric vehicles are exempt from VAT, customs duties, excise duty and withholding tax until June 30 2028 (effective July 1 2025), including charging equipment, batteries and spare parts. Hybrid vehicles lost their full exemption from July 2025 and now pay 18% VAT plus a tiered excise (5% for 0–3 years, 10% for 3–8 years, 15% for over 8 years) while retaining the 25% import-duty exemption. The EV incentives are reviewed annually.", effective_date: "2025-07-01", last_checked: D, source: "EV24.africa / Rwanda Ministry of Finance (revised EV & hybrid tax incentives)", source_url: "https://www.ev24.africa/rwanda-revises-tax-incentives-to-encourage-ev-and-hybrid-imports/", confidence: "medium", needs_review: true, notes: "EV full exemption until 2028-06-30; hybrids tiered from 2025-07-01. Verify with RRA." },
  { rule_id: "rw-emission", country_id: "rwanda", category: "emission", title: "Euro 4/IV emissions standard (EAS 1047:2022)", rule_text: "All imported vehicles must meet Euro 4/IV equivalent emissions standards aligned with the East African Community standard EAS 1047:2022: petrol vehicles below 1.0 g/km CO and 0.08 g/km NOx, with stricter diesel limits including a 0.025 g/km particulate-matter cap.", effective_date: null, last_checked: D, source: "Automag.rw / EAC EAS 1047:2022", source_url: "https://automag.rw/2026/03/21/car-import-rules-rwanda-2026-taxes-age-limits/", confidence: "medium", needs_review: true, notes: "Euro 4/IV (EAS 1047:2022). Verify with RSB." },

  // ===== Malawi (RHD, no age limit, 25% duty + excise + VAT, via Dar es Salaam) =====
  { rule_id: "mw-drive-side", country_id: "malawi", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Malawi drives on the left and permits only right-hand-drive (RHD) vehicles (special-purpose vehicles such as ambulances and fire engines are excepted). A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / Carbarn Malawi (import rules)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "mw-age-limit", country_id: "malawi", category: "vehicle_age", title: "No age limit", rule_text: "Malawi does not apply a fixed age limit to used-vehicle imports. No specific roadworthiness inspection is required for imported vehicles, though a mandatory pre-shipment condition appraisal by an approved inspection body is part of the document set. Confirm any condition or age rules with the Malawi Revenue Authority (MRA) before sourcing stock.", effective_date: null, last_checked: D, source: "Carbarn Malawi (import rules) / KMC Japan (Malawi guide)", source_url: "https://www.carbarn.mw/import-rules-and-regulations", confidence: "medium", needs_review: true, notes: "No age limit. Verify with MRA." },
  { rule_id: "mw-import-process", country_id: "malawi", category: "import_eligibility", title: "Duty + excise + VAT, cleared via Dar es Salaam transit", rule_text: "Malawi is landlocked; vehicles are shipped to Dar es Salaam (Tanzania) by RoRo and transported onward by road. Duties and taxes are based on engine and seating capacity, and the document set includes the export certificate, original invoice, pre-shipment inspection certificate, bill of lading and condition report. MRA is the customs authority.", effective_date: null, last_checked: D, source: "Carbarn Malawi (import rules) / MRA", source_url: "https://www.carbarn.mw/import-rules-and-regulations", confidence: "medium", needs_review: true, notes: "Via Dar es Salaam transit; RoRo. Verify with MRA." },
  { rule_id: "mw-ev-policy", country_id: "malawi", category: "ev_policy", title: "No EV-specific import-duty relief confirmed", rule_text: "No EV-specific import-duty relief was confirmed for Malawi in the sources reviewed; electric vehicles follow the standard import duty + excise + VAT structure. Confirm current EV treatment with the Malawi Revenue Authority before trading.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with MRA." },

  // ===== Albania (LHD, ~10yr age limit + Euro 4/5, 10% MFN duty + 20% VAT) =====
  { rule_id: "al-drive-side", country_id: "albania", category: "drive_side", title: "Left-hand drive (LHD)", rule_text: "Albania drives on the right and registers left-hand-drive (LHD) vehicles. A China-market LHD unit is registrable as-is.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / Albanian Customs (DPD)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "al-age-limit", country_id: "albania", category: "vehicle_age", title: "Age limit ~10 years + Euro 4/5 emissions", rule_text: "Albania restricts used-vehicle imports to about 10 years of age, with a reported tightening trend, plus a Euro 4/5 emissions requirement. Confirm the current age cut-off and emissions standard with the Albanian General Directorate of Customs (DPD) before sourcing stock.", effective_date: null, last_checked: D, source: "EncarExport (2026 used-car import age limits) / Euronews Albania reporting", source_url: "https://encarexport.com/en/blog/used-car-import-age-limits-by-country", confidence: "low", needs_review: true, notes: "~10 years, tightening reported. Verify with DPD." },
  { rule_id: "al-import-process", country_id: "albania", category: "import_eligibility", title: "ASYCUDA World declaration + NIPT", rule_text: "Albanian customs clearance is administered by the General Directorate of Customs (DPD) through the ASYCUDA World electronic declaration system. Commercial imports require an Albanian NIPT (business tax ID); personal imports use an Albanian ID or passport. Imports follow the Stabilisation and Association Agreement (SAA) alignment with EU customs procedures.", effective_date: null, last_checked: D, source: "Albanian Customs (DPD) / Sherbimekontabiliteti.al (2026 customs guide)", source_url: "https://sherbimekontabiliteti.al/en/albania-customs-import-duties/", confidence: "medium", needs_review: true, notes: "ASYCUDA World; NIPT for commercial imports. Verify with DPD." },
  { rule_id: "al-ev-policy", country_id: "albania", category: "ev_policy", title: "EV VAT exemption (new vehicles only)", rule_text: "Albania exempts from VAT the import and first domestic supply of NEW electric vehicles (zero kilometres, never previously registered in any country) under Article 51(p) of the VAT Law. The exemption does NOT apply to used electric vehicles — subsequent supplies of used EVs follow the general VAT regime (with the margin scheme available to taxable dealers). So used EV imports attract full VAT.", effective_date: null, last_checked: D, source: "Altax.al (VAT treatment of EVs in Albania) — Article 51(p) VAT Law", source_url: "https://altax.al/en/on-the-vat-treatment-of-electric-vehicles-imported-and-sold-in-the-albanian-territory/", confidence: "medium", needs_review: true, notes: "EV VAT exemption is new-vehicle-only; used EVs pay full VAT. Verify with DPD." },

  // ===== Moldova (LHD, no age limit since 2021, engine+age excise, 20% VAT from 2027) =====
  { rule_id: "md-drive-side", country_id: "moldova", category: "drive_side", title: "Left-hand drive (LHD)", rule_text: "Moldova drives on the right and registers left-hand-drive (LHD) vehicles. A China-market LHD unit is registrable as-is.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / Customs Service of Moldova", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "md-age-limit", country_id: "moldova", category: "vehicle_age", title: "No age limit (since Jan 1 2021)", rule_text: "Moldova lifted its 10-year vehicle age ban effective January 1 2021; cars can now be imported without an age limit. Excise duty is charged based on engine type, cylinder capacity and year of manufacture.", effective_date: "2021-01-01", last_checked: D, source: "Rapidasig.md (Moldova car excise) / Customs Service of Moldova", source_url: "https://rapidasig.md/en/useful-info/car-excise-duties", confidence: "medium", needs_review: true, notes: "No age limit since 2021. Verify with the Customs Service." },
  { rule_id: "md-import-process", country_id: "moldova", category: "import_eligibility", title: "Excise + VAT, cleared via Giurgiulesti", rule_text: "Moldova clears vehicle imports at the Danube port of Giurgiulesti. Declarations must be submitted in writing or electronically within 72 hours of import. Excise duty is applied by engine type, displacement and age, with a customs procedures fee (0.4%, capped at EUR 1,800) included in the VAT base.", effective_date: null, last_checked: D, source: "Qualitex Trading (Moldova import regulations) / Mobile.md (customs 2027)", source_url: "https://www.qualitextrading.com/import-regulations/moldova", confidence: "medium", needs_review: true, notes: "Giurgiulesti port; 72-hour declaration. Verify with the Customs Service." },
  { rule_id: "md-ev-policy", country_id: "moldova", category: "ev_policy", title: "EVs excise-free (no engine displacement)", rule_text: "Moldovan excise duty is keyed to engine displacement, so electric vehicles (no engine displacement) are excise-free. From January 1 2027 (under the draft fiscal policy), EVs pay only 20% VAT plus the 0.4% customs procedures fee; before 2027 imported cars are VAT-exempt. Confirm the current VAT treatment for EVs with the Customs Service.", effective_date: null, last_checked: D, source: "Mobile.md (Moldova customs 2027) / Rapidasig.md", source_url: "https://www.mobile.md/en/tools/customs-2027", confidence: "low", needs_review: true, notes: "EVs excise-free; VAT 20% from 2027 (draft). Verify with the Customs Service." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const tax = [
  // Rwanda
  { taxrule_id: "rw-duty", country_id: "rwanda", tax_type: "import_duty", label: "Import duty (EAC CET, ICE vehicles)", rate_pct: 25, basis: "CIF value", effective_date: null, last_checked: D, source: "Rwanda Revenue Authority / trade.gov (Rwanda import tariffs)", source_url: "https://www.trade.gov/country-commercial-guides/rwanda-import-tariffs", confidence: "medium", needs_review: true, notes: "25% EAC Common External Tariff (CIF ≤$60,000 for the reduced rate). Verify with RRA." },
  { taxrule_id: "rw-vat", country_id: "rwanda", tax_type: "vat", label: "VAT", rate_pct: 18, basis: "CIF + duty + handling", effective_date: null, last_checked: D, source: "Automag.rw (Rwanda 2026 import rules)", source_url: "https://automag.rw/2026/03/21/car-import-rules-rwanda-2026-taxes-age-limits/", confidence: "medium", needs_review: true, notes: "18% on CIF + duty + handling fees. Verify with RRA." },
  { taxrule_id: "rw-ev-duty", country_id: "rwanda", tax_type: "import_duty", label: "Import duty (electric vehicles)", rate_pct: 0, basis: "CIF value", effective_date: "2025-07-01", last_checked: D, source: "EV24.africa / Rwanda Ministry of Finance", source_url: "https://www.ev24.africa/rwanda-revises-tax-incentives-to-encourage-ev-and-hybrid-imports/", confidence: "medium", needs_review: true, notes: "EVs exempt from duty, VAT, excise and withholding tax until 2028-06-30. Verify with RRA." },
  { taxrule_id: "rw-excise", country_id: "rwanda", tax_type: "excise", label: "Excise duty (ICE by engine size)", rate_pct: 5, basis: "CIF value", effective_date: null, last_checked: D, source: "Automag.rw (Rwanda 2026 import rules)", source_url: "https://automag.rw/2026/03/21/car-import-rules-rwanda-2026-taxes-age-limits/", confidence: "medium", needs_review: true, notes: "5% (<1500cc), 10% (1500–2500cc), 15% (>2500cc). EVs exempt. Verify with RRA.", value_min: 5, value_max: 15 },
  // Malawi
  { taxrule_id: "mw-duty", country_id: "malawi", tax_type: "import_duty", label: "Import duty (customs)", rate_pct: 25, basis: "CIF value", effective_date: null, last_checked: D, source: "Japanese Cars Durban (Malawi MRA duty 2025) / Carbarn Malawi", source_url: "https://japanesecarsdurban.co.za/blog/malawi-vehicle-import-duty-mra-rates-2025", confidence: "medium", needs_review: true, notes: "~25% import duty on CIF value. Verify with MRA." },
  { taxrule_id: "mw-excise", country_id: "malawi", tax_type: "excise", label: "Import excise (by engine & age)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Japanese Cars Durban (Malawi MRA excise rates 2025)", source_url: "https://japanesecarsdurban.co.za/blog/malawi-vehicle-import-duty-mra-rates-2025", confidence: "low", needs_review: true, notes: "Sliding scale 0–110% by engine capacity and age (e.g. 15% for 1500cc 0–8yr rising to 110% for 3000+cc 12+yr). Verify with MRA.", value_min: 0, value_max: 110 },
  { taxrule_id: "mw-vat", country_id: "malawi", tax_type: "vat", label: "VAT", rate_pct: 16.5, basis: "CIF + duty + excise", effective_date: null, last_checked: D, source: "Japanese Cars Durban (Malawi MRA duty 2025) / Carbarn Malawi", source_url: "https://japanesecarsdurban.co.za/blog/malawi-vehicle-import-duty-mra-rates-2025", confidence: "medium", needs_review: true, notes: "16.5% on CIF + duty + excise (some guides cite a 16.5–30% range by specification). Verify with MRA." },
  // Albania
  { taxrule_id: "al-duty", country_id: "albania", tax_type: "import_duty", label: "Import duty (MFN, non-preferential)", rate_pct: 10, basis: "CIF value", effective_date: null, last_checked: D, source: "Sherbimekontabiliteti.al (Albania customs import duties) / trade.gov", source_url: "https://sherbimekontabiliteti.al/en/albania-customs-import-duties/", confidence: "medium", needs_review: true, notes: "Vehicles fall in the 10% MFN band (10–15% MFN by category); EU-origin is 0% under SAA. Verify with DPD." },
  { taxrule_id: "al-vat", country_id: "albania", tax_type: "vat", label: "VAT", rate_pct: 20, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Sherbimekontabiliteti.al (Albania customs import duties)", source_url: "https://sherbimekontabiliteti.al/en/albania-customs-import-duties/", confidence: "medium", needs_review: true, notes: "20% on customs value (CIF + duty). Verify with DPD." },
  { taxrule_id: "al-excise", country_id: "albania", tax_type: "excise", label: "Excise duty (by engine size & CO2)", rate_pct: null, basis: "Vehicle value", effective_date: null, last_checked: D, source: "Sherbimekontabiliteti.al (Albania customs import duties)", source_url: "https://sherbimekontabiliteti.al/en/albania-customs-import-duties/", confidence: "low", needs_review: true, notes: "By engine size and CO2 emissions — minimal for small eco-friendly vehicles, significant for large/high-emission units. Verify with DPD." },
  // Moldova
  { taxrule_id: "md-duty", country_id: "moldova", tax_type: "import_duty", label: "Customs duty (passenger cars)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Customs Service of Moldova / Mobile.md", source_url: "https://www.mobile.md/en/tools/customs-2027", confidence: "low", needs_review: true, notes: "No separate customs duty identified for passenger cars — excise (engine + age) and VAT apply. Verify with the Customs Service." },
  { taxrule_id: "md-excise", country_id: "moldova", tax_type: "excise", label: "Excise duty (by engine displacement & age)", rate_pct: null, basis: "Engine displacement × age (lei/cm³)", effective_date: null, last_checked: D, source: "Rapidasig.md (Moldova car excise) / Customs Service of Moldova", source_url: "https://rapidasig.md/en/useful-info/car-excise-duties", confidence: "medium", needs_review: true, notes: "Per-cm³ schedule rising with engine size and age (e.g. ~12.23 lei/cm³ for 1001–1500cc 0–2yr up to ~46.79 lei/cm³ at 15yr). EVs (no displacement) are excise-free. Verify with the Customs Service." },
  { taxrule_id: "md-vat", country_id: "moldova", tax_type: "vat", label: "VAT", rate_pct: 20, basis: "Customs value + excise + procedures fee", effective_date: "2027-01-01", last_checked: D, source: "Mobile.md (Moldova customs 2027) / Ministry of Finance draft", source_url: "https://www.mobile.md/en/tools/customs-2027", confidence: "low", needs_review: true, notes: "20% VAT from 2027-01-01 (currently imported cars are VAT-exempt). Draft fiscal policy — verify with the Customs Service." },
  { taxrule_id: "md-ev-excise", country_id: "moldova", tax_type: "excise", label: "Excise duty (electric vehicles)", rate_pct: 0, basis: "Not applicable (no engine displacement)", effective_date: null, last_checked: D, source: "Mobile.md (Moldova customs 2027) / Rapidasig.md", source_url: "https://www.mobile.md/en/tools/customs-2027", confidence: "low", needs_review: true, notes: "EVs have no engine displacement, so excise is 0; only VAT (20% from 2027) + procedures fee. Verify with the Customs Service." },
];
for (const t of tax) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "rw-kigali", name: "Kigali (via Mombasa/Dar es Salaam transit)", country_id: "rwanda", type: "destination", note: "Landlocked — transit via Mombasa (Kenya) or Dar es Salaam (Tanzania) then road" },
  { port_id: "mw-lilongwe", name: "Lilongwe (via Dar es Salaam transit)", country_id: "malawi", type: "destination", note: "Landlocked — transit via Dar es Salaam (Tanzania) then road" },
  { port_id: "al-durres", name: "Durrës", country_id: "albania", type: "destination", note: "Main RoRo port" },
  { port_id: "md-giurgiulesti", name: "Giurgiulesti", country_id: "moldova", type: "destination", note: "Danube port; sole Moldovan port" },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-rw-kigali", origin_port_id: "cn-shanghai", destination_port_id: "rw-kigali", est_days_min: 20, est_days_max: 30, shipping_method: "roro", source: "Industry route estimates (via Mombasa transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-mw-lilongwe", origin_port_id: "cn-shanghai", destination_port_id: "mw-lilongwe", est_days_min: 26, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates (via Dar es Salaam transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-al-durres", origin_port_id: "cn-shanghai", destination_port_id: "al-durres", est_days_min: 20, est_days_max: 30, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-md-giurgiulesti", origin_port_id: "cn-shanghai", destination_port_id: "md-giurgiulesti", est_days_min: 25, est_days_max: 35, shipping_method: "roro", source: "Industry route estimates (via Black Sea)", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

console.log("countries:", countries.countries.length);
console.log("importrules:", importrules.rules.length);
console.log("taxrules:", taxrules.taxrules.length);
console.log("ports:", ports.ports.length);
console.log("routes:", routes.routes.length);
