// Batch: market-countries6 — add 6 high-commercial-value countries + data layer + Vehicle×Market relations.
// Countries: Kuwait (GCC last piece), Armenia (Caucasus/EAEU), Dominican Republic (Caribbean),
//            Ecuador (Andean), Uruguay (Mercosur), Panama (Central America / Colón Free Zone).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";
const GBTSRC = "https://en.wikipedia.org/wiki/GB/T_charging_standard";
const MODELS = "https://data.chinausedautohub.com/models/";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "kuwait", name: "Kuwait", name_zh: "科威特", region: "middle-east", drive_side: "lhd", currency: "KWD", status: "active", source: "Kuwait General Administration of Customs / GCC framework", source_url: "https://www.customs.gov.kw/", source_date: D, confidence: "high" },
  { country_id: "armenia", name: "Armenia", name_zh: "亚美尼亚", region: "central-asia", drive_side: "lhd", currency: "AMD", status: "active", source: "State Revenue Committee of Armenia / EAEU Common Customs Tariff", source_url: "https://carawon.com/en/import-to-armenia", source_date: D, confidence: "high" },
  { country_id: "dominican-republic", name: "Dominican Republic", name_zh: "多米尼加共和国", region: "latin-america", drive_side: "lhd", currency: "DOP", status: "active", source: "Dirección General de Aduanas (DGA) / Law 04-07", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_date: D, confidence: "high" },
  { country_id: "ecuador", name: "Ecuador", name_zh: "厄瓜多尔", region: "latin-america", drive_side: "lhd", currency: "USD", status: "active", source: "Servicio Nacional de Aduana del Ecuador (SENAE) / INEN", source_url: "https://autolanded.com/ecuador/", source_date: D, confidence: "high" },
  { country_id: "uruguay", name: "Uruguay", name_zh: "乌拉圭", region: "latin-america", drive_side: "lhd", currency: "UYU", status: "active", source: "Dirección Nacional de Aduanas (Uruguay) / Law 18.250", source_url: "https://www.aduanas.gub.uy/innovaportal/v/5699/3/innova.front/vehiculos-usados.html", source_date: D, confidence: "high" },
  { country_id: "panama", name: "Panama", name_zh: "巴拿马", region: "latin-america", drive_side: "lhd", currency: "USD", status: "active", source: "Autoridad Nacional de Aduanas (ANA) / Colón Free Zone", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Kuwait (LHD GCC, ~5-year age limit, 5% duty, no VAT) =====
  { rule_id: "kw-drive-side", country_id: "kuwait", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Kuwait drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive vehicles are generally not registrable.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "kw-age-limit", country_id: "kuwait", category: "vehicle_age", title: "Used passenger cars ~5 years old", rule_text: "Kuwait restricts used private passenger-car imports to about five years from the date of manufacture — stricter than several other Gulf states. Confirm the current threshold with Kuwait Customs before sourcing stock.", effective_date: null, last_checked: D, source: "The Ship Cars (Kuwait import guide) / Kuwait Customs", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Kuwait General Administration of Customs before purchase." },
  { rule_id: "kw-gcc-spec", country_id: "kuwait", category: "import_eligibility", title: "GCC specification conformity", rule_text: "Imported vehicles must conform to GCC (Gulf specification) standards covering climate-appropriate cooling, safety and emissions. Non-GCC-spec vehicles may require modification or assessment through Kuwait Customs and the Public Authority for Industry.", effective_date: null, last_checked: D, source: "The Ship Cars (Kuwait import guide)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Kuwait Customs before purchase." },
  { rule_id: "kw-tax-stack", country_id: "kuwait", category: "other", title: "5% customs duty; no VAT", rule_text: "Kuwait applies a modest 5% customs duty on the assessed customs value for most passenger vehicles and has not implemented a broad-based VAT (no VAT applies to vehicle imports). Total import tax burden is comparatively light, provided age and specification requirements are met.", effective_date: null, last_checked: D, source: "The Ship Cars / JP Sheet (Kuwait import guide)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Kuwait Customs before purchase." },
  { rule_id: "kw-ev-policy", country_id: "kuwait", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was identified for Kuwait in the sources reviewed; the flat 5% duty applies to all vehicles. EV adoption is driven by charging infrastructure rather than duty relief.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with Kuwait Customs." },

  // ===== Armenia (LHD, EAEU, EV duty-free quota + VAT exemption 2026) =====
  { rule_id: "am-drive-side", country_id: "armenia", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Armenia registers left-hand-drive (LHD) vehicles only. Japanese domestic-market (RHD) cars cannot be registered in Armenia — source LHD export-spec units.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / Carawon", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "am-eaeu", country_id: "armenia", category: "import_eligibility", title: "EAEU Common Customs Tariff + 20% VAT", rule_text: "Armenia is an EAEU member and applies the EAEU Common Customs Tariff to non-EAEU vehicles: about 15% ad valorem for company (legal-entity) imports, plus 20% VAT on CIF + duty. Individuals importing for personal use instead pay an age- and engine-displacement (EUR-per-cc) unified customs payment.", effective_date: null, last_checked: D, source: "Carawon (Armenia import guide)", source_url: "https://carawon.com/en/import-to-armenia", confidence: "medium", needs_review: true, notes: "Duty base differs by importer status (company % vs individual EUR-per-cc) — verify with the State Revenue Committee." },
  { rule_id: "am-individual-duty", country_id: "armenia", category: "other", title: "Individual import: age/engine EUR-per-cc payment", rule_text: "For personal-use imports, Armenia charges a unified customs payment keyed to vehicle age and engine displacement (EUR-per-cc) rather than a flat percentage — so the effective duty is not a single number. Road tax and an environmental payment are also collected at entry.", effective_date: null, last_checked: D, source: "Carawon (Armenia import guide)", source_url: "https://carawon.com/en/import-to-armenia", confidence: "medium", needs_review: true, notes: "EUR-per-cc basis scales with engine size and age — verify with the State Revenue Committee." },
  { rule_id: "am-ev-policy", country_id: "armenia", category: "ev_policy", title: "EV 2026 duty-free quota + VAT exemption", rule_text: "In 2026 electric vehicles benefit from an EAEU 15,000-unit duty-free import quota plus a VAT exemption running through 31 December 2026 (duty exemption for permanent residents; EVs built 2024–2026) — a strong relief delta versus the ~15% duty + 20% VAT on combustion vehicles.", effective_date: "2026-01-01", last_checked: D, source: "Carawon / Mekenan (Armenia EV 2026)", source_url: "https://www.mekenan.com/en/blog/your-complete-guide-to-the-2026-ev-vat-exemption-in-armenia", confidence: "medium", needs_review: true, notes: "EV quota + VAT exemption runs to 31 Dec 2026 — verify current status with the State Revenue Committee." },
  { rule_id: "am-transit", country_id: "armenia", category: "other", title: "Landlocked — transit via Poti (Georgia) to Yerevan", rule_text: "Armenia is landlocked. The main corridor is sea freight to Poti (Georgia), then bonded overland transit through Georgia (Bagratashen/Sadakhlo) to Yerevan. EAEU-sourced vehicles may instead use the Upper Lars corridor from Russia.", effective_date: null, last_checked: D, source: "Carawon (Armenia import guide)", source_url: "https://carawon.com/en/import-to-armenia", confidence: "medium", needs_review: true, notes: "Transit routing is operational guidance, not regulation — confirm with a forwarder." },
  { rule_id: "am-age-limit", country_id: "armenia", category: "vehicle_age", title: "No strict age limit identified", rule_text: "No single universal used-vehicle age limit was identified for Armenia in the sources reviewed; eligibility is governed by EAEU certification and the age/engine-size duty schedule (which rises for older vehicles). Confirm current used-vehicle eligibility with the State Revenue Committee.", effective_date: null, last_checked: D, source: "Needs verification (no explicit age rule located)", source_url: null, confidence: "unknown", needs_review: true, notes: "Used-vehicle age eligibility not clearly documented — verify with the State Revenue Committee." },

  // ===== Dominican Republic (LHD, 5-year rule, 20% duty + 18% ITBIS + 17% plate) =====
  { rule_id: "do-drive-side", country_id: "dominican-republic", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "The Dominican Republic drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "do-age-limit", country_id: "dominican-republic", category: "vehicle_age", title: "5-year age limit (cars); 15 years (trucks)", rule_text: "Under Law 04-07 (5 Jan 2007), used passenger cars more than five years old (from manufacture) may not be imported; trucks and heavy vehicles are limited to fifteen years. In 2026 this means roughly model-year 2021 and newer for passenger cars.", effective_date: null, last_checked: D, source: "Contadores Dominicanos / Law 04-07 / DGA", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", confidence: "high", needs_review: true, notes: "Age rule enforced at inspection — verify current cut-off with the DGA before purchase." },
  { rule_id: "do-salvage-ban", country_id: "dominican-republic", category: "import_eligibility", title: "Salvage vehicles prohibited (Decree 671-02)", rule_text: "Decree 671 of 27 Aug 2002 prohibits the importation of salvage vehicles (collision, theft-recovered, flood or otherwise damaged units). A clean, lien-free title is required.", effective_date: null, last_checked: D, source: "Contadores Dominicanos / Decree 671-02", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with the DGA before purchase." },
  { rule_id: "do-tax-stack", country_id: "dominican-republic", category: "other", title: "20% duty + 18% ITBIS + 17% first-plate", rule_text: "Vehicle imports face a layered tax stack: 20% customs duty on value, 18% ITBIS (VAT), and a first-registration (placa) tax of 17% of the CIF value scaled by CO₂ emissions under Law 253-12, plus a circulation tax (marbete) and a 2% transfer cost. Combined burden can approach or exceed half the vehicle value.", effective_date: null, last_checked: D, source: "Contadores Dominicanos / DGA / Law 253-12", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with the DGA before purchase." },
  { rule_id: "do-ev-policy", country_id: "dominican-republic", category: "ev_policy", title: "EV / hybrid reduced duties (evolving)", rule_text: "Electric vehicles and hybrids have historically enjoyed reduced import duties under clean-energy incentives; the current 2026 scope should be confirmed with the DGA, as the policy framework has been evolving.", effective_date: null, last_checked: D, source: "DRRevealed / DGA (EV incentive, evolving)", source_url: "https://drrevealed.com/moving-to-dr/moving-logistics/can-i-import-my-car-to-the-dominican-republic-the-5-year-rule", confidence: "low", needs_review: true, notes: "EV incentive scope evolving — verify current status with the DGA." },

  // ===== Ecuador (LHD, 1-year rule / used imports prohibited, strong EV relief) =====
  { rule_id: "ec-drive-side", country_id: "ecuador", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Ecuador drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "ec-age-limit", country_id: "ecuador", category: "vehicle_age", title: "1-year age limit — used imports effectively prohibited", rule_text: "Ecuador allows imported vehicles up to roughly one year old (counted from the year of manufacture); used-vehicle imports are effectively prohibited, with diplomatic and returning-migrant cases as the only exceptions.", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide) / SENAE", source_url: "https://autolanded.com/ecuador/", confidence: "medium", needs_review: true, notes: "Used-car imports restricted — verify current conditions with SENAE before purchase." },
  { rule_id: "ec-inen", country_id: "ecuador", category: "import_eligibility", title: "INEN conformity certificate (prior control)", rule_text: "Vehicle imports require an INEN Certificado de Conformidad / Reconocimiento (Servicio Ecuatoriano de Normalización) filed with the customs declaration via the VUE — a prior-control document issued for the model or model family.", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide) / INEN", source_url: "https://autolanded.com/ecuador/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with SENAE/INEN before purchase." },
  { rule_id: "ec-tax-stack", country_id: "ecuador", category: "other", title: "~34% duty + 10% excise + 15% VAT (~70% combined)", rule_text: "Combustion-vehicle imports face a compounding stack: ~34% customs duty, ~10% excise (ICE) on CIF + duty, 15% VAT on the cumulative base, plus para-fiscal levies — roughly 60–80% of CIF combined. ICE is assessed against the official retail price (PVP), not the invoice.", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide) / SENAE", source_url: "https://autolanded.com/ecuador/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with SENAE before purchase." },
  { rule_id: "ec-ev-policy", country_id: "ecuador", category: "ev_policy", title: "EV incentive (~0.5–2% vs ~70% ICE)", rule_text: "Electric vehicles attract a dramatically lower combined tax of roughly 0.5–2% of CIF (versus ~60–80% for combustion vehicles), but BEV duty/VAT relief requires a Ministry-of-Environment exemption approval. The incentive favors new EV units since used imports are effectively prohibited.", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide)", source_url: "https://autolanded.com/ecuador/", confidence: "medium", needs_review: true, notes: "BEV relief needs environmental approval — verify current scope with SENAE." },

  // ===== Uruguay (LHD, Mercosur CET + 22% VAT, >10yr restricted) =====
  { rule_id: "uy-drive-side", country_id: "uruguay", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Uruguay drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "uy-age-limit", country_id: "uruguay", category: "vehicle_age", title: "Used cars over 10 years restricted", rule_text: "Uruguay restricts import of used cars more than 10 years old. Project cargo and machinery follow standard tariff rules with no age gate.", effective_date: null, last_checked: D, source: "Seaway Project Cargo (Uruguay import guide)", source_url: "https://seawayprojectcargo.com/en/blog/importing-to-uruguay-mercosur-duty-vat", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Dirección Nacional de Aduanas before purchase." },
  { rule_id: "uy-returning-citizens", country_id: "uruguay", category: "import_eligibility", title: "Returning-citizen-only imports (Law 18.250 / Decree 330/2008)", rule_text: "Under Law 18.250 and Decree 330/2008, only returning Uruguayan citizens (with at least 12 months of prior vehicle use and 2 years' residence abroad) may import a used vehicle; private non-citizens and Uruguayan diplomats cannot import vehicles. The vehicle cannot be sold or transferred for 4 years.", effective_date: null, last_checked: D, source: "Qualitex Trading (Uruguay import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/uruguay", confidence: "medium", needs_review: true, notes: "Import eligibility is narrow (returning citizens) — verify with Dirección Nacional de Aduanas." },
  { rule_id: "uy-tax-stack", country_id: "uruguay", category: "other", title: "Mercosur CET duty + 22% VAT", rule_text: "As a Mercosur member, Uruguay applies the bloc's Common External Tariff to extra-zone goods (tariff by HS code), plus 22% VAT (IVA) on the duty-inclusive value and first-registration charges.", effective_date: null, last_checked: D, source: "Seaway Project Cargo (Uruguay import guide)", source_url: "https://seawayprojectcargo.com/en/blog/importing-to-uruguay-mercosur-duty-vat", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Dirección Nacional de Aduanas." },
  { rule_id: "uy-ev-policy", country_id: "uruguay", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was identified for Uruguay in the sources reviewed; the Mercosur CET duty plus 22% VAT applies. Uruguay promotes EV adoption through local incentives that do not reduce used-vehicle import duty.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with Dirección Nacional de Aduanas." },

  // ===== Panama (LHD, age limit conflicting, Colón Free Zone) =====
  { rule_id: "pa-drive-side", country_id: "panama", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Panama does not allow the import of right-hand-drive vehicles for road registration; left-hand-drive (LHD) only. This is enforced consistently with no widely recognised exceptions for passenger cars.", effective_date: null, last_checked: D, source: "West Coast Shipping (Panama import guide)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", confidence: "high", needs_review: false },
  { rule_id: "pa-age-limit", country_id: "panama", category: "vehicle_age", title: "Age limit conflicting (5 / 7 / 10 years cited)", rule_text: "Panama's vehicle age restriction is cited inconsistently across sources (five, seven or ten years from manufacture), and enforcement appears to vary by port and inspector. Verify the current threshold with a Panamanian customs broker before shipping any near-limit vehicle.", effective_date: null, last_checked: D, source: "West Coast Shipping (Panama import guide)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", confidence: "medium", needs_review: true, notes: "Conflicting age limits across sources — verify with ANA Panama before purchase." },
  { rule_id: "pa-clean-title", country_id: "panama", category: "import_eligibility", title: "Clean title required (salvage rejected)", rule_text: "The vehicle must have a clear, lien-free title in the importer's name. Salvage titles, rebuilt titles and vehicles with unresolved liens are likely to be rejected or face significant complications at customs.", effective_date: null, last_checked: D, source: "West Coast Shipping (Panama import guide)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with ANA Panama before purchase." },
  { rule_id: "pa-free-zone", country_id: "panama", category: "other", title: "Colón Free Zone + Pensionado duty exemption", rule_text: "Panama operates the Colón Free Zone, a major regional re-export hub where goods (including vehicles) can enter duty-free for re-export. Qualifying Pensionado retirement-visa holders may claim an import-duty exemption on one personal vehicle every two years. A clean US export declaration and certificate of origin are part of the document pack.", effective_date: null, last_checked: D, source: "West Coast Shipping (Panama import guide)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", confidence: "medium", needs_review: true, notes: "Pensionado exemption and Free Zone treatment are scheme-specific — verify with ANA Panama." },
  { rule_id: "pa-ev-policy", country_id: "panama", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was identified for Panama in the sources reviewed; the standard duty plus ITBMS applies. EV adoption is growing but driven by local incentives rather than import-duty relief.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with ANA Panama." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  // Kuwait
  { taxrule_id: "kw-duty", country_id: "kuwait", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: 5, basis: "CIF value", effective_date: null, last_checked: D, source: "The Ship Cars / Kuwait Customs", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", confidence: "medium", needs_review: true, notes: "5% standard customs duty. Verify with Kuwait Customs." },
  { taxrule_id: "kw-vat", country_id: "kuwait", tax_type: "vat", label: "VAT (not implemented)", rate_pct: 0, basis: "N/A", effective_date: null, last_checked: D, source: "JP Sheet / The Ship Cars (Kuwait)", source_url: "https://jpsheet.com/import-guide/kuwait/", confidence: "high", needs_review: false, notes: "No VAT applies to vehicle imports; a broad VAT is ruled out until at least 2028." },

  // Armenia
  { taxrule_id: "am-duty", country_id: "armenia", tax_type: "import_duty", label: "Import duty (EAEU Common Customs Tariff, company imports)", rate_pct: 15, basis: "CIF value", effective_date: null, last_checked: D, source: "Carawon (Armenia import guide)", source_url: "https://carawon.com/en/import-to-armenia", confidence: "medium", needs_review: true, notes: "~15% for company imports; individuals pay an age/engine EUR-per-cc payment instead. Verify with the State Revenue Committee." },
  { taxrule_id: "am-vat", country_id: "armenia", tax_type: "vat", label: "VAT", rate_pct: 20, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Carawon (Armenia import guide)", source_url: "https://carawon.com/en/import-to-armenia", confidence: "medium", needs_review: false },
  { taxrule_id: "am-ev-duty", country_id: "armenia", tax_type: "import_duty", label: "Import duty (electric vehicles, 2026 quota + VAT exemption)", rate_pct: 0, basis: "CIF value", effective_date: "2026-01-01", last_checked: D, source: "Mekenan / Carawon (Armenia EV 2026)", source_url: "https://www.mekenan.com/en/blog/your-complete-guide-to-the-2026-ev-vat-exemption-in-armenia", confidence: "medium", needs_review: true, notes: "EVs (2024–2026 build) under EAEU 15,000-unit quota: 0% duty + VAT exemption to 31 Dec 2026. Verify with the State Revenue Committee." },

  // Dominican Republic
  { taxrule_id: "do-duty", country_id: "dominican-republic", tax_type: "import_duty", label: "Import duty (used vehicles)", rate_pct: 20, basis: "CIF value", effective_date: null, last_checked: D, source: "Contadores Dominicanos / DGA", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", confidence: "medium", needs_review: true, notes: "20% on the vehicle value. Verify with the DGA." },
  { taxrule_id: "do-itbis", country_id: "dominican-republic", tax_type: "vat", label: "ITBIS (VAT)", rate_pct: 18, basis: "Taxed base", effective_date: null, last_checked: D, source: "Contadores Dominicanos / DGII", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", confidence: "medium", needs_review: false },
  { taxrule_id: "do-first-plate", country_id: "dominican-republic", tax_type: "excise", label: "First-registration (placa) tax", rate_pct: 17, basis: "CIF value + CO₂/km", effective_date: null, last_checked: D, source: "Contadores Dominicanos / Law 253-12", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", confidence: "low", needs_review: true, notes: "17% scaled by CO₂ emissions under Law 253-12, plus marbete and 2% transfer. Verify with the DGII." },

  // Ecuador
  { taxrule_id: "ec-duty", country_id: "ecuador", tax_type: "import_duty", label: "Import duty (passenger vehicles)", rate_pct: 34, basis: "CIF value", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide) / SENAE", source_url: "https://autolanded.com/ecuador/", confidence: "medium", needs_review: true, notes: "~34% customs duty. Verify with SENAE." },
  { taxrule_id: "ec-excise", country_id: "ecuador", tax_type: "excise", label: "Excise tax (ICE)", rate_pct: 10, basis: "CIF + duty (official PVP)", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide)", source_url: "https://autolanded.com/ecuador/", confidence: "low", needs_review: true, notes: "~10% ICE assessed on the official retail price (PVP), not the invoice. Verify with SENAE." },
  { taxrule_id: "ec-vat", country_id: "ecuador", tax_type: "vat", label: "VAT (IVA)", rate_pct: 15, basis: "CIF + duty + excise", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide)", source_url: "https://autolanded.com/ecuador/", confidence: "medium", needs_review: false },
  { taxrule_id: "ec-ev-duty", country_id: "ecuador", tax_type: "import_duty", label: "Combined import taxes (electric vehicles, incentive)", rate_pct: 0.5, basis: "CIF value", effective_date: null, last_checked: D, source: "AutoLanded (Ecuador import guide)", source_url: "https://autolanded.com/ecuador/", confidence: "low", needs_review: true, notes: "BEVs ~0.5–2% of CIF combined (vs ~60–80% ICE); requires Ministry-of-Environment approval. Verify with SENAE." },

  // Uruguay
  { taxrule_id: "uy-duty", country_id: "uruguay", tax_type: "import_duty", label: "Import duty (Mercosur CET, by HS code)", rate_pct: 20, basis: "CIF value", effective_date: null, last_checked: D, source: "Seaway Project Cargo (Uruguay import guide)", source_url: "https://seawayprojectcargo.com/en/blog/importing-to-uruguay-mercosur-duty-vat", confidence: "low", needs_review: true, notes: "Mercosur Common External Tariff — varies by HS code (commonly ~20–35% for passenger cars). Verify with Dirección Nacional de Aduanas." },
  { taxrule_id: "uy-vat", country_id: "uruguay", tax_type: "vat", label: "VAT (IVA)", rate_pct: 22, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Seaway Project Cargo (Uruguay import guide)", source_url: "https://seawayprojectcargo.com/en/blog/importing-to-uruguay-mercosur-duty-vat", confidence: "medium", needs_review: false },

  // Panama
  { taxrule_id: "pa-duty", country_id: "panama", tax_type: "import_duty", label: "Import duty (used vehicles, ad valorem)", rate_pct: 25, basis: "CIF value", effective_date: null, last_checked: D, source: "West Coast Shipping / ANA Panama (import guide)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", confidence: "low", needs_review: true, notes: "Commonly cited ~25% ad valorem, varying by engine and type. Verify with ANA Panama." },
  { taxrule_id: "pa-itbms", country_id: "panama", tax_type: "vat", label: "ITBMS (VAT)", rate_pct: 7, basis: "CIF + duty", effective_date: null, last_checked: D, source: "West Coast Shipping / ANA Panama (import guide)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", confidence: "medium", needs_review: true, notes: "7% ITBMS standard rate. Verify with ANA Panama." },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "kw-shuwaikh", name: "Shuwaikh Port", country_id: "kuwait", type: "destination", note: null },
  { port_id: "kw-shuaiba", name: "Shuaiba Port", country_id: "kuwait", type: "destination", note: null },
  { port_id: "am-yerevan", name: "Yerevan (via Poti, Georgia transit)", country_id: "armenia", type: "destination", note: "Landlocked — vehicles transit via Port of Poti (Georgia) then road to Yerevan" },
  { port_id: "do-haina", name: "Haina (Santo Domingo)", country_id: "dominican-republic", type: "destination", note: null },
  { port_id: "do-caucedo", name: "Caucedo (DP World)", country_id: "dominican-republic", type: "destination", note: null },
  { port_id: "do-puerto-plata", name: "Puerto Plata", country_id: "dominican-republic", type: "destination", note: "North coast" },
  { port_id: "ec-guayaquil", name: "Guayaquil", country_id: "ecuador", type: "destination", note: null },
  { port_id: "ec-posorja", name: "Posorja", country_id: "ecuador", type: "destination", note: null },
  { port_id: "uy-montevideo", name: "Montevideo", country_id: "uruguay", type: "destination", note: "River Plate transshipment hub (onward to Paraguay/Argentina)" },
  { port_id: "pa-cristobal", name: "Cristóbal (Colón)", country_id: "panama", type: "destination", note: "Atlantic entrance / Colón Free Zone" },
  { port_id: "pa-balboa", name: "Balboa (Panama City)", country_id: "panama", type: "destination", note: "Pacific entrance" },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-kw-shuwaikh", origin_port_id: "cn-shanghai", destination_port_id: "kw-shuwaikh", est_days_min: 18, est_days_max: 26, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-kw-shuaiba", origin_port_id: "cn-guangzhou", destination_port_id: "kw-shuaiba", est_days_min: 20, est_days_max: 28, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-am-yerevan", origin_port_id: "cn-shanghai", destination_port_id: "am-yerevan", est_days_min: 28, est_days_max: 38, shipping_method: "container", source: "Industry route estimates (sea to Poti + road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-do-haina", origin_port_id: "cn-shanghai", destination_port_id: "do-haina", est_days_min: 24, est_days_max: 32, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-do-caucedo", origin_port_id: "cn-guangzhou", destination_port_id: "do-caucedo", est_days_min: 24, est_days_max: 32, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-ec-guayaquil", origin_port_id: "cn-shanghai", destination_port_id: "ec-guayaquil", est_days_min: 30, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-ec-posorja", origin_port_id: "cn-shanghai", destination_port_id: "ec-posorja", est_days_min: 30, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-uy-montevideo", origin_port_id: "cn-shanghai", destination_port_id: "uy-montevideo", est_days_min: 30, est_days_max: 42, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-pa-cristobal", origin_port_id: "cn-shanghai", destination_port_id: "pa-cristobal", est_days_min: 26, est_days_max: 36, shipping_method: "roro", source: "Industry route estimates (Panama Canal)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-pa-balboa", origin_port_id: "cn-shanghai", destination_port_id: "pa-balboa", est_days_min: 26, est_days_max: 36, shipping_method: "roro", source: "Industry route estimates (Panama Canal)", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

// ---------- vehicle-market.json relations ----------
const vm = read("vehicle-market.json");
vm.meta.batch = "batch 17 — market-countries6";
vm.meta.updated = D;

const dsMatch = (summary) => ({ status: "match", summary, source: "Data sub-site models.json (export intelligence) + Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, source_type: "database", confidence: "high", checked_date: D });
const charging = (dest, notes) => ({ standard: "GB/T", destination_standard: dest, connector: "GB/T AC / GB/T DC (vehicle inlet)", voltage: null, frequency: null, needs_adapter: true, notes: notes ?? `China-market GB/T inlet vs ${dest} network — adapter required; confirm the sourced unit's inlet (some export units carry a CCS2 inlet).`, source: "Vehicle: GB/T charging standard (Wikipedia); Destination: Combined Charging System / Type 2 (Wikipedia)", source_url: GBTSRC, source_type: "reputable_media", confidence: "medium", checked_date: D, needs_review: true });

const relations = [
  // ===== Armenia (LHD, EAEU, EV duty-free quota + VAT exemption) =====
  {
    vehicle_id: "byd-atto-3", country_id: "armenia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Armenia registers LHD only — no conversion required."),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Armenia's 2026 EV regime (EAEU 15,000-unit duty-free quota + VAT exemption to 31 Dec 2026) applies, versus ~15% EAEU duty + 20% VAT for combustion vehicles. The strongest EV relief delta in the Caucasus/EAEU set.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)"),
    import_eligibility: { status: "conformity_required", requirements: ["EAEU technical certification", "EV quota + VAT-exemption eligibility (2024–2026 build)"], notes: "The EV quota/VAT exemption runs to 31 Dec 2026 and favours 2024–2026-build units; EAEU certification applies. Confirm quota availability before sourcing.", source: "market sub-site importrules.json (EV 2026 quota)", source_url: "https://www.mekenan.com/en/blog/your-complete-guide-to-the-2026-ev-vat-exemption-in-armenia", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "am-duty", ev_duty_taxrule_id: "am-ev-duty", vat_taxrule_id: "am-vat", ev_duty_relief: true, notes: "EV: 0% duty + VAT exemption (2026 quota) vs 15% duty + 20% VAT standard. Referenced from taxrules.json — verify with the State Revenue Committee.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-armenia", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-am-yerevan"], notes: "Sea freight to Poti (Georgia), then bonded road transit to Yerevan (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Armenia's EV quota + VAT exemption and the Poti→Yerevan corridor are the key fit points. Confirm the sourced unit is 2024–2026 build to qualify.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "li-auto-l7", country_id: "armenia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Armenia registers LHD only — no conversion required."),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "EREV (extended-range electric vehicle) — the EREV class is under-explained in Armenia's EV quota/VAT exemption: whether an EREV (which carries a combustion range-extender) qualifies for the 2026 EV duty-free quota and VAT exemption is unconfirmed and must be clarified with the State Revenue Committee. If classified as a hybrid/combustion, the ~15% + 20% VAT stack applies instead.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)", "EREV charges on AC GB/T; Armenia uses Type 2 / CCS2 — adapter required."),
    import_eligibility: { status: "conformity_required", requirements: ["EAEU technical certification", "EREV-vs-EV classification confirmation"], notes: "EREV classification under Armenia's EV quota/VAT exemption is the open question; EAEU certification applies. Confirm before sourcing.", source: "market sub-site importrules.json (EAEU + EV quota)", source_url: "https://carawon.com/en/import-to-armenia", source_type: "regulatory", confidence: "low", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "am-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "am-vat", ev_duty_relief: false, notes: "EREV classification unconfirmed — if treated as combustion/hybrid, ~15% duty + 20% VAT applies (not the EV quota). Referenced from taxrules.json — verify with the State Revenue Committee.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-armenia", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-am-yerevan"], notes: "Sea freight to Poti (Georgia), then road transit to Yerevan (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Li Auto L7 (理想L7) is an EREV SUV; EREV-vs-EV classification under Armenia's EV quota/VAT exemption is the key fit question.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Li_L7", source_type: "reputable_media", confidence: "low", checked_date: D,
  },
  {
    vehicle_id: "byd-han", country_id: "armenia",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Armenia registers LHD only — no conversion required."),
    age_rule_fit: null,
    powertrain_fit: { status: "noted", summary: "EV and PHEV (DM-i) trims — the EV trim may qualify for Armenia's 2026 EV quota + VAT exemption, but the PHEV DM-i trim's classification is unconfirmed (hybrid vs BEV). This EV-vs-PHEV split is the key open question.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)", "EV trim charges GB/T DC; PHEV DM-i on AC GB/T. Armenia Type 2 / CCS2 — adapter required."),
    import_eligibility: { status: "conformity_required", requirements: ["EAEU technical certification", "EV-vs-PHEV classification confirmation"], notes: "The EV trim may fit the 2026 quota/VAT exemption; the PHEV DM-i trim's classification is unconfirmed. EAEU certification applies.", source: "market sub-site importrules.json (EAEU + EV quota)", source_url: "https://www.mekenan.com/en/blog/your-complete-guide-to-the-2026-ev-vat-exemption-in-armenia", source_type: "regulatory", confidence: "low", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "am-duty", ev_duty_taxrule_id: "am-ev-duty", vat_taxrule_id: "am-vat", ev_duty_relief: true, notes: "EV trim: 0% duty + VAT exemption (2026 quota) vs 15% + 20% VAT; PHEV DM-i classification unconfirmed. Referenced from taxrules.json — verify with the State Revenue Committee.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://carawon.com/en/import-to-armenia", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-am-yerevan"], notes: "Sea freight to Poti (Georgia), then road transit to Yerevan (container).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Han (汉) is an EV/PHEV sedan; EV-vs-PHEV classification under Armenia's EV quota/VAT exemption is the key fit question.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/han", source_type: "manufacturer", confidence: "low", checked_date: D,
  },

  // ===== Ecuador (LHD, used imports prohibited, strong EV relief) =====
  {
    vehicle_id: "byd-atto-3", country_id: "ecuador",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Ecuador registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Atto 3 production began 2022; Ecuador's ~1-year age rule (used imports effectively prohibited) renders any used Atto 3 ineligible. Only a new (current-year) unit qualifies, and the EV incentive applies to new units.", source: "market sub-site importrules.json (1-year age limit)", source_url: "https://autolanded.com/ecuador/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Ecuador's EV incentive (~0.5–2% of CIF combined) versus ~60–80% for combustion vehicles is the widest EV-vs-ICE tax gap in the tracked set, but it applies to NEW units only (used imports are prohibited).", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS2 / Type 2 (Mennekes)"),
    import_eligibility: { status: "conformity_required", requirements: ["INEN conformity certificate", "Ministry-of-Environment approval (BEV relief)", "New (current-year) unit only"], notes: "Used-vehicle imports are effectively prohibited; only new units qualify, and BEV duty/VAT relief needs environmental approval. This is a new-EV destination, not a used-EV destination.", source: "market sub-site importrules.json (INEN + EV relief)", source_url: "https://autolanded.com/ecuador/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "ec-duty", ev_duty_taxrule_id: "ec-ev-duty", vat_taxrule_id: "ec-vat", ev_duty_relief: true, notes: "EV (new): ~0.5–2% combined vs ~34% duty + 10% excise + 15% VAT for ICE (~70%). Referenced from taxrules.json — verify with SENAE.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://autolanded.com/ecuador/", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-ec-guayaquil", "cn-shanghai-to-ec-posorja"], notes: "Sea freight to Guayaquil or Posorja (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Ecuador's used-import prohibition (1-year rule) and the new-EV-only incentive are the key fit questions — this is a new-vehicle market for EVs, not a used-export destination.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "geely-monjaro", country_id: "ecuador",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Ecuador registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Monjaro production began 2021; Ecuador's ~1-year age rule renders any used Monjaro ineligible (used imports effectively prohibited). Only a new unit qualifies, and it would face the ~70% combustion tax stack.", source: "market sub-site importrules.json (1-year age limit)", source_url: "https://autolanded.com/ecuador/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to ~34% duty + 10% excise + 15% VAT (~70% combined). Combined with the used-import prohibition, this makes ICE used-export to Ecuador effectively closed.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["INEN conformity certificate", "New (current-year) unit only"], notes: "Used-vehicle imports are effectively prohibited (1-year rule); only new units qualify, facing the heavy ICE tax stack.", source: "market sub-site importrules.json (INEN + age)", source_url: "https://autolanded.com/ecuador/", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "ec-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "ec-vat", ev_duty_relief: false, notes: "ICE: ~34% duty + 10% excise + 15% VAT (~70% combined). Referenced from taxrules.json — verify with SENAE.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://autolanded.com/ecuador/", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-ec-guayaquil"], notes: "Sea freight to Guayaquil (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; Ecuador's used-import prohibition and heavy ICE tax stack make it effectively closed to used exports — the 1-year rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Dominican Republic (LHD, 5-year rule, 20% duty + 18% ITBIS + 17% plate) =====
  {
    vehicle_id: "byd-atto-3", country_id: "dominican-republic",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); the Dominican Republic registers LHD only — no conversion required."),
    age_rule_fit: { status: "eligible", summary: "Atto 3 production began 2022; the Dominican Republic's 5-year age rule (Law 04-07) is satisfied by current-generation units (2022 = ~4 years old in 2026). Verify the exact manufacture date.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — the Dominican Republic has historically granted reduced duties on EVs/hybrids (clean-energy incentive, evolving in 2026). The CO₂-scaled first-plate tax (Law 253-12) also favours EVs.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS1 / Type 1 (SAE J1772)", "China-market GB/T inlet vs North-American-standard CCS1/Type 1 network — adapter required; DR charging network is early-stage."),
    import_eligibility: { status: "conformity_required", requirements: ["Clean title (Decree 671-02 salvage ban)", "≤5 years old"], notes: "The 5-year age rule and salvage ban are the hard filters; the EV reduced-duty incentive is evolving. A licensed agente aduanal is required in practice.", source: "market sub-site importrules.json (age + salvage ban)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "do-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "do-itbis", ev_duty_relief: false, notes: "20% duty + 18% ITBIS + 17% first-plate (CO₂-scaled); EV reduced-duty incentive evolving (not a fixed rate). Referenced from taxrules.json — verify with the DGA.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-do-haina", "cn-guangzhou-to-do-caucedo"], notes: "Sea freight to Haina or Caucedo (RoRo); Puerto Plata on the north coast.", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; the DR 5-year rule, CO₂-scaled first-plate tax and evolving EV incentive are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "geely-monjaro", country_id: "dominican-republic",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); the Dominican Republic registers LHD only — no conversion required."),
    age_rule_fit: { status: "borderline", summary: "Monjaro production began 2021; the Dominican Republic's 5-year age rule makes 2021 units ~5 years old (borderline) — source 2022+ units and verify the exact cut-off with the DGA.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to 20% duty + 18% ITBIS + 17% first-plate (CO₂-scaled) + marbete + 2% transfer, a heavy layered stack. No EV relief applies to the ICE trim.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["Clean title (Decree 671-02 salvage ban)", "≤5 years old"], notes: "The 5-year age rule (2021 units borderline) and salvage ban are the hard filters; the heavy layered tax stack makes ICE imports expensive.", source: "market sub-site importrules.json (age + salvage ban)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "do-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "do-itbis", ev_duty_relief: false, notes: "ICE: 20% duty + 18% ITBIS + 17% first-plate (CO₂-scaled) + marbete + 2% transfer. Referenced from taxrules.json — verify with the DGA.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-do-haina"], notes: "Sea freight to Haina (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; the DR 5-year rule (2021 units borderline) and the heavy layered ICE tax stack are the key fit questions.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "chery-tiggo-8", country_id: "dominican-republic",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); the Dominican Republic registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 8 production began 2018; the Dominican Republic's 5-year age rule makes 2018 units ~8 years old (ineligible) — source 2021+ units and verify the cut-off with the DGA.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to 20% duty + 18% ITBIS + 17% first-plate + marbete + 2% transfer. No EV relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["Clean title (Decree 671-02 salvage ban)", "≤5 years old"], notes: "The 5-year age rule renders 2018 units ineligible — the age rule is the primary blocker for this model.", source: "market sub-site importrules.json (age + salvage ban)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "regulatory", confidence: "high", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "do-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "do-itbis", ev_duty_relief: false, notes: "ICE: 20% duty + 18% ITBIS + 17% first-plate. Referenced from taxrules.json — verify with the DGA.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://contadoresdominicanos.com/en/post/customs/requirements-for-importing-vehicles-to-the-dominican-republic/", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-guangzhou-to-do-caucedo"], notes: "Sea freight to Caucedo (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 8 is an ICE SUV; the DR 5-year rule renders 2018 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_8", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Kuwait (LHD GCC, ~5-year age limit, 5% duty, no VAT) =====
  {
    vehicle_id: "geely-monjaro", country_id: "kuwait",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Kuwait registers LHD only — no conversion required."),
    age_rule_fit: { status: "borderline", summary: "Monjaro production began 2021; Kuwait's ~5-year age rule makes 2021 units ~5 years old (borderline) — source 2022+ units and verify the cut-off with Kuwait Customs.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to Kuwait's 5% customs duty with no VAT (a comparatively light GCC tax burden). No EV-specific relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["GCC specification", "~5 years old"], notes: "GCC specification conformity and the ~5-year age rule (2021 units borderline) are the key filters.", source: "market sub-site importrules.json (GCC spec + age)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "kw-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "kw-vat", ev_duty_relief: false, notes: "ICE: 5% duty + no VAT. Referenced from taxrules.json — verify with Kuwait Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-kw-shuwaikh"], notes: "Sea freight to Shuwaikh (RoRo); Shuaiba as alternative.", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Geely Monjaro is an ICE SUV; Kuwait's ~5-year age rule (2021 units borderline), GCC specification and 5%-duty/no-VAT regime are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Geely_Xingyue_L", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },
  {
    vehicle_id: "chery-tiggo-8", country_id: "kuwait",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Kuwait registers LHD only — no conversion required."),
    age_rule_fit: { status: "ineligible", summary: "Tiggo 8 production began 2018; Kuwait's ~5-year age rule makes 2018 units ~8 years old (ineligible) — source 2021+ units and verify the cut-off with Kuwait Customs.", source: "market sub-site importrules.json (5-year age limit)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Combustion (ICE) — subject to 5% customs duty with no VAT; no EV-specific relief applies.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    ev_charging_compat: null,
    import_eligibility: { status: "conformity_required", requirements: ["GCC specification", "~5 years old"], notes: "GCC specification and the ~5-year age rule render 2018 units ineligible — the age rule is the primary blocker.", source: "market sub-site importrules.json (GCC spec + age)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "kw-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "kw-vat", ev_duty_relief: false, notes: "ICE: 5% duty + no VAT. Referenced from taxrules.json — verify with Kuwait Customs.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://theshipcars.co.uk/guides/importing-car-to-kuwait", source_type: "government", confidence: "medium", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-guangzhou-to-kw-shuaiba"], notes: "Sea freight to Shuaiba (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "Chery Tiggo 8 is an ICE SUV; Kuwait's ~5-year age rule renders 2018 units ineligible — the age rule is the primary blocker.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "medium", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://en.wikipedia.org/wiki/Chery_Tiggo_8", source_type: "reputable_media", confidence: "medium", checked_date: D,
  },

  // ===== Panama (LHD, age limit conflicting, Colón Free Zone) =====
  {
    vehicle_id: "byd-atto-3", country_id: "panama",
    drive_side_fit: dsMatch("China domestic-market production is left-hand drive (LHD); Panama registers LHD only — no conversion required."),
    age_rule_fit: { status: "borderline", summary: "Atto 3 production began 2022; Panama's age limit is cited inconsistently (5/7/10 years). 2022 units are ~4 years old — under even the strictest cited limit, but verify the current threshold with a Panamanian customs broker.", source: "market sub-site importrules.json (age limit conflicting)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    powertrain_fit: { status: "noted", summary: "Battery-electric (EV) — Panama records no EV-specific import-duty relief (standard duty + 7% ITBMS); the Colón Free Zone and Pensionado exemption are scheme-specific. EV adoption is driven by local incentives.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    ev_charging_compat: charging("CCS1 / Type 1 (SAE J1772)", "China-market GB/T inlet vs North-American-standard CCS1/Type 1 network — adapter required."),
    import_eligibility: { status: "conformity_required", requirements: ["Clean title (salvage rejected)", "Age limit (verify current threshold)"], notes: "The conflicting age limit and clean-title requirement are the key filters; Colón Free Zone re-export and Pensionado exemption are scheme-specific. Verify with ANA Panama.", source: "market sub-site importrules.json (clean title + age + Free Zone)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", source_type: "regulatory", confidence: "medium", checked_date: D, needs_review: true },
    duty_anchors: { standard_duty_taxrule_id: "pa-duty", ev_duty_taxrule_id: null, vat_taxrule_id: "pa-itbms", ev_duty_relief: false, notes: "No EV relief — ~25% duty + 7% ITBMS (verify with ANA). Colón Free Zone / Pensionado exemption are scheme-specific. Referenced from taxrules.json.", source: "market sub-site taxrules.json (referenced, not copied)", source_url: "https://www.wcshipping.com/blog/ship-a-car-to-panama-or-buy-locally-col%C3%B3n-free-zone-guide", source_type: "government", confidence: "low", checked_date: D, needs_review: true },
    shipping_route: { route_ids: ["cn-shanghai-to-pa-cristobal", "cn-shanghai-to-pa-balboa"], notes: "Sea freight to Cristóbal (Atlantic) or Balboa (Pacific) via Panama Canal (RoRo).", source: "market sub-site routes.json (referenced, not copied)", source_url: null, source_type: "industry", confidence: "low", checked_date: D, needs_review: true },
    model_considerations: { status: "noted", summary: "BYD Atto 3 is a compact EV SUV; Panama's conflicting age limit, clean-title rule, no-EV-relief regime and the Colón Free Zone re-export angle are the key fit points.", source: "Data sub-site models.json (export intelligence)", source_url: MODELS, source_type: "database", confidence: "low", checked_date: D, needs_review: true },
    source: "Data sub-site models.json + market sub-site taxrules/importrules (joined)", source_url: "https://www.byd.com/eu/car/atto3", source_type: "manufacturer", confidence: "low", checked_date: D,
  },
];

const skips = [
  { vehicle_id: "byd-seal", country_id: "armenia", reason: "EV × LHD — EV quota/VAT-exemption delta already represented by byd-atto-3 × armenia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "mg-4", country_id: "armenia", reason: "EV × LHD — EV quota/VAT-exemption delta already represented by byd-atto-3 × armenia (mechanical EV cross-product, avoid)." },
  { vehicle_id: "geely-monjaro", country_id: "armenia", reason: "ICE × LHD — EAEU ~15% + 20% VAT is a market-level fact (no EV relief, no age conflict for 2021 start); fails the generation gate." },
  { vehicle_id: "chery-tiggo-8", country_id: "armenia", reason: "ICE × LHD — EAEU duty/VAT is a market-level fact; no age conflict (Armenia has no strict age limit). Fails the generation gate." },
  { vehicle_id: "byd-seal", country_id: "ecuador", reason: "EV × LHD — used-import prohibition + EV incentive delta already represented by byd-atto-3 × ecuador (mechanical EV cross-product, avoid)." },
  { vehicle_id: "chery-tiggo-8", country_id: "ecuador", reason: "ICE × LHD — used-import prohibition delta already represented by geely-monjaro × ecuador (mechanical ICE cross-product, avoid)." },
  { vehicle_id: "byd-seal", country_id: "dominican-republic", reason: "EV × LHD — 5-year rule + evolving EV incentive delta already represented by byd-atto-3 × dominican-republic (mechanical EV cross-product, avoid)." },
  { vehicle_id: "byd-dolphin", country_id: "dominican-republic", reason: "EV × LHD — 5-year rule + EV incentive delta already represented by byd-atto-3 × dominican-republic (mechanical EV cross-product, avoid)." },
  { vehicle_id: "great-wall-haval-h6", country_id: "kuwait", reason: "ICE × LHD — 5-year age-rule delta already represented by chery-tiggo-8 × kuwait (ineligible) and geely-monjaro × kuwait (borderline); mechanical ICE cross-product (avoid)." },
  { vehicle_id: "byd-atto-3", country_id: "kuwait", reason: "EV × LHD — Kuwait has no EV-specific duty relief (flat 5% + no VAT) and no distinct EV increment; charging-only delta already represented (defer, like UAE/Qatar/Oman/Bahrain)." },
  { vehicle_id: "byd-seal", country_id: "kuwait", reason: "EV × LHD — no EV relief recorded; charging-only delta already represented by GCC EV exemplars (defer)." },
  { vehicle_id: "geely-monjaro", country_id: "panama", reason: "ICE × LHD — no age conflict (2021 start under even the strictest cited limit); Colón Free Zone/Pensionado are market-level facts (fails the generation gate)." },
  { vehicle_id: "chery-tiggo-8", country_id: "panama", reason: "ICE × LHD — conflicting age limit is a market-level uncertainty, not a computed vehicle×market increment (fails the generation gate)." },
  { vehicle_id: "byd-atto-3", country_id: "uruguay", reason: "EV × LHD — Uruguay has no EV-specific duty relief (Mercosur CET + 22% VAT is market-level); returning-citizen-only import is a market-level restriction, not a vehicle×market increment (fails the generation gate)." },
  { vehicle_id: "geely-monjaro", country_id: "uruguay", reason: "ICE × LHD — >10-year age restriction is satisfied by 2021 start (no age conflict); returning-citizen-only import and Mercosur CET + 22% VAT are market-level facts (fails the generation gate)." },
  { vehicle_id: "chery-tiggo-8", country_id: "uruguay", reason: "ICE × LHD — 2018 start is ~8 years (under the >10-year restriction, no age conflict); returning-citizen-only import is market-level (fails the generation gate)." },
];

let added = 0;
for (const rel of relations) {
  if (vm.relations.find((x) => x.vehicle_id === rel.vehicle_id && x.country_id === rel.country_id)) continue;
  vm.relations.push(rel);
  added++;
}
let skipped = 0;
for (const s of skips) {
  if (vm.skipped.find((x) => x.vehicle_id === s.vehicle_id && x.country_id === s.country_id)) continue;
  if (vm.relations.find((x) => x.vehicle_id === s.vehicle_id && x.country_id === s.country_id)) continue;
  vm.skipped.push(s);
  skipped++;
}
write("vehicle-market.json", vm);

console.log(`countries: ${countries.countries.length}, rules: ${importrules.rules.length}, taxes: ${taxrules.taxrules.length}, ports: ${ports.ports.length}, routes: ${routes.routes.length}, relations: ${vm.relations.length} (+${added}), skips: ${vm.skipped.length} (+${skipped})`);
