// Batch: market-countries10 — add 6 high-commercial-value countries + data layer.
// Countries: Nepal (South Asia RHD, EV 20% flat duty), Zambia (Africa RHD, specific-duty schedule),
//            Laos (Southeast Asia LHD, EV gas-import ban), Cambodia (Southeast Asia LHD, EV 0% duty),
//            Honduras (Latin America LHD, 10-year age limit), El Salvador (Latin America LHD, 8-year age limit).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "nepal", name: "Nepal", name_zh: "尼泊尔", region: "south-asia", drive_side: "rhd", currency: "NPR", status: "active", source: "Department of Customs, Nepal / EV tax policy (FY 2083/84)", source_url: "https://customs.gov.np/content/50/custom-tariff-rate/", source_date: D, confidence: "high" },
  { country_id: "zambia", name: "Zambia", name_zh: "赞比亚", region: "africa", drive_side: "rhd", currency: "ZMW", status: "active", source: "Zambia Revenue Authority (ZRA) — Specific Duty schedule (2024)", source_url: "https://www.zra.org.zm/wp-content/uploads/2024/11/Specific-Duty-rates-Used-Motor-Vehicle-Valuation-July-2024.pdf", source_date: D, confidence: "high" },
  { country_id: "laos", name: "Laos", name_zh: "老挝", region: "southeast-asia", drive_side: "lhd", currency: "LAK", status: "active", source: "Lao PDR Trade Portal / US ITA (Laos Automotive Sector)", source_url: "https://www.laotradeportal.gov.la/en-gb/site/display/74", source_date: D, confidence: "high" },
  { country_id: "cambodia", name: "Cambodia", name_zh: "柬埔寨", region: "southeast-asia", drive_side: "lhd", currency: "KHR", status: "active", source: "General Department of Customs and Excise (GDCE) / DFDL (2026 tariff reductions)", source_url: "https://www.dfdl.com/insights/legal-and-tax-updates/cambodia-revised-customs-duty-and-tax-rates-on-certain-goods-effective-1-january-2026/", source_date: D, confidence: "high" },
  { country_id: "honduras", name: "Honduras", name_zh: "洪都拉斯", region: "latin-america", drive_side: "lhd", currency: "HNL", status: "active", source: "US trade.gov (Honduras Prohibited & Restricted Imports)", source_url: "https://www.trade.gov/country-commercial-guides/honduras-prohibited-restricted-imports", source_date: D, confidence: "high" },
  { country_id: "el-salvador", name: "El Salvador", name_zh: "萨尔瓦多", region: "latin-america", drive_side: "lhd", currency: "USD", status: "active", source: "Dirección General de Aduanas (DGA) / US trade.gov", source_url: "https://www.trade.gov/country-commercial-guides/el-salvador-import-tariffs", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Nepal (RHD, no universal age cap + 20yr operation ban, EV 20% flat duty + 13% VAT) =====
  { rule_id: "np-drive-side", country_id: "nepal", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Nepal drives on the left and registers right-hand-drive (RHD) vehicles; left-hand-drive vehicles are generally not permitted for registration. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / Park(ing) Day (Nepal import guide)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "np-age-limit", country_id: "nepal", category: "vehicle_age", title: "No universal age cap; 20-year operation ban (EV 30-year)", rule_text: "Nepal currently has no universal restriction on the age of imported used vehicles, but a 2015 gazette bans the operation of vehicles older than 20 years (extended to 30 years for EVs in 2017). A 2024/25 proposal would restrict import permits to vehicles under one year old by VIN. Verify current import-age rules with the Department of Customs.", effective_date: null, last_checked: D, source: "New Business Age / myRepublica (Nepal age-rule reporting)", source_url: "https://www.newbusinessage.com/news/44302/nepal-moves-to-ban-import-of-vehicles-over-one-year-old-to-regulate-auto-market/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with the Department of Customs before purchase." },
  { rule_id: "np-import-process", country_id: "nepal", category: "import_eligibility", title: "Customs clearance + Euro 6 emission standard", rule_text: "Vehicle imports clear through the Nepal National Single Window (NNSW); imported vehicles must meet emission standards (Euro 6 cited by importer guides). Nepal is landlocked — vehicles arrive via Indian ports (Kolkata/Vizag) or overland via the Tatopani/Rasuwagadhi border with China.", effective_date: null, last_checked: D, source: "Nepal National Single Window / Motar Nepal (import guide)", source_url: "https://nnsw.gov.np/trade/customs/tariff/search", confidence: "medium", needs_review: true, notes: "Landlocked — Kolkata/Vizag transit or China overland. Verify document set with the Department of Customs." },
  { rule_id: "np-ev-policy", country_id: "nepal", category: "ev_policy", title: "EV flat 20% customs duty (FY 2083/84)", rule_text: "The FY 2083/84 (2026/27) Finance Bill scrapped Nepal's kW-based EV tax. Imported passenger EVs now pay a flat 20% customs duty, with the old excise duty replaced by a Clean Infrastructure Investment Fee (CIIF) on CIF value, plus a 5% road-construction fee and 13% VAT. Confirm current EV duty with the Department of Customs.", effective_date: "2026-05-29", last_checked: D, source: "Nepal Automart (EV tax) / TechLekh (FY 2081/82)", source_url: "https://nepalautomart.com/ev-tax", confidence: "medium", needs_review: true, notes: "EV 20% flat duty replaces the kW-based schedule — verify current rates with customs." },

  // ===== Zambia (RHD, no legal age limit + 20% surtax >5yr, specific duty + carbon surtax, 16% VAT) =====
  { rule_id: "zm-drive-side", country_id: "zambia", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Zambia drives on the left and accepts only right-hand-drive (RHD) vehicles. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "japan-carrier.com (Zambia import regulations) / Left- and right-hand traffic (Wikipedia)", source_url: "https://www.japan-carrier.com/regulations/zambia?lang=en", confidence: "high", needs_review: false },
  { rule_id: "zm-age-limit", country_id: "zambia", category: "vehicle_age", title: "No legal age limit; 20% surtax over 5 years old", rule_text: "Zambia has no legal age limit on imported used vehicles, but a 20% motor-vehicle surtax applies to vehicles over 5 years old. Duty is age-banded by the ZRA specific-duty schedule. Confirm current surtax with ZRA before sourcing older stock.", effective_date: null, last_checked: D, source: "japan-carrier.com / One Roof Autos (Zambia import guides)", source_url: "https://www.japan-carrier.com/regulations/zambia?lang=en", confidence: "medium", needs_review: true, notes: "No age ban, but 20% surtax >5 years — verify with ZRA." },
  { rule_id: "zm-import-process", country_id: "zambia", category: "import_eligibility", title: "JEVIC / Bureau Veritas pre-inspection + ZRA specific duty", rule_text: "Pre-inspection by JEVIC or Bureau Veritas is mandatory for used vehicles entering Zambia. Zambia is landlocked — vehicles transit via Durban (South Africa) or Dar es Salaam (Tanzania) and clear at a ZRA border post. Duty is assessed on the ZRA specific-duty schedule (flat Kwacha by engine size and age), not a simple percentage.", effective_date: null, last_checked: D, source: "japan-carrier.com / KMC Japan (Zambia import guides)", source_url: "https://kmcjapan.co.jp/export-to/zambia", confidence: "medium", needs_review: true, notes: "JEVIC/BV pre-inspection + Durban/Dar transit. Verify document set with ZRA." },
  { rule_id: "zm-ev-policy", country_id: "zambia", category: "ev_policy", title: "Hybrid excise 15%; EV treatment not separately documented", rule_text: "Zambia applies a reduced 15% excise duty to hybrids; a separate EV import-duty relief was not confirmed in the sources reviewed, and EVs are assessed under the ZRA specific-duty schedule. Confirm current EV/hybrid treatment with ZRA.", effective_date: null, last_checked: D, source: "Zambia Duty Calculator (2026 ZRA rates)", source_url: "https://www.zambiadutycalculator.com/", confidence: "low", needs_review: true, notes: "Hybrid excise 15%; EV treatment not documented — verify with ZRA." },

  // ===== Laos (LHD, 5-year age limit removed 2025, gas-car import ban, 40-65% duty stack) =====
  { rule_id: "la-drive-side", country_id: "laos", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Laos drives on the right and registers left-hand-drive (LHD) vehicles. A China-market LHD unit imports directly without conversion.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "la-age-limit", country_id: "laos", category: "vehicle_age", title: "5-year age limit removed (2025)", rule_text: "Laos removed its strict 5-year age limit on imported used vehicles in 2025, opening a window for 2018–2020 model-year cars. Confirm the current age rule with the Lao PDR Ministry of Industry and Commerce before sourcing stock.", effective_date: null, last_checked: D, source: "uCars (Laos Used Car Import Policy 2025)", source_url: "https://blog.ucarsea.com/laos-used-car-import-policy-2025/", confidence: "medium", needs_review: true, notes: "5-year limit removed in 2025 — confirm current rule with the Ministry of Industry and Commerce." },
  { rule_id: "la-import-process", country_id: "laos", category: "import_eligibility", title: "Automatic import licensing + duty by type/age/engine", rule_text: "Car imports are subject to an automatic import-licensing regime for statistical/monitoring purposes (Decision on Procedures for Car Import and Distribution). Duties are assessed on vehicle type, age and engine size. Laos is landlocked — vehicles arrive via Thai ports (Laem Chabang) or overland via the China–Laos border.", effective_date: null, last_checked: D, source: "Lao PDR Trade Portal (Decision 74) / Qualitex Trading", source_url: "https://www.laotradeportal.gov.la/en-gb/site/display/74", confidence: "medium", needs_review: true, notes: "Automatic import licence + duty by type/age/engine. Verify with the Ministry of Industry and Commerce." },
  { rule_id: "la-ev-policy", country_id: "laos", category: "ev_policy", title: "Gas/diesel passenger-import ban (Jun 2024–2026); EV incentives", rule_text: "From 1 June 2024 Laos suspended imports of new gasoline- and diesel-powered passenger vehicles (until end-2026), so virtually all newly imported passenger vehicles must be fully electric. The government offers EV tax incentives and imposes no import restrictions on EVs. Confirm current scope with the Ministry of Industry and Commerce.", effective_date: "2024-06-01", last_checked: D, source: "US ITA (Laos Automotive Sector) / eco-business", source_url: "https://www.trade.gov/country-commercial-guides/laos-automotive-sector", confidence: "medium", needs_review: true, notes: "Gas-car import ban + EV incentives — verify current scope before trading." },

  // ===== Cambodia (LHD, no hard age cap, EV 0% / PHEV 7% / ICE 35% + 10% VAT) =====
  { rule_id: "kh-drive-side", country_id: "cambodia", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Cambodia registers only left-hand-drive (LHD) vehicles; right-hand-drive imports face restrictions. China — a pure LHD market — is a natural sourcing base. A China-market LHD unit imports directly without conversion.", effective_date: null, last_checked: D, source: "uCars (Cambodia guide) / Qualitex Trading", source_url: "https://ucarsea.com/cambodia-used-car-import-guide/", confidence: "high", needs_review: false },
  { rule_id: "kh-age-limit", country_id: "cambodia", category: "vehicle_age", title: "No hard age cap (as of 2026)", rule_text: "Cambodia has no hard used-vehicle age cap as of 2026; proposals to legislate a strict age limit (2024, 2025) were not passed. Vehicles manufactured before 2000 are discouraged due to stricter inspection requirements. Confirm current rule with the GDCE.", effective_date: null, last_checked: D, source: "uCars (Cambodia Used Car Import Guide 2026)", source_url: "https://ucarsea.com/cambodia-used-car-import-guide/", confidence: "medium", needs_review: true, notes: "No hard cap today, but age-limit proposals recur — verify with GDCE." },
  { rule_id: "kh-import-process", country_id: "cambodia", category: "import_eligibility", title: "Euro II emission minimum + Sihanoukville clearance", rule_text: "Imported used vehicles must comply with at least Euro II emission standards for inspection. The main seaport is Sihanoukville (Sihanoukville Autonomous Port). Standard export documents plus GDCE customs declaration are required.", effective_date: null, last_checked: D, source: "Qualitex Trading (Cambodia import regulations)", source_url: "https://www.qualitextrading.com/import-regulations/cambodia", confidence: "medium", needs_review: true, notes: "Euro II minimum + Sihanoukville clearance. Verify document set with GDCE." },
  { rule_id: "kh-ev-policy", country_id: "cambodia", category: "ev_policy", title: "EV 0% duty / PHEV 7% (from Jan 2026)", rule_text: "Effective 1 January 2026 Cambodia cut customs duty on fully electric passenger vehicles and core EV components from 35% to 0%, and PHEV duty from 35% to 7%. ICE passenger vehicles remain at 35% duty plus 10% VAT. Confirm current rates with GDCE.", effective_date: "2026-01-01", last_checked: D, source: "DFDL / YiJie Auto Sales (2026 Cambodia tariff changes)", source_url: "https://www.dfdl.com/insights/legal-and-tax-updates/cambodia-revised-customs-duty-and-tax-rates-on-certain-goods-effective-1-january-2026/", confidence: "high", needs_review: true, notes: "EV 0% / PHEV 7% / ICE 35% — verify current rates with GDCE." },

  // ===== Honduras (LHD, 10-year age limit, DAI 5-20% + 15% ISV + ecotasa) =====
  { rule_id: "hn-drive-side", country_id: "honduras", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Honduras drives on the right and registers left-hand-drive (LHD) vehicles; imports of right-hand-drive vehicles are prohibited. A China-market LHD unit imports directly without conversion.", effective_date: null, last_checked: D, source: "US trade.gov (Honduras Prohibited & Restricted Imports)", source_url: "https://www.trade.gov/country-commercial-guides/honduras-prohibited-restricted-imports", confidence: "high", needs_review: false },
  { rule_id: "hn-age-limit", country_id: "honduras", category: "vehicle_age", title: "10-year age limit (Financial Balance & Social Protection Act)", rule_text: "Under Honduras' Financial Balance and Social Protection Act, imports of motor vehicles over ten years old are prohibited (except classic collectible cars), and passenger buses over thirteen years are prohibited. Some sources cite a 7-year limit — use the more conservative figure and confirm with a licensed customs broker or the DEI.", effective_date: null, last_checked: D, source: "US trade.gov (Honduras Prohibited & Restricted Imports)", source_url: "https://www.trade.gov/country-commercial-guides/honduras-prohibited-restricted-imports", confidence: "high", needs_review: true, notes: "10 years (some sources cite 7) — verify with DEI before sourcing stock." },
  { rule_id: "hn-import-process", country_id: "honduras", category: "import_eligibility", title: "DAI duty + 15% ISV + ecotasa environmental fee", rule_text: "Landed cost is set by three lines: the DAI import duty (5–20% by vehicle type under the Central American SAC/CET), the 15% ISV sales tax, and the ecotasa environmental fee banded by vehicle value. The main port is Puerto Cortés. Confirm the current stack with the Dirección Ejecutiva de Ingresos (DEI).", effective_date: null, last_checked: D, source: "Seaway Export (Honduras import taxes)", source_url: "https://www.seawayexport.com/destinations/shipping-to-honduras", confidence: "medium", needs_review: true, notes: "DAI 5-20% + ISV 15% + ecotasa. Verify with DEI." },
  { rule_id: "hn-ev-policy", country_id: "honduras", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was confirmed for Honduras in the sources reviewed; EVs follow the standard DAI + 15% ISV + ecotasa stack. Confirm EV treatment with the DEI.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with DEI." },

  // ===== El Salvador (LHD, 8-year age limit (15 for trucks/SUVs), 25-30% duty + 13% VAT) =====
  { rule_id: "sv-drive-side", country_id: "el-salvador", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "El Salvador drives on the right and registers left-hand-drive (LHD) vehicles. A China-market LHD unit imports directly without conversion.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "sv-age-limit", country_id: "el-salvador", category: "vehicle_age", title: "8-year age limit (15 years for trucks/SUVs)", rule_text: "El Salvador limits used passenger-car imports to a maximum of 8 years old; trucks and SUVs are limited to 15 years. Vehicles older than these cut-offs may be restricted unless they qualify for an exception (e.g. classic cars). Confirm current limits with the DGA.", effective_date: null, last_checked: D, source: "MGR Transports (El Salvador import regulations)", source_url: "https://www.mgrautotransport.com/el-salvador", confidence: "medium", needs_review: true, notes: "8 years (passenger) / 15 years (trucks/SUVs) — verify with DGA." },
  { rule_id: "sv-import-process", country_id: "el-salvador", category: "import_eligibility", title: "DUCA clearance + 25-30% duty + 13% VAT", rule_text: "Imports clear through the Dirección General de Aduanas (DGA) under the DUCA (Central American single customs declaration). Duty ranges 25–30% of CIF plus 13% VAT (IVA). The main port is Acajutla, reached via Panama transshipment or a Guatemalan/Honduran port plus truck.", effective_date: null, last_checked: D, source: "RoRoFromUSA / InterWF (El Salvador shipping guides)", source_url: "https://www.rorofromusa.com/car-shipping-to-el-salvador/", confidence: "medium", needs_review: true, notes: "DUCA + 25-30% duty + 13% VAT. Verify with DGA." },
  { rule_id: "sv-ev-policy", country_id: "el-salvador", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty relief was confirmed for El Salvador in the sources reviewed; EVs follow the standard 25–30% duty plus 13% VAT stack. Confirm EV treatment with the DGA.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with DGA." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  // Nepal
  { taxrule_id: "np-duty", country_id: "nepal", tax_type: "import_duty", label: "Import duty (petrol/diesel)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "KharchaPatra (Nepal car import tax)", source_url: "https://kharchapatra.com/blog/car-import-tax-nepal", confidence: "medium", needs_review: true, notes: "Customs + steeply progressive excise by engine size; total tax stack 200–317% of landed cost. Verify with the Department of Customs.", value_min: 200, value_max: 317 },
  { taxrule_id: "np-vat", country_id: "nepal", tax_type: "vat", label: "VAT", rate_pct: 13, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Car360 Nepal (Nepal car import tax rates 2026)", source_url: "https://car360nepal.com/nepal-car-import-tax-rates-2026-what-you-need-to-know-2/", confidence: "medium", needs_review: false },
  { taxrule_id: "np-ev-duty", country_id: "nepal", tax_type: "import_duty", label: "Import duty (electric vehicles, flat)", rate_pct: 20, basis: "CIF value", effective_date: "2026-05-29", last_checked: D, source: "Nepal Automart (EV tax FY 2083/84)", source_url: "https://nepalautomart.com/ev-tax", confidence: "medium", needs_review: true, notes: "Flat 20% EV customs duty replaces the kW-based schedule; + CIIF + 5% road fee + 13% VAT. Verify with the Department of Customs." },
  // Zambia
  { taxrule_id: "zm-duty", country_id: "zambia", tax_type: "import_duty", label: "Import duty (newer vehicles, ad valorem)", rate_pct: 25, basis: "CIF value (VDP)", effective_date: null, last_checked: D, source: "Levy Legal (Zambia import duty)", source_url: "https://www.levylegal.ai/answers/how-much-is-import-duty-on-a-car-in-zambia", confidence: "medium", needs_review: true, notes: "Newer (<2yr) vehicles: 25% customs + 30% excise + 16% VAT. Older (2+yr) use the ZRA specific-duty (flat Kwacha) schedule + carbon emission surtax. Verify with ZRA." },
  { taxrule_id: "zm-excise", country_id: "zambia", tax_type: "excise", label: "Excise duty", rate_pct: 30, basis: "CIF value (VDP)", effective_date: null, last_checked: D, source: "Levy Legal (Zambia import duty)", source_url: "https://www.levylegal.ai/answers/how-much-is-import-duty-on-a-car-in-zambia", confidence: "medium", needs_review: true, notes: "30% excise for newer vehicles; hybrids reduced to 15%. Verify with ZRA." },
  { taxrule_id: "zm-vat", country_id: "zambia", tax_type: "vat", label: "VAT", rate_pct: 16, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Levy Legal (Zambia import duty)", source_url: "https://www.levylegal.ai/answers/how-much-is-import-duty-on-a-car-in-zambia", confidence: "medium", needs_review: false },
  // Laos
  { taxrule_id: "la-duty", country_id: "laos", tax_type: "import_duty", label: "Import duty + excise + VAT (combined)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "uCars (Laos Used Car Import Policy 2025)", source_url: "https://blog.ucarsea.com/laos-used-car-import-policy-2025/", confidence: "medium", needs_review: true, notes: "Total tax burden 40–65% of CIF for a typical sedan depending on engine displacement (import duty + excise + VAT). Verify with the Lao PDR Customs Department.", value_min: 40, value_max: 65 },
  { taxrule_id: "la-vat", country_id: "laos", tax_type: "vat", label: "VAT", rate_pct: 10, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Washin Auto (Laos import guide)", source_url: "https://www.washinauto.com/import-guide?country=Laos", confidence: "low", needs_review: true, notes: "10% VAT (standard Laos rate) — verify with the Lao PDR Customs Department." },
  { taxrule_id: "la-ev-duty", country_id: "laos", tax_type: "import_duty", label: "Import duty (electric vehicles, incentivized)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "US ITA (Laos Automotive Sector)", source_url: "https://www.trade.gov/country-commercial-guides/laos-automotive-sector", confidence: "low", needs_review: true, notes: "EV tax incentives (reduced/exempt) + no import restrictions on EVs. Verify the current EV rate with the Ministry of Industry and Commerce." },
  // Cambodia
  { taxrule_id: "kh-duty", country_id: "cambodia", tax_type: "import_duty", label: "Import duty (ICE passenger vehicles)", rate_pct: 35, basis: "CIF value", effective_date: null, last_checked: D, source: "RidoMart / YiJie Auto Sales (Cambodia duties)", source_url: "https://ridomart.com/markets/cambodia", confidence: "high", needs_review: true, notes: "35% for ICE passenger cars. Verify with GDCE." },
  { taxrule_id: "kh-vat", country_id: "cambodia", tax_type: "vat", label: "VAT", rate_pct: 10, basis: "CIF + duty", effective_date: null, last_checked: D, source: "RidoMart (Cambodia import guide)", source_url: "https://ridomart.com/markets/cambodia", confidence: "medium", needs_review: false },
  { taxrule_id: "kh-ev-duty", country_id: "cambodia", tax_type: "import_duty", label: "Import duty (electric vehicles)", rate_pct: 0, basis: "CIF value", effective_date: "2026-01-01", last_checked: D, source: "DFDL (Cambodia 2026 tariff reductions)", source_url: "https://www.dfdl.com/insights/legal-and-tax-updates/cambodia-revised-customs-duty-and-tax-rates-on-certain-goods-effective-1-january-2026/", confidence: "high", needs_review: true, notes: "0% duty for fully electric passenger vehicles from 1 Jan 2026. Verify with GDCE." },
  { taxrule_id: "kh-phev-duty", country_id: "cambodia", tax_type: "import_duty", label: "Import duty (plug-in hybrids)", rate_pct: 7, basis: "CIF value", effective_date: "2026-01-01", last_checked: D, source: "YiJie Auto Sales (2026 Cambodia tariff changes)", source_url: "https://www.yijieautosales.com/news/en/2026-Cambodia-Import-Tariff-Changes-for-EV-PHEV-Auto-Parts-Full-Guide-for-Global-Importers.html", confidence: "high", needs_review: true, notes: "7% duty for PHEVs from 1 Jan 2026. Verify with GDCE." },
  // Honduras
  { taxrule_id: "hn-duty", country_id: "honduras", tax_type: "import_duty", label: "Import duty (DAI)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Seaway Export (Honduras import taxes)", source_url: "https://www.seawayexport.com/destinations/shipping-to-honduras", confidence: "medium", needs_review: true, notes: "DAI 5–20% by vehicle type (Central American SAC/CET). Verify with DEI.", value_min: 5, value_max: 20 },
  { taxrule_id: "hn-isv", country_id: "honduras", tax_type: "vat", label: "ISV (sales tax)", rate_pct: 15, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Seaway Export (Honduras import taxes)", source_url: "https://www.seawayexport.com/destinations/shipping-to-honduras", confidence: "medium", needs_review: false },
  { taxrule_id: "hn-ecotasa", country_id: "honduras", tax_type: "other", label: "Ecotasa (environmental fee)", rate_pct: null, basis: "Vehicle value (banded)", effective_date: null, last_checked: D, source: "Seaway Export (Honduras import taxes)", source_url: "https://www.seawayexport.com/destinations/shipping-to-honduras", confidence: "low", needs_review: true, notes: "Environmental fee banded by vehicle value. Verify with DEI." },
  // El Salvador
  { taxrule_id: "sv-duty", country_id: "el-salvador", tax_type: "import_duty", label: "Import duty", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "RoRoFromUSA (El Salvador car shipping)", source_url: "https://www.rorofromusa.com/car-shipping-to-el-salvador/", confidence: "medium", needs_review: true, notes: "25–30% of CIF. Verify with DGA.", value_min: 25, value_max: 30 },
  { taxrule_id: "sv-vat", country_id: "el-salvador", tax_type: "vat", label: "IVA (VAT)", rate_pct: 13, basis: "CIF + duty", effective_date: null, last_checked: D, source: "InterWF (El Salvador customs guide)", source_url: "https://interwf.com/blog/shipping-to-el-salvador/", confidence: "medium", needs_review: false },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "np-kathmandu", name: "Kathmandu (via Kolkata/Vizag transit or China overland)", country_id: "nepal", type: "destination", note: "Landlocked — via Kolkata/Vizag (India) ports or Tatopani/Rasuwagadhi border from China" },
  { port_id: "zm-lusaka", name: "Lusaka (via Durban/Dar es Salaam transit)", country_id: "zambia", type: "destination", note: "Landlocked — transit via Durban (South Africa) or Dar es Salaam (Tanzania); ZRA border post" },
  { port_id: "la-vientiane", name: "Vientiane (via Laem Chabang transit or China border)", country_id: "laos", type: "destination", note: "Landlocked — via Laem Chabang (Thailand) or China–Laos overland/border" },
  { port_id: "kh-sihanoukville", name: "Sihanoukville (Autonomous Port)", country_id: "cambodia", type: "destination", note: null },
  { port_id: "hn-puerto-cortes", name: "Puerto Cortés", country_id: "honduras", type: "destination", note: null },
  { port_id: "sv-acajutla", name: "Acajutla", country_id: "el-salvador", type: "destination", note: "No Caribbean coast — via Panama transshipment or Guatemalan/Honduran port + truck" },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-np-kathmandu", origin_port_id: "cn-shanghai", destination_port_id: "np-kathmandu", est_days_min: 14, est_days_max: 24, shipping_method: "container", source: "Industry route estimates (sea to Kolkata/Vizag + road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-zm-lusaka", origin_port_id: "cn-guangzhou", destination_port_id: "zm-lusaka", est_days_min: 26, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates (sea to Durban/Dar es Salaam + road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-la-vientiane", origin_port_id: "cn-guangzhou", destination_port_id: "la-vientiane", est_days_min: 8, est_days_max: 16, shipping_method: "container", source: "Industry route estimates (sea to Laem Chabang + road, or China overland)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-kh-sihanoukville", origin_port_id: "cn-guangzhou", destination_port_id: "kh-sihanoukville", est_days_min: 5, est_days_max: 10, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-hn-puerto-cortes", origin_port_id: "cn-shanghai", destination_port_id: "hn-puerto-cortes", est_days_min: 30, est_days_max: 42, shipping_method: "roro", source: "Industry route estimates (via Panama transshipment)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-sv-acajutla", origin_port_id: "cn-shanghai", destination_port_id: "sv-acajutla", est_days_min: 30, est_days_max: 42, shipping_method: "roro", source: "Industry route estimates (via Panama transshipment)", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

console.log("countries:", countries.countries.length, "| rules:", importrules.rules.length, "| taxes:", taxrules.taxrules.length, "| ports:", ports.ports.length, "| routes:", routes.routes.length);
