// Batch: market-countries — add 6 high-commercial-value countries + data layer + Vehicle×Market relations.
// Countries: South Africa (RHD), Egypt (LHD), Jordan (LHD), Pakistan (RHD), Bangladesh (RHD), Chile (LHD).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "south-africa", name: "South Africa", name_zh: "南非", region: "africa", drive_side: "rhd", currency: "ZAR", status: "active", source: "South African Government (gov.za)", source_url: "https://www.gov.za/services/services-organisations/import/importing-second-hand-or-used-vehicle", source_date: D, confidence: "high" },
  { country_id: "egypt", name: "Egypt", name_zh: "埃及", region: "africa", drive_side: "lhd", currency: "EGP", status: "active", source: "Egyptian Customs Authority (public record)", source_url: "https://www.trade.gov/country-commercial-guides/egypt-import-tariffs", source_date: D, confidence: "high" },
  { country_id: "jordan", name: "Jordan", name_zh: "约旦", region: "middle-east", drive_side: "lhd", currency: "JOD", status: "active", source: "Jordan Customs / Jordan Times (official reporting)", source_url: "https://www.jordantimes.com/news/local/cabinet-overhauls-vehicle-import-rules-slashes-taxes-bans-damaged-car-imports", source_date: D, confidence: "high" },
  { country_id: "pakistan", name: "Pakistan", name_zh: "巴基斯坦", region: "south-asia", drive_side: "rhd", currency: "PKR", status: "active", source: "Federal Board of Revenue (FBR)", source_url: "https://www.fbr.gov.pk/vehicles/51149/131187", source_date: D, confidence: "high" },
  { country_id: "bangladesh", name: "Bangladesh", name_zh: "孟加拉国", region: "south-asia", drive_side: "rhd", currency: "BDT", status: "active", source: "National Board of Revenue (NBR)", source_url: "https://bangladeshcustoms.gov.bd/", source_date: D, confidence: "high" },
  { country_id: "chile", name: "Chile", name_zh: "智利", region: "latin-america", drive_side: "lhd", currency: "CLP", status: "active", source: "Servicio Nacional de Aduanas (Chile Customs)", source_url: "https://www.aduana.cl/importacion-de-vehiculos/aduana/2017-11-22/101502.html", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // South Africa
  { rule_id: "za-drive-side", country_id: "south-africa", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "South Africa drives on the left and registers right-hand-drive (RHD) vehicles. Left-hand-drive vehicles are generally not registrable for private use.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic", confidence: "high", needs_review: false },
  { rule_id: "za-import-permit", country_id: "south-africa", category: "import_eligibility", title: "ITAC import permit required", rule_text: "Used/second-hand vehicles may only be imported with an International Trade Administration Commission (ITAC) import permit. Permits are restricted mainly to returning South African nationals, permanent-residence immigrants, racing cars, vintage, specially designed and inherited vehicles.", effective_date: null, last_checked: D, source: "South African Government (gov.za)", source_url: "https://www.gov.za/services/services-organisations/import/importing-second-hand-or-used-vehicle", confidence: "high", needs_review: false },
  { rule_id: "za-nrcs-loa", country_id: "south-africa", category: "registration", title: "NRCS Letter of Authority + Interpol clearance", rule_text: "SARS requires, for a second-hand vehicle import to be legal: customs clearance documents, a Letter of Authority from the National Regulator for Compulsory Specifications (NRCS), an ITAC import permit, and an Interpol clearance certificate.", effective_date: null, last_checked: D, source: "South African Revenue Service (SARS)", source_url: "https://www.sars.gov.za/media-release/importation-of-a-second-hand-vehicle/", confidence: "high", needs_review: false },
  { rule_id: "za-age-limit", country_id: "south-africa", category: "vehicle_age", title: "No fixed age limit (restricted categories)", rule_text: "South Africa has no hard age cut-off for used vehicles, but imports are restricted to defined permit categories (returning residents, immigrants, special-purpose vehicles). Confirm current ITAC permit eligibility before sourcing stock.", effective_date: null, last_checked: D, source: "South African Government (gov.za) / ITAC", source_url: "https://www.gov.za/services/services-organisations/import/importing-second-hand-or-used-vehicle", confidence: "medium", needs_review: true, notes: "Permit categories are restrictive — verify eligibility with ITAC before purchase." },
  { rule_id: "za-ev-duty", country_id: "south-africa", category: "ev_policy", title: "EVs face 25% import duty (no relief)", rule_text: "Electric vehicles attract the same 25% passenger-vehicle import duty (higher than the 18% ICE rate in some classifications); there is no EV-specific import-duty relief in South Africa.", effective_date: null, last_checked: D, source: "SARS Tariff / JLog (HS Chapter 87)", source_url: "https://jlog.co.za/vehicles-auto-parts-hs-87-6/", confidence: "medium", needs_review: true, notes: "Confirm current HS 87 duty classification with SARS before purchase." },

  // Egypt
  { rule_id: "eg-drive-side", country_id: "egypt", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Egypt drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive vehicles are not registrable — typical RHD Japanese used cars cannot be imported or registered.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / AskJapanCars", source_url: "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic", confidence: "high", needs_review: false },
  { rule_id: "eg-age-limit", country_id: "egypt", category: "vehicle_age", title: "Used cars near-new (about 1 year); EVs up to 3 years", rule_text: "Egypt restricts used passenger-car imports to near-new units (about one year old), while electric vehicles up to three years old are permitted under the 2025 EV policy.", effective_date: null, last_checked: D, source: "Egyptian Customs / EV24.africa", source_url: "https://www.ev24.africa/egypt-ev-import-tax-changes-2025-what-car-buyers-need-to-know/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Egyptian Customs before purchase." },
  { rule_id: "eg-nafeza", country_id: "egypt", category: "import_eligibility", title: "NAFEZA single-window clearance", rule_text: "All vehicle shipments must clear through the NAFEZA single-window system; import licence, certificate of conformity and proof of payment via authorised banks are required.", effective_date: null, last_checked: D, source: "Egyptian Customs (NAFEZA)", source_url: "https://www.nafeza.gov.eg/en", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Egyptian Customs before purchase." },
  { rule_id: "eg-ev-policy", country_id: "egypt", category: "ev_policy", title: "EV import duty exemption (0%)", rule_text: "From 1 January 2025 Egypt exempts pure-electric vehicles (BEV, HS 8703.80) from customs duty (0%), with a progressive FOB-value deduction up to 50%. Individuals may import one EV every five years.", effective_date: "2025-01-01", last_checked: D, source: "Egyptian Ministry of Finance / EV24.africa", source_url: "https://www.ev24.africa/egypt-ev-import-tax-changes-2025-what-car-buyers-need-to-know/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Egyptian Customs before purchase." },

  // Jordan
  { rule_id: "jo-drive-side", country_id: "jordan", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Jordan drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic", confidence: "high", needs_review: false },
  { rule_id: "jo-ev-age", country_id: "jordan", category: "vehicle_age", title: "EV age cap of 3 years", rule_text: "Under rules effective 1 November 2025, electric vehicles more than three years old (including the year of customs clearance) may no longer be imported.", effective_date: "2025-11-01", last_checked: D, source: "Jordan Times (official reporting)", source_url: "https://www.jordantimes.com/news/local/cabinet-overhauls-vehicle-import-rules-slashes-taxes-bans-damaged-car-imports", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Jordan Customs before purchase." },
  { rule_id: "jo-salvage-ban", country_id: "jordan", category: "import_eligibility", title: "Salvage / damaged vehicles banned", rule_text: "Vehicles classified as salvage or junk — including fire-, flood-damaged or unrepairable units — may no longer be imported into Jordan.", effective_date: "2025-06-28", last_checked: D, source: "Jordan Times (official reporting)", source_url: "https://www.jordantimes.com/news/local/cabinet-overhauls-vehicle-import-rules-slashes-taxes-bans-damaged-car-imports", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Jordan Customs before purchase." },
  { rule_id: "jo-ev-policy", country_id: "jordan", category: "ev_policy", title: "EV special tax unified at 27%", rule_text: "Under the 2025 Special Tax Bylaw (announced 28 June 2025), special tax on electric vehicles is unified at 27% for all categories, versus 51% for petrol and 39% for hybrid vehicles.", effective_date: "2025-06-28", last_checked: D, source: "Jordan Times / HKTDC Research", source_url: "https://research.hktdc.com/en/article/MjA3NzE4NzM0OQ", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Jordan Customs before purchase." },

  // Pakistan
  { rule_id: "pk-drive-side", country_id: "pakistan", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Pakistan drives on the left and registers right-hand-drive (RHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic", confidence: "high", needs_review: false },
  { rule_id: "pk-age-limit", country_id: "pakistan", category: "vehicle_age", title: "Cars up to 3 years (personal schemes)", rule_text: "Under the Personal Baggage, Gift and Transfer of Residence schemes, used cars not older than 3 years and other vehicles not older than 5 years may be imported. The commercial-channel 5-year age cap was removed from 1 July 2026 (SRO 1065/2026).", effective_date: "2026-07-01", last_checked: D, source: "Federal Board of Revenue (FBR)", source_url: "https://www.fbr.gov.pk/vehicles/51149/131187", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with FBR before purchase." },
  { rule_id: "pk-import-schemes", country_id: "pakistan", category: "import_eligibility", title: "Personal Baggage / Gift / Transfer of Residence schemes", rule_text: "Used vehicles are imported by overseas Pakistanis under the Personal Baggage, Gift or Transfer of Residence schemes only; duty is a fixed US-dollar schedule by engine capacity (e.g. US$13,200 for 1001–1300cc).", effective_date: null, last_checked: D, source: "Federal Board of Revenue (FBR)", source_url: "https://www.fbr.gov.pk/vehicles/51149/131187", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with FBR before purchase." },
  { rule_id: "pk-ev-policy", country_id: "pakistan", category: "ev_policy", title: "EV duty concession (25% up to US$50k)", rule_text: "Electric 4-wheelers valued up to US$50,000 are taxed at 25% customs duty; hybrid electric vehicles up to 1800cc receive a 50% duty exemption (25% for 1800–2500cc).", effective_date: null, last_checked: D, source: "Federal Board of Revenue (FBR) / pkrevenue", source_url: "https://pkrevenue.com/pakistan-notifies-duty-rates-for-electric-vehicles-in-fy26/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with FBR before purchase." },

  // Bangladesh
  { rule_id: "bd-drive-side", country_id: "bangladesh", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Bangladesh drives on the left and registers right-hand-drive (RHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic", confidence: "high", needs_review: false },
  { rule_id: "bd-age-limit", country_id: "bangladesh", category: "vehicle_age", title: "Reconditioned-car age restrictions", rule_text: "Bangladesh imports reconditioned (used) vehicles under NBR rules with age and condition restrictions; duty is a compounding cascade of customs duty, supplementary duty, VAT, advance income tax and regulatory duty.", effective_date: null, last_checked: D, source: "National Board of Revenue (NBR)", source_url: "https://bangladeshcustoms.gov.bd/", confidence: "low", needs_review: true, notes: "Uncertain / changes frequently — verify with NBR before purchase." },
  { rule_id: "bd-import-inspection", country_id: "bangladesh", category: "import_eligibility", title: "Pre-export inspection required", rule_text: "Reconditioned vehicle imports require pre-export inspection and standard documentation (invoice, bill of lading, certificate of origin).", effective_date: null, last_checked: D, source: "National Board of Revenue (NBR) / SUVHUB", source_url: "https://suvhub.com/import-rules/bangladesh", confidence: "low", needs_review: true, notes: "Uncertain / changes frequently — verify with NBR before purchase." },
  { rule_id: "bd-ev-policy", country_id: "bangladesh", category: "ev_policy", title: "PHEV / EV duty reduction", rule_text: "Bangladesh has proposed import-duty cuts on plug-in hybrid electric vehicles as part of its energy-efficiency strategy; EV/PHEV duty treatment is evolving.", effective_date: null, last_checked: D, source: "The Daily Star (NBR reporting)", source_url: "https://www.thedailystar.net/business/economy/news/import-duty-cuts-plug-hybrids-raise-concerns-4204676", confidence: "low", needs_review: true, notes: "Uncertain / changes frequently — verify with NBR before purchase." },

  // Chile
  { rule_id: "cl-drive-side", country_id: "chile", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Chile drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic", confidence: "high", needs_review: false },
  { rule_id: "cl-age-limit", country_id: "chile", category: "vehicle_age", title: "No import age limit", rule_text: "Chile has no import age limit for used vehicles, making it one of the most flexible markets in Latin America.", effective_date: null, last_checked: D, source: "Chile Customs (aduana.cl) / chinausedcar.net", source_url: "https://chinausedcar.net/blog/chile-used-car-import-guide", confidence: "medium", needs_review: true, notes: "Confirm current SNA customs rules before ordering used units." },
  { rule_id: "cl-import-docs", country_id: "chile", category: "import_eligibility", title: "RUT + standard documents", rule_text: "A Chilean tax identification number (RUT) is required; clearance needs the invoice, bill of lading, certificate of origin and export certificate.", effective_date: null, last_checked: D, source: "Chile Customs (aduana.cl) / Expat Focus", source_url: "https://www.expatfocus.com/chile/guide/chile-buying-or-importing-a-car", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Chile Customs before purchase." },
  { rule_id: "cl-ev-policy", country_id: "chile", category: "ev_policy", title: "No EV-specific duty relief", rule_text: "Chile applies a flat 6% ad valorem duty regardless of powertrain; no EV-specific import-duty relief is recorded. Chinese EVs have strong market presence.", effective_date: null, last_checked: D, source: "Chile Customs (aduana.cl)", source_url: "https://www.aduana.cl/importacion-de-vehiculos/aduana/2017-11-22/101502.html", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Chile Customs before purchase." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  { taxrule_id: "za-duty", country_id: "south-africa", tax_type: "import_duty", label: "Import duty (used passenger vehicles)", rate_pct: 25.0, basis: "Customs value (FOB)", effective_date: null, last_checked: D, source: "SARS Customs Tariff (HS Chapter 87)", source_url: "https://jlog.co.za/vehicles-auto-parts-hs-87-6/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with SARS before purchase." },
  { taxrule_id: "za-vat", country_id: "south-africa", tax_type: "vat", label: "VAT", rate_pct: 15.0, basis: "Customs value + duty", effective_date: null, last_checked: D, source: "South African Revenue Service (SARS)", source_url: "https://www.sars.gov.za/customs-and-excise/tariff/", confidence: "medium", needs_review: false },
  { taxrule_id: "eg-duty", country_id: "egypt", tax_type: "import_duty", label: "Import duty (used passenger vehicles, ≤1600cc)", rate_pct: 30.0, basis: "CIF value", effective_date: null, last_checked: D, source: "ITA / Egyptian Customs (Decree 419/2018)", source_url: "https://www.trade.gov/country-commercial-guides/egypt-import-tariffs", confidence: "medium", needs_review: true, notes: "Rate 30% up to 1600cc, 100% above 1600cc. Uncertain / changes frequently — verify with Egyptian Customs before purchase." },
  { taxrule_id: "eg-vat", country_id: "egypt", tax_type: "vat", label: "VAT", rate_pct: 14.0, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Egyptian Tax Authority", source_url: "https://www.trade.gov/country-commercial-guides/egypt-import-tariffs", confidence: "medium", needs_review: false },
  { taxrule_id: "eg-ev-duty", country_id: "egypt", tax_type: "import_duty", label: "Import duty (electric vehicles, exempt)", rate_pct: 0.0, basis: "CIF value", effective_date: "2025-01-01", last_checked: D, source: "Egyptian Ministry of Finance / EV24.africa", source_url: "https://www.ev24.africa/egypt-ev-import-tax-changes-2025-what-car-buyers-need-to-know/", confidence: "medium", needs_review: true, notes: "BEV HS 8703.80 only. Uncertain / changes frequently — verify with Egyptian Customs before purchase." },
  { taxrule_id: "jo-special-petrol", country_id: "jordan", tax_type: "excise", label: "Special tax (petrol vehicles)", rate_pct: 51.0, basis: "Vehicle value", effective_date: "2025-06-28", last_checked: D, source: "Jordan Special Tax Bylaw / HKTDC", source_url: "https://research.hktdc.com/en/article/MjA3NzE4NzM0OQ", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Jordan Customs before purchase." },
  { taxrule_id: "jo-special-hybrid", country_id: "jordan", tax_type: "excise", label: "Special tax (hybrid vehicles)", rate_pct: 39.0, basis: "Vehicle value", effective_date: "2025-06-28", last_checked: D, source: "Jordan Special Tax Bylaw / HKTDC", source_url: "https://research.hktdc.com/en/article/MjA3NzE4NzM0OQ", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Jordan Customs before purchase." },
  { taxrule_id: "jo-special-ev", country_id: "jordan", tax_type: "excise", label: "Special tax (electric vehicles)", rate_pct: 27.0, basis: "Vehicle value", effective_date: "2025-06-28", last_checked: D, source: "Jordan Special Tax Bylaw / HKTDC", source_url: "https://research.hktdc.com/en/article/MjA3NzE4NzM0OQ", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Jordan Customs before purchase." },
  { taxrule_id: "jo-gst", country_id: "jordan", tax_type: "vat", label: "GST", rate_pct: 16.0, basis: "Vehicle value + special tax", effective_date: null, last_checked: D, source: "Jordan Customs", source_url: "https://www.jordantimes.com/news/local/cabinet-overhauls-vehicle-import-rules-slashes-taxes-bans-damaged-car-imports", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Jordan Customs before purchase." },
  { taxrule_id: "pk-ev-duty", country_id: "pakistan", tax_type: "import_duty", label: "Import duty (electric vehicles ≤US$50k)", rate_pct: 25.0, basis: "CIF value", effective_date: null, last_checked: D, source: "Federal Board of Revenue (FBR)", source_url: "https://pkrevenue.com/pakistan-notifies-duty-rates-for-electric-vehicles-in-fy26/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with FBR before purchase." },
  { taxrule_id: "pk-rd-used", country_id: "pakistan", tax_type: "other", label: "Regulatory duty (commercial used imports)", rate_pct: 30.0, basis: "CIF value", effective_date: "2026-07-01", last_checked: D, source: "FBR SRO 1065(I)/2026", source_url: "https://www.providenceauto.co.uk/latest-news/pakistan-used-car-import-age-limit-removed-2026", confidence: "low", needs_review: true, notes: "Used-vehicle duty under personal schemes is a fixed US-dollar schedule; commercial channel adds 30% regulatory duty. Uncertain — verify with FBR." },
  { taxrule_id: "bd-duty", country_id: "bangladesh", tax_type: "import_duty", label: "Import duty (reconditioned vehicles, base CD)", rate_pct: 25.0, basis: "CIF value", effective_date: null, last_checked: D, source: "National Board of Revenue (NBR)", source_url: "https://bangladeshcustoms.gov.bd/", confidence: "low", needs_review: true, notes: "Compounding cascade: CD + supplementary duty + VAT + AIT + regulatory duty can multiply CIF several times. Uncertain — verify with NBR." },
  { taxrule_id: "bd-vat", country_id: "bangladesh", tax_type: "vat", label: "VAT", rate_pct: 15.0, basis: "CIF + duty + supplementary duty", effective_date: null, last_checked: D, source: "National Board of Revenue (NBR)", source_url: "https://bangladeshcustoms.gov.bd/", confidence: "medium", needs_review: false },
  { taxrule_id: "cl-duty", country_id: "chile", tax_type: "import_duty", label: "Import duty (ad valorem)", rate_pct: 6.0, basis: "Customs value (aduanero)", effective_date: null, last_checked: D, source: "Servicio Nacional de Aduanas (aduana.cl)", source_url: "https://www.aduana.cl/importacion-de-vehiculos/aduana/2017-11-22/101502.html", confidence: "medium", needs_review: false },
  { taxrule_id: "cl-vat", country_id: "chile", tax_type: "vat", label: "VAT (IVA)", rate_pct: 19.0, basis: "Customs value + duty", effective_date: null, last_checked: D, source: "Servicio Nacional de Aduanas (aduana.cl)", source_url: "https://www.aduana.cl/importacion-de-vehiculos/aduana/2017-11-22/101502.html", confidence: "medium", needs_review: false },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "za-durban", name: "Durban", country_id: "south-africa", type: "destination", note: null },
  { port_id: "za-cape-town", name: "Cape Town", country_id: "south-africa", type: "destination", note: null },
  { port_id: "eg-alexandria", name: "Alexandria", country_id: "egypt", type: "destination", note: null },
  { port_id: "eg-port-said", name: "Port Said", country_id: "egypt", type: "destination", note: null },
  { port_id: "jo-aqaba", name: "Aqaba", country_id: "jordan", type: "destination", note: null },
  { port_id: "pk-karachi", name: "Karachi (Port Qasim)", country_id: "pakistan", type: "destination", note: null },
  { port_id: "bd-chittagong", name: "Chittagong", country_id: "bangladesh", type: "destination", note: null },
  { port_id: "cl-san-antonio", name: "San Antonio", country_id: "chile", type: "destination", note: null },
  { port_id: "cl-iquique", name: "Iquique (ZOFRI free trade zone)", country_id: "chile", type: "destination", note: "Free trade zone; re-export hub for Bolivia and northern Chile" },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-za-durban", origin_port_id: "cn-shanghai", destination_port_id: "za-durban", est_days_min: 18, est_days_max: 28, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-tianjin-to-eg-alexandria", origin_port_id: "cn-tianjin", destination_port_id: "eg-alexandria", est_days_min: 22, est_days_max: 34, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-jo-aqaba", origin_port_id: "cn-shanghai", destination_port_id: "jo-aqaba", est_days_min: 18, est_days_max: 28, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-pk-karachi", origin_port_id: "cn-shanghai", destination_port_id: "pk-karachi", est_days_min: 12, est_days_max: 20, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-bd-chittagong", origin_port_id: "cn-guangzhou", destination_port_id: "bd-chittagong", est_days_min: 10, est_days_max: 16, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-cl-san-antonio", origin_port_id: "cn-shanghai", destination_port_id: "cl-san-antonio", est_days_min: 30, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

console.log(`countries: ${countries.countries.length}, rules: ${importrules.rules.length}, taxes: ${taxrules.taxrules.length}, ports: ${ports.ports.length}, routes: ${routes.routes.length}`);
