// Batch: market-countries8 — add 6 high-commercial-value countries + data layer + Vehicle×Market relations.
// Countries: Lebanon (Middle East re-export hub), Ukraine (Europe large market),
//            Belarus (Europe EAEU gateway), Bolivia (Latin America), Costa Rica (Latin America),
//            Guatemala (Central America).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";
const GBTSRC = "https://en.wikipedia.org/wiki/GB/T_charging_standard";
const MODELS = "https://data.chinausedautohub.com/models/";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "lebanon", name: "Lebanon", name_zh: "黎巴嫩", region: "middle-east", drive_side: "lhd", currency: "LBP", status: "active", source: "Lebanese Customs / JapanCarTrade import guide", source_url: "https://blog.japanesecartrade.com/558-lebanon-import-regulation-for-japan-used-cars/", source_date: D, confidence: "high" },
  { country_id: "ukraine", name: "Ukraine", name_zh: "乌克兰", region: "europe", drive_side: "lhd", currency: "UAH", status: "active", source: "State Customs Service of Ukraine / Law No. 2612-VIII", source_url: "https://cargoline.com.ua/en/customs-clearance-cars/", source_date: D, confidence: "high" },
  { country_id: "belarus", name: "Belarus", name_zh: "白俄罗斯", region: "europe", drive_side: "lhd", currency: "BYN", status: "active", source: "State Customs Committee of Belarus / EAEU EEC Decision 107 / Carawon import guide", source_url: "https://carawon.com/en/import-to-belarus", source_date: D, confidence: "high" },
  { country_id: "bolivia", name: "Bolivia", name_zh: "玻利维亚", region: "latin-america", drive_side: "lhd", currency: "BOB", status: "active", source: "Aduana Nacional de Bolivia / US trade.gov (Bolivia trade barriers)", source_url: "https://www.privacyshield.gov/ps/article?id=Bolivia-Trade-Barriers", source_date: D, confidence: "high" },
  { country_id: "costa-rica", name: "Costa Rica", name_zh: "哥斯达黎加", region: "latin-america", drive_side: "lhd", currency: "CRC", status: "active", source: "Costa Rica Customs (Dirección General de Aduanas) / Law 9518 / trade.gov", source_url: "https://www.trade.gov/market-intelligence/costa-rica-electric-vehicles", source_date: D, confidence: "high" },
  { country_id: "guatemala", name: "Guatemala", name_zh: "危地马拉", region: "latin-america", drive_side: "lhd", currency: "GTQ", status: "active", source: "SAT (Superintendencia de Administración Tributaria) / West Coast Shipping guide", source_url: "https://www.wcshipping.com/blog/guatemala-vehicle-import-rules-2025-sat-regulations-vs-reality-guide", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Lebanon (LHD, 8-year age limit, diesel ban, 5M LBP flat / 50% duty + 10% VAT) =====
  { rule_id: "lb-drive-side", country_id: "lebanon", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Lebanon drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive vehicles are not registrable — a China-market LHD unit imports directly.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / JapanCarTrade", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "lb-age-limit", country_id: "lebanon", category: "vehicle_age", title: "8-year age limit", rule_text: "Lebanon prohibits the import of used vehicles older than eight years (from the year of manufacture). In 2026 this means roughly model-year 2018 and newer.", effective_date: null, last_checked: D, source: "JapanCarTrade / OneRoofAutos (Lebanon import guides)", source_url: "https://blog.japanesecartrade.com/558-lebanon-import-regulation-for-japan-used-cars/", confidence: "medium", needs_review: true, notes: "Uncertain / changes frequently — verify with Lebanese Customs before purchase." },
  { rule_id: "lb-diesel-ban", country_id: "lebanon", category: "import_eligibility", title: "Diesel used vehicles prohibited", rule_text: "Lebanon prohibits the import of used vehicles that use diesel fuel. Petrol, hybrid and electric powertrains are admissible.", effective_date: null, last_checked: D, source: "JapanCarTrade (Lebanon import guide)", source_url: "https://blog.japanesecartrade.com/558-lebanon-import-regulation-for-japan-used-cars/", confidence: "medium", needs_review: true, notes: "Diesel ban — verify current scope with Lebanese Customs." },
  { rule_id: "lb-docs", country_id: "lebanon", category: "import_eligibility", title: "Bill of lading, registration, title and invoice", rule_text: "Required documents include the original bill of lading (make, model, engine and chassis numbers, weight and colour), original vehicle registration, original certificate of title and a purchase/commercial invoice.", effective_date: null, last_checked: D, source: "JapanCarTrade (Lebanon import guide)", source_url: "https://blog.japanesecartrade.com/558-lebanon-import-regulation-for-japan-used-cars/", confidence: "medium", needs_review: true, notes: "Standard documentation — verify with Lebanese Customs." },
  { rule_id: "lb-ev-policy", country_id: "lebanon", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty exemption was confirmed for Lebanon in the sources reviewed; EVs follow the standard duty schedule (flat 5M LBP up to 20M LBP CIF, or 50% above). Confirm current EV treatment with Lebanese Customs.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with Lebanese Customs." },

  // ===== Ukraine (LHD, Euro-2 minimum, no hard age cap (proposed 20-year), 10% + excise + 20% VAT) =====
  { rule_id: "ua-drive-side", country_id: "ukraine", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Ukraine drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive vehicles are not registrable.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "ua-emission", country_id: "ukraine", category: "emission", title: "Euro-2 emission standard minimum", rule_text: "Imported passenger cars must meet the Euro-2 environmental standard or higher (Euro-2 was introduced in 1995). Vehicles from a state recognised by Ukraine as an occupier/aggressor are excluded.", effective_date: null, last_checked: D, source: "Law of Ukraine No. 2612-VIII / CARGO LINE", source_url: "https://cargoline.com.ua/en/customs-clearance-cars/", confidence: "medium", needs_review: true, notes: "Euro-2 minimum — verify current standard with the State Customs Service." },
  { rule_id: "ua-age-limit", country_id: "ukraine", category: "vehicle_age", title: "No hard age cap today; 20-year cap proposed", rule_text: "Ukraine has no firm vehicle-age cut-off at present (Euro-2 compliance is the binding gate), but a maximum import age of 20 years has been proposed. Confirm the current rule with the State Customs Service before sourcing older stock.", effective_date: null, last_checked: D, source: "Wandertours / Komersant (Ukraine age-restriction reporting)", source_url: "https://wah.ua/en/blog/210-age-restricted-cars-how-will-the-import-of-used-cars-into-ukraine-change", confidence: "low", needs_review: true, notes: "Proposed 20-year cap — not yet confirmed as law. Verify with the State Customs Service." },
  { rule_id: "ua-docs", country_id: "ukraine", category: "import_eligibility", title: "Certificate of Conformity + preliminary declaration", rule_text: "Clearance requires a Certificate of Conformity for an individually approved wheeled vehicle, a preliminary customs declaration with a financial guarantee of the customs payments, and standard documents (registration certificate, invoice, export declaration, payment receipt, passport and TIN).", effective_date: null, last_checked: D, source: "CARGO LINE (Ukraine customs clearance) / Law No. 2612-VIII", source_url: "https://cargoline.com.ua/en/customs-clearance-cars/", confidence: "medium", needs_review: true, notes: "Confirm the document set with the State Customs Service." },
  { rule_id: "ua-ev-policy", country_id: "ukraine", category: "ev_policy", title: "Full EV exemption ends 31 Dec 2025", rule_text: "Ukraine's full EV import exemptions (0% duty, 0% excise, 0% VAT) expired on 31 December 2025. From 2026 electric vehicles pay up to 10% import duty, an excise of €1 per kWh of battery capacity, and 20% VAT — erasing the previous EV cost advantage.", effective_date: "2025-12-31", last_checked: D, source: "Wandertours / eAuto.org.ua (Ukraine EV customs)", source_url: "https://wah.ua/en/blog/195-customs-clearance-of-electric-vehicles-new-rules-and-features", confidence: "medium", needs_review: true, notes: "EV exemption ended Dec 2025 — verify current EV treatment with the State Customs Service." },

  // ===== Belarus (LHD, no hard age ban, EAEU unified rate, EV duty-free quota) =====
  { rule_id: "by-drive-side", country_id: "belarus", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Belarus drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "by-age-limit", country_id: "belarus", category: "vehicle_age", title: "No hard age ban (rate scales with age)", rule_text: "Belarus has no hard vehicle-age cut-off for used imports; the individual unified customs rate scales up steeply with age and engine size (and a per-cc minimum applies).", effective_date: null, last_checked: D, source: "Carawon (Belarus import guide 2026)", source_url: "https://carawon.com/en/import-to-belarus", confidence: "medium", needs_review: true, notes: "No hard age ban — but older cars cost materially more in unified rate. Verify with the State Customs Committee." },
  { rule_id: "by-eaeu", country_id: "belarus", category: "import_eligibility", title: "EAEU member — single customs clearance", rule_text: "Belarus is an EAEU member. A vehicle cleared and registered in Belarus moves across the EAEU (Russia, Kazakhstan, Kyrgyzstan, Armenia) without re-paying customs duty. Russia still levies a recycling fee on EAEU-origin vehicles.", effective_date: null, last_checked: D, source: "Carawon (Belarus import guide 2026)", source_url: "https://carawon.com/en/import-to-belarus", confidence: "medium", needs_review: true, notes: "EAEU single-clearance advantage; Russia recycling fee applies on re-export. Verify with the State Customs Committee." },
  { rule_id: "by-ev-policy", country_id: "belarus", category: "ev_policy", title: "EV duty-free quota (20,000 units) + 0% EV VAT", rule_text: "Belarus keeps a 20,000-unit duty-free import quota for pure electric vehicles in 2026 (13,800 for companies, 6,200 for individuals). Individual pure-EV import VAT stays at 0% through 31 December 2028 (Decree No. 428). Hybrids are excluded and pay 15% duty + 20% VAT.", effective_date: "2026-01-01", last_checked: D, source: "Carawon (Belarus EV quota) / Decree No. 428", source_url: "https://carawon.com/en/import-to-belarus", confidence: "medium", needs_review: true, notes: "Quota is limited and resets annually; over 40% used by April 2026. Verify quota status with the State Customs Committee." },
  { rule_id: "by-landlocked", country_id: "belarus", category: "import_eligibility", title: "Landlocked — transit via Klaipėda/Riga or Brest", rule_text: "Belarus is landlocked. Vehicles arrive overland via Poland (Brest border) or through the Klaipėda (Lithuania) and Riga (Latvia) seaports, then by road to Minsk for customs clearance.", effective_date: null, last_checked: D, source: "Carawon (Belarus import guide 2026)", source_url: "https://carawon.com/en/import-to-belarus", confidence: "medium", needs_review: true, notes: "Transit routing is operational guidance — confirm with a forwarder." },

  // ===== Bolivia (LHD, strict ~1 model-year age rule, NANDINA + 14.94% IVA) =====
  { rule_id: "bo-drive-side", country_id: "bolivia", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Bolivia drives on the right and registers left-hand-drive (LHD) vehicles. Right-hand-drive vehicles are not registrable.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "bo-age-limit", country_id: "bolivia", category: "vehicle_age", title: "Very strict age rule (~1 model year)", rule_text: "Bolivia applies one of the region's strictest used-vehicle age rules: since December 2014 the maximum age for imported cars is one model year old (some sources cite up to two years). In 2026 this means only brand-new or current-model-year units qualify — a near-total bar to used imports.", effective_date: "2014-12-01", last_checked: D, source: "US trade.gov (Bolivia trade barriers) / Bolivian Customs", source_url: "https://www.privacyshield.gov/ps/article?id=Bolivia-Trade-Barriers", confidence: "medium", needs_review: true, notes: "Sources conflict (1 vs 2 years vs ~10 years). Verify the exact cut-off with Aduana Nacional before sourcing stock." },
  { rule_id: "bo-import-process", country_id: "bolivia", category: "import_eligibility", title: "NIT + licensed customs broker (Agente Despachante)", rule_text: "Bolivia is landlocked; vehicles transit via Iquique/Antofagasta (Chile) or Matarani/Ilo (Peru). Import requires a locally registered entity with NIT, and a licensed Agente Despachante is mandatory for all shipments above USD 1,000.", effective_date: null, last_checked: D, source: "CarraGlobe (Bolivia importer-of-record guide)", source_url: "https://carraglobe.com/importer-of-record-bolivia/", confidence: "medium", needs_review: true, notes: "Landlocked transit + mandatory broker — verify with Aduana Nacional." },
  { rule_id: "bo-ev-policy", country_id: "bolivia", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty exemption was confirmed for Bolivia in the sources reviewed; imports follow the NANDINA tariff plus an effective 14.94% IVA. Confirm EV treatment with Aduana Nacional.", effective_date: null, last_checked: D, source: "CarraGlobe (Bolivia import guide)", source_url: "https://carraglobe.com/importer-of-record-bolivia/", confidence: "low", needs_review: true, notes: "EV treatment not documented — verify with Aduana Nacional." },

  // ===== Costa Rica (LHD, no age limit but tiered duty, EV/hybrid zero import tax) =====
  { rule_id: "cr-drive-side", country_id: "costa-rica", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Costa Rica drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "cr-age-limit", country_id: "costa-rica", category: "vehicle_age", title: "No fixed age limit (duty rises with age)", rule_text: "Costa Rica has no fixed vehicle-age cut-off for used imports, but import tax rises sharply with age (52.29% ≤3 years, 63.91% at 4 years, 79.03% at 6+ years). Older vehicles also require more frequent RITEVE inspections.", effective_date: null, last_checked: D, source: "Vamos Rent A Car (Costa Rica import tax guide)", source_url: "https://vamosrentacar.com/ship-or-buy-import-taxes/", confidence: "medium", needs_review: true, notes: "No age ban — but age drives the duty tier. Verify with Costa Rica Customs." },
  { rule_id: "cr-riteve", country_id: "costa-rica", category: "import_eligibility", title: "RITEVE emissions/safety inspection", rule_text: "All imported vehicles must pass emissions and safety testing at RITEVE; vehicles over 10 years old require annual technical inspection (newer vehicles every two years).", effective_date: null, last_checked: D, source: "Vamos Rent A Car / US Embassy Costa Rica", source_url: "https://vamosrentacar.com/ship-or-buy-import-taxes/", confidence: "medium", needs_review: true, notes: "RITEVE inspection required — verify with Costa Rica Customs." },
  { rule_id: "cr-ev-policy", country_id: "costa-rica", category: "ev_policy", title: "EV zero import tax (Law 9518); hybrids partial", rule_text: "Costa Rica exempts fully electric vehicles from import tax, sales tax and consumption tax under Law 9518 (fully electric vehicles under US$30,000 historically exempt; hybrids do not receive the full exemption).", effective_date: null, last_checked: D, source: "US trade.gov (Costa Rica EVs) / Law 9518", source_url: "https://www.trade.gov/market-intelligence/costa-rica-electric-vehicles", confidence: "medium", needs_review: true, notes: "EV zero import tax; hybrid treatment partial — verify with Costa Rica Customs." },

  // ===== Guatemala (LHD, ~10-year age limit, DAI + 12% VAT + IPRIMA 20%) =====
  { rule_id: "gt-drive-side", country_id: "guatemala", category: "drive_side", title: "Left-hand drive (LHD) only", rule_text: "Guatemala drives on the right and registers left-hand-drive (LHD) vehicles.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "gt-age-limit", country_id: "guatemala", category: "vehicle_age", title: "~10-year age limit (cited inconsistently)", rule_text: "Sources cite a 10-year age limit (from date of manufacture) for used-vehicle imports into Guatemala, though the exact threshold is cited inconsistently and no definitive SAT regulation is publicly documented. Confirm with a Guatemalan customs broker.", effective_date: null, last_checked: D, source: "West Coast Shipping (Guatemala SAT vs reality guide)", source_url: "https://www.wcshipping.com/blog/guatemala-vehicle-import-rules-2025-sat-regulations-vs-reality-guide", confidence: "low", needs_review: true, notes: "Age limit cited inconsistently — verify with SAT / a licensed broker." },
  { rule_id: "gt-duty-stack", country_id: "guatemala", category: "import_eligibility", title: "DAI duty + 12% VAT + IPRIMA 20%", rule_text: "Guatemala applies the DAI import duty (0–15%, 0% under CAFTA-DR for US-built vehicles) plus 12% IVA, plus a first-registration IPRIMA tax of ~20% for vehicles carrying up to five people.", effective_date: null, last_checked: D, source: "West Coast Shipping / AB Group Shipping (Guatemala guides)", source_url: "https://www.wcshipping.com/blog/guatemala-vehicle-import-rules-2025-sat-regulations-vs-reality-guide", confidence: "low", needs_review: true, notes: "Layered DAI + IVA + IPRIMA; exact rates vary — verify with SAT." },
  { rule_id: "gt-ev-policy", country_id: "guatemala", category: "ev_policy", title: "No EV-specific import-duty relief recorded", rule_text: "No EV-specific import-duty exemption was confirmed for Guatemala in the sources reviewed; EVs are expected to follow the standard DAI + IVA + IPRIMA stack. Confirm EV treatment with SAT.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented for used imports — verify with SAT." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  // Lebanon
  { taxrule_id: "lb-duty", country_id: "lebanon", tax_type: "import_duty", label: "Import duty (flat 5M LBP ≤20M CIF; 50% above)", rate_pct: 50, basis: "CIF value", effective_date: null, last_checked: D, source: "JapanCarTrade (Lebanon import guide)", source_url: "https://blog.japanesecartrade.com/558-lebanon-import-regulation-for-japan-used-cars/", confidence: "medium", needs_review: true, notes: "Flat 5,000,000 LBP for CIF ≤20M LBP, otherwise 50% of CIF. Verify with Lebanese Customs." },
  { taxrule_id: "lb-vat", country_id: "lebanon", tax_type: "vat", label: "VAT", rate_pct: 10, basis: "CIF + duty", effective_date: null, last_checked: D, source: "JapanCarTrade (Lebanon import guide)", source_url: "https://blog.japanesecartrade.com/558-lebanon-import-regulation-for-japan-used-cars/", confidence: "medium", needs_review: false },
  // Ukraine
  { taxrule_id: "ua-duty", country_id: "ukraine", tax_type: "import_duty", label: "Import duty (passenger vehicles)", rate_pct: 10, basis: "Customs value", effective_date: null, last_checked: D, source: "eAuto.org.ua (Ukraine customs)", source_url: "https://eauto.org.ua/en/instrumenty/rozmytnennia", confidence: "medium", needs_review: true, notes: "10% of customs value. Verify with the State Customs Service." },
  { taxrule_id: "ua-excise", country_id: "ukraine", tax_type: "excise", label: "Excise tax (engine type, displacement and age formula)", rate_pct: null, basis: "Customs value (formula-based)", effective_date: null, last_checked: D, source: "eAuto.org.ua (Ukraine customs)", source_url: "https://eauto.org.ua/en/instrumenty/rozmytnennia", confidence: "medium", needs_review: true, notes: "Formula based on engine type, displacement and age — not a flat %. Verify with the State Customs Service." },
  { taxrule_id: "ua-vat", country_id: "ukraine", tax_type: "vat", label: "VAT", rate_pct: 20, basis: "Customs value + duty + excise", effective_date: null, last_checked: D, source: "eAuto.org.ua (Ukraine customs)", source_url: "https://eauto.org.ua/en/instrumenty/rozmytnennia", confidence: "medium", needs_review: false },
  { taxrule_id: "ua-ev-duty", country_id: "ukraine", tax_type: "import_duty", label: "Import duty (electric vehicles, exemption ended Dec 2025)", rate_pct: 0, basis: "Customs value", effective_date: "2025-12-31", last_checked: D, source: "Wandertours / eAuto.org.ua (Ukraine EV customs)", source_url: "https://wah.ua/en/blog/195-customs-clearance-of-electric-vehicles-new-rules-and-features", confidence: "medium", needs_review: true, notes: "0% duty + 0% excise + 0% VAT ended 31 Dec 2025; from 2026 EVs pay 10% duty + €1/kWh excise + 20% VAT. Verify with the State Customs Service." },
  // Belarus
  { taxrule_id: "by-duty", country_id: "belarus", tax_type: "import_duty", label: "Unified customs rate (individuals, VAT incl.)", rate_pct: null, basis: "Customs value (age/engine banded)", effective_date: null, last_checked: D, source: "Carawon / EEC Decision 107 (Belarus)", source_url: "https://carawon.com/en/import-to-belarus", confidence: "medium", needs_review: true, notes: "~48–54% unified rate for cars 1–3 years old (VAT + excise included); per-cc minimum. Companies pay CCT duty + 20% VAT. Verify with the State Customs Committee.", value_min: 48, value_max: 54 },
  { taxrule_id: "by-vat", country_id: "belarus", tax_type: "vat", label: "VAT (company imports)", rate_pct: 20, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Carawon (Belarus import guide)", source_url: "https://carawon.com/en/import-to-belarus", confidence: "medium", needs_review: false, notes: "Companies pay a separate 20% VAT; individuals pay an all-inclusive unified rate." },
  { taxrule_id: "by-ev-duty", country_id: "belarus", tax_type: "import_duty", label: "Import duty (pure EV, duty-free quota)", rate_pct: 0, basis: "Customs value", effective_date: "2026-01-01", last_checked: D, source: "Carawon / Decree No. 428 (Belarus EV quota)", source_url: "https://carawon.com/en/import-to-belarus", confidence: "medium", needs_review: true, notes: "0% duty under the 20,000-unit quota; individual EV VAT 0% through 31 Dec 2028. Hybrids pay 15% duty + 20% VAT. Verify quota status." },
  // Bolivia
  { taxrule_id: "bo-duty", country_id: "bolivia", tax_type: "import_duty", label: "Import duty (NANDINA tariff)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "CarraGlobe (Bolivia import guide)", source_url: "https://carraglobe.com/importer-of-record-bolivia/", confidence: "low", needs_review: true, notes: "NANDINA tariff schedule (rate varies by HS code). Verify with Aduana Nacional." },
  { taxrule_id: "bo-iva", country_id: "bolivia", tax_type: "vat", label: "IVA (effective rate)", rate_pct: 14.94, basis: "CIF + duty", effective_date: null, last_checked: D, source: "CarraGlobe (Bolivia import guide)", source_url: "https://carraglobe.com/importer-of-record-bolivia/", confidence: "low", needs_review: true, notes: "Effective IVA 14.94%. Verify with Aduana Nacional." },
  // Costa Rica
  { taxrule_id: "cr-duty", country_id: "costa-rica", tax_type: "import_duty", label: "Import tax (tiered by age)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Vamos Rent A Car (Costa Rica import tax)", source_url: "https://vamosrentacar.com/ship-or-buy-import-taxes/", confidence: "medium", needs_review: true, notes: "52.29% (≤3yr), 63.91% (4yr), 79.03% (6+yr) — bundles duty, selective consumption tax and VAT. Verify with Costa Rica Customs.", value_min: 52.29, value_max: 79.03 },
  { taxrule_id: "cr-ev-duty", country_id: "costa-rica", tax_type: "import_duty", label: "Import tax (electric vehicles, exempt)", rate_pct: 0, basis: "CIF value", effective_date: null, last_checked: D, source: "US trade.gov / Law 9518 (Costa Rica EV)", source_url: "https://www.trade.gov/market-intelligence/costa-rica-electric-vehicles", confidence: "medium", needs_review: true, notes: "Fully electric vehicles exempt (hybrids partial). Verify with Costa Rica Customs." },
  // Guatemala
  { taxrule_id: "gt-duty", country_id: "guatemala", tax_type: "import_duty", label: "Import duty (DAI)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "West Coast Shipping / AB Group (Guatemala)", source_url: "https://www.wcshipping.com/blog/guatemala-vehicle-import-rules-2025-sat-regulations-vs-reality-guide", confidence: "low", needs_review: true, notes: "DAI 0–15% (0% under CAFTA-DR); sources cite 15–20% for vehicles. Verify with SAT.", value_min: 15, value_max: 20 },
  { taxrule_id: "gt-vat", country_id: "guatemala", tax_type: "vat", label: "IVA (VAT)", rate_pct: 12, basis: "CIF + duty", effective_date: null, last_checked: D, source: "West Coast Shipping (Guatemala)", source_url: "https://www.wcshipping.com/blog/guatemala-vehicle-import-rules-2025-sat-regulations-vs-reality-guide", confidence: "medium", needs_review: false },
  { taxrule_id: "gt-iprima", country_id: "guatemala", tax_type: "excise", label: "IPRIMA (first-registration tax)", rate_pct: 20, basis: "Original invoice", effective_date: null, last_checked: D, source: "Living in Guatemala / AB Group (SAT import guide)", source_url: "https://livinginguatemala.com/tramites/sat-importacion-vehiculo/", confidence: "low", needs_review: true, notes: "~20% for vehicles up to five passengers. Verify with SAT." },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "lb-beirut", name: "Beirut", country_id: "lebanon", type: "destination", note: null },
  { port_id: "ua-odesa", name: "Odesa", country_id: "ukraine", type: "destination", note: "Black Sea — principal container/RoRo entry" },
  { port_id: "ua-chornomorsk", name: "Chornomorsk", country_id: "ukraine", type: "destination", note: "Black Sea (near Odesa)" },
  { port_id: "by-minsk", name: "Minsk (via Klaipėda/Riga or Brest transit)", country_id: "belarus", type: "destination", note: "Landlocked — transit via Klaipėda (Lithuania) / Riga (Latvia) or Brest (Poland) road" },
  { port_id: "bo-santa-cruz", name: "Santa Cruz (via Iquique/Antofagasta transit)", country_id: "bolivia", type: "destination", note: "Landlocked — transit via Iquique/Antofagasta (Chile) or Matarani/Ilo (Peru)" },
  { port_id: "cr-puerto-limon", name: "Puerto Limón", country_id: "costa-rica", type: "destination", note: "Atlantic (Caribbean) coast" },
  { port_id: "cr-caldera", name: "Caldera", country_id: "costa-rica", type: "destination", note: "Pacific coast" },
  { port_id: "gt-puerto-quetzal", name: "Puerto Quetzal", country_id: "guatemala", type: "destination", note: "Pacific coast" },
  { port_id: "gt-santo-tomas", name: "Santo Tomás de Castilla", country_id: "guatemala", type: "destination", note: "Atlantic (Caribbean) coast" },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-lb-beirut", origin_port_id: "cn-shanghai", destination_port_id: "lb-beirut", est_days_min: 22, est_days_max: 32, shipping_method: "roro", source: "Industry route estimates (Suez / East Mediterranean)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-ua-odesa", origin_port_id: "cn-shanghai", destination_port_id: "ua-odesa", est_days_min: 24, est_days_max: 34, shipping_method: "roro", source: "Industry route estimates (Black Sea)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-by-minsk", origin_port_id: "cn-shanghai", destination_port_id: "by-minsk", est_days_min: 30, est_days_max: 42, shipping_method: "container", source: "Industry route estimates (sea to Klaipėda/Riga + road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-bo-santa-cruz", origin_port_id: "cn-shanghai", destination_port_id: "bo-santa-cruz", est_days_min: 32, est_days_max: 46, shipping_method: "roro", source: "Industry route estimates (via Iquique/Arica + rail/road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-cr-puerto-limon", origin_port_id: "cn-shanghai", destination_port_id: "cr-puerto-limon", est_days_min: 26, est_days_max: 36, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-gt-puerto-quetzal", origin_port_id: "cn-shanghai", destination_port_id: "gt-puerto-quetzal", est_days_min: 26, est_days_max: 36, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

console.log("countries:", countries.countries.length, "| rules:", importrules.rules.length, "| taxes:", taxrules.taxrules.length, "| ports:", ports.ports.length, "| routes:", routes.routes.length);
