// Batch: market-countries11 — add 6 RHD countries + data layer.
// Countries: Botswana (Africa RHD, no fixed age cap, 27% duty + 12% VAT, SACU),
//            Namibia (Africa RHD, 8-year age limit, Walvis Bay, NamRA),
//            Mauritius (Africa RHD island, ~3-4yr age cap, excise + 15% VAT),
//            Jamaica (Caribbean RHD, 6yr car age limit, Trade Board),
//            Trinidad & Tobago (Caribbean RHD, 6yr car / 10yr LCV from Jan 2026),
//            Brunei (Southeast Asia RHD, 3yr private age cap, no VAT).
// All regulatory data cited to official/reliable sources; every statement carries source URL + last_checked (2026-10-07).
const fs = require("fs");
const base = "shared/data";
const D = "2026-10-07";
const read = (f) => JSON.parse(fs.readFileSync(`${base}/${f}`, "utf8"));
const write = (f, obj, indent = 2) => fs.writeFileSync(`${base}/${f}`, JSON.stringify(obj, null, indent) + "\n");

const WIKI_LHT = "https://en.wikipedia.org/wiki/Left-_and_right-hand_traffic";

// ---------- countries.json ----------
const countries = read("countries.json");
const newCountries = [
  { country_id: "botswana", name: "Botswana", name_zh: "博茨瓦纳", region: "africa", drive_side: "rhd", currency: "BWP", status: "active", source: "Botswana Unified Revenue Service (BURS) / SACU", source_url: "https://www.burs.org.bw", source_date: D, confidence: "high" },
  { country_id: "namibia", name: "Namibia", name_zh: "纳米比亚", region: "africa", drive_side: "rhd", currency: "NAD", status: "active", source: "Namibia Revenue Agency (NamRA) / Namibia Trade Portal", source_url: "https://www.namra.org.na", source_date: D, confidence: "high" },
  { country_id: "mauritius", name: "Mauritius", name_zh: "毛里求斯", region: "africa", drive_side: "rhd", currency: "MUR", status: "active", source: "Mauritius Revenue Authority (MRA)", source_url: "https://www.mra.mu", source_date: D, confidence: "high" },
  { country_id: "jamaica", name: "Jamaica", name_zh: "牙买加", region: "caribbean", drive_side: "rhd", currency: "JMD", status: "active", source: "Trade Board Limited (Jamaica) / Jamaica Customs Agency", source_url: "https://www.tradeboard.gov.jm/ttbl/MV_Age.php", source_date: D, confidence: "high" },
  { country_id: "trinidad-and-tobago", name: "Trinidad and Tobago", name_zh: "特立尼达和多巴哥", region: "caribbean", drive_side: "rhd", currency: "TTD", status: "active", source: "Trinidad & Tobago Customs & Excise Division", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", source_date: D, confidence: "high" },
  { country_id: "brunei", name: "Brunei Darussalam", name_zh: "文莱", region: "southeast-asia", drive_side: "rhd", currency: "BND", status: "active", source: "Royal Customs and Excise Department (RCED)", source_url: "https://www.customs.gov.bn", source_date: D, confidence: "high" },
];
for (const c of newCountries) {
  if (!countries.countries.find((x) => x.country_id === c.country_id)) countries.countries.push(c);
}
write("countries.json", countries);

// ---------- importrules.json ----------
const importrules = read("importrules.json");
const rules = [
  // ===== Botswana (RHD, no fixed age cap, 27% duty + 12% VAT, SACU, landlocked via Durban) =====
  { rule_id: "bw-drive-side", country_id: "botswana", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Botswana drives on the left and accepts only right-hand-drive (RHD) vehicles. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "SUVHUB (Botswana import rules) / Left- and right-hand traffic (Wikipedia)", source_url: "https://suvhub.com/import-rules/botswana", confidence: "high", needs_review: false },
  { rule_id: "bw-age-limit", country_id: "botswana", category: "vehicle_age", title: "No fixed age limit (duty climbs with age)", rule_text: "Botswana has no hard cut-off on the age of imported used vehicles, but duty and taxes are assessed on CIF value and generally climb with age. A 2-year no-sale restriction applies to imported vehicles. Confirm the current BURS schedule before sourcing older stock.", effective_date: null, last_checked: D, source: "SUVHUB (Botswana import rules) / One Roof Autos (Botswana import policy)", source_url: "https://suvhub.com/import-rules/botswana", confidence: "medium", needs_review: true, notes: "No age ban, but tax climbs with age + 2-year no-sale rule — verify with BURS." },
  { rule_id: "bw-import-process", country_id: "botswana", category: "import_eligibility", title: "SACU duty on CIF + import permit (Durban transit)", rule_text: "Botswana is landlocked; vehicles arrive via Durban (South Africa) under the Southern African Customs Union (SACU) common external tariff. Duty is assessed on CIF value (customs duty 27% + VAT 12% per importer guides). An import permit from BURS is required. Confirm the document set with BURS.", effective_date: null, last_checked: D, source: "One Roof Autos (Botswana import policy) / SUVHUB", source_url: "https://oneroofautos.com/import-policy/botswana", confidence: "medium", needs_review: true, notes: "Landlocked — Durban (SA) transit + SACU. Duty 27% + VAT 12% per guides; verify with BURS." },
  { rule_id: "bw-ev-policy", country_id: "botswana", category: "ev_policy", title: "No EV-specific import-duty relief confirmed", rule_text: "No EV-specific import-duty relief was confirmed for Botswana in the sources reviewed; EVs follow the standard SACU duty + VAT stack. Confirm current EV treatment with BURS.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with BURS." },

  // ===== Namibia (RHD, strict 8-year age limit, Walvis Bay, NamRA) =====
  { rule_id: "na-drive-side", country_id: "namibia", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Namibia drives on the left and accepts only right-hand-drive (RHD) vehicles. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "SUVHUB (Namibia import rules) / Left- and right-hand traffic (Wikipedia)", source_url: "https://suvhub.com/import-rules/namibia", confidence: "high", needs_review: false },
  { rule_id: "na-age-limit", country_id: "namibia", category: "vehicle_age", title: "Strict 8-year age limit (from first registration)", rule_text: "Namibia enforces a strict 8-year age limit on imported used vehicles, counted from the vehicle's first registration date (not model year). An import permit is required before shipping. Source units comfortably inside the 8-year window and confirm with NamRA.", effective_date: null, last_checked: D, source: "SUVHUB (Namibia import rules) / Namibia Trade Portal (second-hand motor vehicle requirements)", source_url: "https://namibiatradeportal.gov.na/general-trade-information", confidence: "high", needs_review: true, notes: "8 years from first registration + import permit — verify with NamRA before sourcing stock." },
  { rule_id: "na-import-process", country_id: "namibia", category: "import_eligibility", title: "Duty on CIF value + Walvis Bay clearance (NamRA)", rule_text: "Duty and taxes are assessed on CIF value (rates vary by engine size, body type and sometimes emissions). The main port is Walvis Bay — a direct deep-water port on the Atlantic coast. NamRA (Namibia Revenue Agency) is the customs authority. Confirm the current duty schedule with NamRA.", effective_date: null, last_checked: D, source: "WalvisLink (2026 vehicle import via Walvis Bay) / SUVHUB", source_url: "https://walvislink.com/resources/vehicle-import-namibia-walvis-bay", confidence: "medium", needs_review: true, notes: "Duty on CIF (varies) + Walvis Bay. Verify document set with NamRA." },
  { rule_id: "na-ev-policy", country_id: "namibia", category: "ev_policy", title: "EV treatment not separately documented", rule_text: "No EV-specific import-duty relief was confirmed for Namibia in the sources reviewed; EVs follow the standard duty + VAT stack. Confirm current EV treatment with NamRA.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with NamRA." },

  // ===== Mauritius (RHD island, ~3-4yr age cap, excise + 15% VAT, Port Louis) =====
  { rule_id: "mu-drive-side", country_id: "mauritius", category: "drive_side", title: "Right-hand drive (RHD) only; LHD not for normal use", rule_text: "Mauritius drives on the left and registers right-hand-drive (RHD) vehicles; left-hand-drive vehicles are not permitted for normal use. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "KMC Japan (Mauritius import guide) / Left- and right-hand traffic (Wikipedia)", source_url: "https://kmcjapan.co.jp/import-guide/mauritius", confidence: "high", needs_review: false },
  { rule_id: "mu-age-limit", country_id: "mauritius", category: "vehicle_age", title: "Tight age cap (~3–4 years, set by Finance Act)", rule_text: "Mauritius caps used-car imports at a short maximum age — historically around 3–4 years from first registration/manufacture, set by the Finance Act in force and adjusted in each budget. Confirm the current MRA age rule in writing before bidding; LHD is not permitted.", effective_date: null, last_checked: D, source: "KMC Japan (Mauritius import guide) / Expat Mauritius (customs & taxes 2026)", source_url: "https://expat-mauritius.com/en/blog/importing-a-car-to-mauritius-customs-taxes-procedures-2026/", confidence: "medium", needs_review: true, notes: "~3–4 years, moves with the budget — verify the current Finance Act age with MRA before purchase." },
  { rule_id: "mu-import-process", country_id: "mauritius", category: "import_eligibility", title: "Excise + VAT on CIF + MRA/NLTA clearance", rule_text: "Landed cost is dominated by excise duty plus 15% VAT on importation (MRA tariff). Vehicles discharge at Port Louis and require MRA customs clearance plus an NLTA roadworthiness inspection. Confirm the document set with MRA.", effective_date: null, last_checked: D, source: "KMC Japan (Mauritius import guide) / Expat Mauritius", source_url: "https://expat-mauritius.com/en/blog/importing-a-car-to-mauritius-customs-taxes-procedures-2026/", confidence: "medium", needs_review: true, notes: "Excise + 15% VAT, Port Louis, MRA + NLTA. Verify with MRA." },
  { rule_id: "mu-ev-policy", country_id: "mauritius", category: "ev_policy", title: "EV/hybrid excise concessions (confirm with MRA)", rule_text: "Mauritius has historically offered reduced excise for electric and hybrid vehicles under successive Finance Acts. A current, specific EV duty rate was not confirmed in the sources reviewed — confirm the current EV/hybrid excise treatment with MRA.", effective_date: null, last_checked: D, source: "Expat Mauritius (customs & taxes 2026) / MRA", source_url: "https://expat-mauritius.com/en/blog/importing-a-car-to-mauritius-customs-taxes-procedures-2026/", confidence: "low", needs_review: true, notes: "EV/hybrid excise concessions — verify the current rate with MRA." },

  // ===== Jamaica (RHD, 6yr car age limit, Trade Board, Kingston) =====
  { rule_id: "jm-drive-side", country_id: "jamaica", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Jamaica drives on the left and registers right-hand-drive (RHD) vehicles. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "Left- and right-hand traffic (Wikipedia) / Trade Board Limited (Jamaica)", source_url: WIKI_LHT, confidence: "high", needs_review: false },
  { rule_id: "jm-age-limit", country_id: "jamaica", category: "vehicle_age", title: "Age limit: 6 years (cars/SUVs), 10 years (pickups/vans)", rule_text: "Under Jamaica's Motor Vehicle Import Policy (Ministry Paper #36/14), cars, sedans, station wagons and SUVs (≤8 seats) are limited to 6 years old; pick-up trucks, panel vans and small buses are limited to 10 years. Confirm the current schedule with the Trade Board / Jamaica Customs Agency.", effective_date: null, last_checked: D, source: "Trade Board Limited (Jamaica) — Motor Vehicle Age Limit (Ministry Paper #36/14)", source_url: "https://www.tradeboard.gov.jm/ttbl/MV_Age.php", confidence: "high", needs_review: true, notes: "6 years (cars/SUVs) / 10 years (pickups/vans) — verify with the Trade Board." },
  { rule_id: "jm-import-process", country_id: "jamaica", category: "import_eligibility", title: "Import permit (2 vehicles / 3 years) + Kingston clearance", rule_text: "Individuals may import up to two vehicles every three years under a Motor Vehicle Import Permit from the Trade Board (resident status applies). Vehicles clear through Kingston via the Jamaica Customs Agency. Confirm the permit and document set with the Trade Board.", effective_date: null, last_checked: D, source: "Trade Board Limited (Jamaica) — Motor Vehicle General", source_url: "https://www.tradeboard.gov.jm/ttbl/MV_General.php", confidence: "high", needs_review: true, notes: "Import permit (2 vehicles/3 years for individuals) + Kingston. Verify with the Trade Board." },
  { rule_id: "jm-ev-policy", country_id: "jamaica", category: "ev_policy", title: "EV duty concessions (reduced duty)", rule_text: "Jamaica offers reduced import duty for electric vehicles (and, previously, hybrids) to encourage EV adoption, and continues to build public charging. Confirm the current EV duty rate and any age/eligibility carve-outs with the Jamaica Customs Agency.", effective_date: null, last_checked: D, source: "Jamaica Customs Agency / Trade Board Limited (EV policy reporting)", source_url: "https://jca.gov.jm", confidence: "low", needs_review: true, notes: "EV duty concessions — verify current rate with the Jamaica Customs Agency." },

  // ===== Trinidad & Tobago (RHD, 6yr car / 10yr LCV from Jan 2026, 20-30% duty + 12.5% VAT) =====
  { rule_id: "tt-drive-side", country_id: "trinidad-and-tobago", category: "drive_side", title: "Right-hand drive (RHD) only", rule_text: "Trinidad & Tobago drives on the left and registers right-hand-drive (RHD) vehicles. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "Pace Motors Thailand (2026 Trinidad import regulations) / Left- and right-hand traffic (Wikipedia)", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", confidence: "high", needs_review: false },
  { rule_id: "tt-age-limit", country_id: "trinidad-and-tobago", category: "vehicle_age", title: "Age limit: 6 years (private cars), 10 years (LCV) from Jan 2026", rule_text: "Effective 1 January 2026, Trinidad & Tobago extended its used-vehicle age limits: private cars (SUVs, sedans, station wagons) may now be imported up to 6 years old (previously 3), and light commercial vehicles up to 10 years (previously 7). Some categories are 8 years. Confirm the exact category cut-off with the Customs & Excise Division.", effective_date: "2026-01-01", last_checked: D, source: "Pace Motors Thailand (2026 Trinidad import regulations)", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", confidence: "medium", needs_review: true, notes: "6yr cars / 10yr LCV from Jan 2026 — verify category cut-offs with the Customs & Excise Division." },
  { rule_id: "tt-import-process", country_id: "trinidad-and-tobago", category: "import_eligibility", title: "20–30% duty + MVT + 12.5% VAT (Port of Spain)", rule_text: "Landed cost is set by import duty (typically 20–30% of CIF), a Motor Vehicle Tax (MVT) banded by engine capacity, and 12.5% VAT on the duty-inclusive value. Vehicles clear at Port of Spain. Confirm the current stack with the Customs & Excise Division.", effective_date: null, last_checked: D, source: "Pace Motors Thailand (2026 Trinidad import regulations)", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", confidence: "medium", needs_review: true, notes: "20–30% duty + MVT (engine) + 12.5% VAT. Verify with the Customs & Excise Division." },
  { rule_id: "tt-ev-policy", country_id: "trinidad-and-tobago", category: "ev_policy", title: "EV/hybrid eligibility tightened; no clear relief", rule_text: "Trinidad & Tobago tightened eligibility rules for hybrid and electric vehicle imports under the 2026 Motor Vehicles and Road Traffic Act amendments; no clear EV duty relief was confirmed. Confirm current EV treatment with the Customs & Excise Division.", effective_date: "2026-01-01", last_checked: D, source: "Pace Motors Thailand (2026 Trinidad import regulations)", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", confidence: "low", needs_review: true, notes: "EV/hybrid eligibility tightened — verify with the Customs & Excise Division." },

  // ===== Brunei (RHD, 3yr private age cap, import+excise, no VAT, Muara) =====
  { rule_id: "bn-drive-side", country_id: "brunei", category: "drive_side", title: "Right-hand drive (RHD) required; LHD re-export only", rule_text: "Brunei Darussalam drives on the left. Right-hand-drive vehicles are permitted; left-hand-drive vehicles are allowed only for temporary tour use and must be re-exported. A China-market LHD unit cannot be registered as-is — source an RHD export unit.", effective_date: null, last_checked: D, source: "Washin Auto (Brunei import guide) / Left- and right-hand traffic (Wikipedia)", source_url: "https://www.washinauto.com/import-guide?country=Brunei", confidence: "high", needs_review: false },
  { rule_id: "bn-age-limit", country_id: "brunei", category: "vehicle_age", title: "Age limit: 3 years private (4 from manufacture)", rule_text: "Imported used vehicles for private use must be no more than 3 years old from original registration and no more than 4 years from the year of manufacture; commercial vehicles are limited to 60 months / 6 years. Confirm the current rule with the Royal Customs and Excise Department (RCED).", effective_date: null, last_checked: D, source: "Washin Auto (Brunei import guide)", source_url: "https://www.washinauto.com/import-guide?country=Brunei", confidence: "medium", needs_review: true, notes: "3yr private / 60-month commercial — verify with RCED." },
  { rule_id: "bn-import-process", country_id: "brunei", category: "import_eligibility", title: "Import + excise duty (no VAT) + Muara clearance", rule_text: "Brunei levies import and excise duties on vehicles but has no VAT. Used vehicles require an approval permit before departure and a pre-delivery inspection at origin. The main port is Muara. Confirm the document set with RCED.", effective_date: null, last_checked: D, source: "Washin Auto (Brunei import guide) / Expat Focus (Brunei car import)", source_url: "https://www.expatfocus.com/brunei/guide/brunei-buying-or-importing-a-car", confidence: "medium", needs_review: true, notes: "Import+excise, no VAT, Muara. Approval permit before departure. Verify with RCED." },
  { rule_id: "bn-ev-policy", country_id: "brunei", category: "ev_policy", title: "EV treatment not separately documented", rule_text: "No EV-specific import-duty relief was confirmed for Brunei in the sources reviewed; EVs follow the standard import + excise duty structure (no VAT). Confirm current EV treatment with RCED.", effective_date: null, last_checked: D, source: "Needs verification (no EV-specific source located)", source_url: null, confidence: "unknown", needs_review: true, notes: "EV treatment not documented — verify with RCED." },
];
for (const r of rules) {
  if (!importrules.rules.find((x) => x.rule_id === r.rule_id)) importrules.rules.push(r);
}
write("importrules.json", importrules);

// ---------- taxrules.json ----------
const taxrules = read("taxrules.json");
const taxes = [
  // Botswana
  { taxrule_id: "bw-duty", country_id: "botswana", tax_type: "import_duty", label: "Import duty (customs)", rate_pct: 27, basis: "CIF value", effective_date: null, last_checked: D, source: "One Roof Autos (Botswana import policy)", source_url: "https://oneroofautos.com/import-policy/botswana", confidence: "medium", needs_review: true, notes: "27% customs duty per importer guides (SACU CET). Verify with BURS." },
  { taxrule_id: "bw-vat", country_id: "botswana", tax_type: "vat", label: "VAT", rate_pct: 12, basis: "CIF + duty", effective_date: null, last_checked: D, source: "One Roof Autos (Botswana import policy)", source_url: "https://oneroofautos.com/import-policy/botswana", confidence: "low", needs_review: true, notes: "12% VAT per importer guides — confirm the current BURS VAT rate before trading." },
  // Namibia
  { taxrule_id: "na-duty", country_id: "namibia", tax_type: "import_duty", label: "Import duty (SACU tariff)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "SUVHUB / WalvisLink (Namibia import rules)", source_url: "https://walvislink.com/resources/vehicle-import-namibia-walvis-bay", confidence: "low", needs_review: true, notes: "Assessed on CIF (SACU CET); rate varies by engine size/body type — confirm with NamRA." },
  { taxrule_id: "na-vat", country_id: "namibia", tax_type: "vat", label: "VAT", rate_pct: 15, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Namibia Revenue Agency (standard VAT rate)", source_url: "https://www.namra.org.na", confidence: "low", needs_review: true, notes: "15% standard VAT on importation — verify with NamRA." },
  // Mauritius
  { taxrule_id: "mu-excise", country_id: "mauritius", tax_type: "excise", label: "Excise duty (motor cars)", rate_pct: null, basis: "CIF value (MRA tariff)", effective_date: null, last_checked: D, source: "KMC Japan / Expat Mauritius (Mauritius customs & taxes)", source_url: "https://expat-mauritius.com/en/blog/importing-a-car-to-mauritius-customs-taxes-procedures-2026/", confidence: "low", needs_review: true, notes: "High excise on motor cars, banded by engine size (MRA tariff). Verify current excise with MRA." },
  { taxrule_id: "mu-vat", country_id: "mauritius", tax_type: "vat", label: "VAT", rate_pct: 15, basis: "CIF + excise", effective_date: null, last_checked: D, source: "Expat Mauritius (customs & taxes 2026)", source_url: "https://expat-mauritius.com/en/blog/importing-a-car-to-mauritius-customs-taxes-procedures-2026/", confidence: "medium", needs_review: false },
  // Jamaica
  { taxrule_id: "jm-duty", country_id: "jamaica", tax_type: "import_duty", label: "Import duty (motor vehicles)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Jamaica Customs Agency (motor vehicle processing)", source_url: "https://jca.gov.jm/business/motor-vehicle-processing/motor-vehicle-age-limit/", confidence: "low", needs_review: true, notes: "Import duty varies by vehicle type/value — confirm the current rate with the Jamaica Customs Agency." },
  { taxrule_id: "jm-gct", country_id: "jamaica", tax_type: "vat", label: "GCT (General Consumption Tax)", rate_pct: 15, basis: "CIF + duty", effective_date: null, last_checked: D, source: "Jamaica Customs Agency (motor vehicle processing)", source_url: "https://jca.gov.jm", confidence: "low", needs_review: true, notes: "15% GCT on duty-inclusive value — verify with the Jamaica Customs Agency." },
  { taxrule_id: "jm-ev-duty", country_id: "jamaica", tax_type: "import_duty", label: "Import duty (electric vehicles, reduced)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Jamaica Customs Agency / Trade Board Limited (EV policy)", source_url: "https://jca.gov.jm", confidence: "low", needs_review: true, notes: "Reduced import duty for EVs — verify the current rate with the Jamaica Customs Agency." },
  // Trinidad & Tobago
  { taxrule_id: "tt-duty", country_id: "trinidad-and-tobago", tax_type: "import_duty", label: "Import duty", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Pace Motors Thailand (2026 Trinidad import regulations)", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", confidence: "medium", needs_review: true, notes: "20–30% of CIF (some sources cite higher). Verify with the Customs & Excise Division.", value_min: 20, value_max: 30 },
  { taxrule_id: "tt-mvt", country_id: "trinidad-and-tobago", tax_type: "other", label: "Motor Vehicle Tax (MVT)", rate_pct: null, basis: "Engine capacity (banded)", effective_date: null, last_checked: D, source: "Pace Motors Thailand (2026 Trinidad import regulations)", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", confidence: "low", needs_review: true, notes: "MVT banded by engine capacity (larger engines pay more). Verify with the Customs & Excise Division." },
  { taxrule_id: "tt-vat", country_id: "trinidad-and-tobago", tax_type: "vat", label: "VAT", rate_pct: 12.5, basis: "CIF + duty + MVT", effective_date: null, last_checked: D, source: "Pace Motors Thailand (2026 Trinidad import regulations)", source_url: "https://www.pacemotorsthailand.com/blog/2026-trinidad-vehicle-import-regulations-direct", confidence: "medium", needs_review: false },
  // Brunei
  { taxrule_id: "bn-duty", country_id: "brunei", tax_type: "import_duty", label: "Import duty + excise (no VAT)", rate_pct: null, basis: "CIF value", effective_date: null, last_checked: D, source: "Expat Focus (Brunei car import) / RCED", source_url: "https://www.expatfocus.com/brunei/guide/brunei-buying-or-importing-a-car", confidence: "low", needs_review: true, notes: "Import + excise duties levied; no VAT in Brunei. Verify current rates with RCED." },
];
for (const t of taxes) {
  if (!taxrules.taxrules.find((x) => x.taxrule_id === t.taxrule_id)) taxrules.taxrules.push(t);
}
write("taxrules.json", taxrules);

// ---------- ports.json ----------
const ports = read("ports.json");
const newPorts = [
  { port_id: "bw-gaborone", name: "Gaborone (via Durban transit)", country_id: "botswana", type: "destination", note: "Landlocked — transit via Durban (South Africa), SACU border post" },
  { port_id: "na-walvis-bay", name: "Walvis Bay", country_id: "namibia", type: "destination", note: "Direct deep-water port on the Atlantic coast" },
  { port_id: "mu-port-louis", name: "Port Louis", country_id: "mauritius", type: "destination", note: null },
  { port_id: "jm-kingston", name: "Kingston", country_id: "jamaica", type: "destination", note: null },
  { port_id: "tt-port-of-spain", name: "Port of Spain", country_id: "trinidad-and-tobago", type: "destination", note: null },
  { port_id: "bn-muara", name: "Muara", country_id: "brunei", type: "destination", note: null },
];
for (const p of newPorts) {
  if (!ports.ports.find((x) => x.port_id === p.port_id)) ports.ports.push(p);
}
write("ports.json", ports);

// ---------- routes.json ----------
const routes = read("routes.json");
const newRoutes = [
  { route_id: "cn-shanghai-to-bw-gaborone", origin_port_id: "cn-shanghai", destination_port_id: "bw-gaborone", est_days_min: 28, est_days_max: 40, shipping_method: "roro", source: "Industry route estimates (sea to Durban + road transit)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-na-walvis-bay", origin_port_id: "cn-shanghai", destination_port_id: "na-walvis-bay", est_days_min: 24, est_days_max: 34, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-mu-port-louis", origin_port_id: "cn-shanghai", destination_port_id: "mu-port-louis", est_days_min: 20, est_days_max: 30, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-jm-kingston", origin_port_id: "cn-shanghai", destination_port_id: "jm-kingston", est_days_min: 30, est_days_max: 42, shipping_method: "roro", source: "Industry route estimates (via Panama transshipment)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-shanghai-to-tt-port-of-spain", origin_port_id: "cn-shanghai", destination_port_id: "tt-port-of-spain", est_days_min: 30, est_days_max: 42, shipping_method: "roro", source: "Industry route estimates (via Panama transshipment)", source_url: null, last_checked: D, confidence: "low" },
  { route_id: "cn-guangzhou-to-bn-muara", origin_port_id: "cn-guangzhou", destination_port_id: "bn-muara", est_days_min: 7, est_days_max: 14, shipping_method: "roro", source: "Industry route estimates", source_url: null, last_checked: D, confidence: "low" },
];
for (const r of newRoutes) {
  if (!routes.routes.find((x) => x.route_id === r.route_id)) routes.routes.push(r);
}
write("routes.json", routes);

console.log("countries:", countries.countries.length, "| rules:", importrules.rules.length, "| taxes:", taxrules.taxrules.length, "| ports:", ports.ports.length, "| routes:", routes.routes.length);
